import Head from "next/head";
import styles from "../../styles/Home.module.css";

export default function AboutIt() {
  return (
    <div>
      <Head>
        <title>Propaganda Diary | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container + " " + styles.aboutPageWrap}>
        <p className="c6">
          <span className="c2">
            Il progetto sulla disinformazione sull&#39;Ucraina nei media
            tedeschi e italiani si basa sulla metodologia. Qui puoi ottenere le
            informazioni sui nostri metodi e politiche.
          </span>
        </p>
        <p className="c1">
          <span className="c2"></span>
        </p>

        <h2 className="c6">
          <span className="c4">Liste bianche e nere dei media</span>
        </h2>
        <p className="c1">
          <span className="c2"></span>
        </p>

        <p className="c6">
          <span className="c2">
            In primo luogo, per formare il database sulla disinformazione era
            necessario identificare i principali mezzi di comunicazione nei
            paesi interessati e distinguere le fonti credibili da quelle
            discutibili. Pertanto, abbiamo creato liste bianche e nere di media
            in Germania e in Italia.{" "}
          </span>
        </p>
        <p className="c1">
          <span className="c2"></span>
        </p>
        <p className="c6">
          <span className="c2">
            I media nella lista bianca sono media di alta qualit&agrave; che
            forniscono informazioni affidabili sulla politica estera e interna
            dell&#39;Ucraina. Al contrario, le fonti della lista nera diffondono
            regolarmente notizie false sull&#39;Ucraina.
          </span>
        </p>
        <p className="c1">
          <span className="c2"></span>
        </p>
        <p className="c6">
          <span className="c2">
            Per differenziare le fonti e creare questi elenchi abbiamo
            utilizzato i seguenti criteri:
          </span>
        </p>
        <p className="c1">
          <span className="c2"></span>
        </p>
        <ul className="c10 lst-kix_f6a3t5dc9e1v-0 start">
          <li className="c0 li-bullet-0">
            <span className="c7">Contenuto</span>
            <span className="c2">
              . Tutti i media, sia nella lista bianca che nella lista nera,
              riportano regolarmente notizie e pubblicano articoli analitici
              sulla politica, le relazioni internazionali, in particolare
              l&#39;Ucraina.
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c7">Standard professionali</span>
            <span className="c2">
              . I media di alta qualit&agrave; nella lista bianca devono
              soddisfare gli standard giornalistici: completezza e
              imparzialit&agrave; della copertura delle notizie;
              obiettivit&agrave; e neutralit&agrave; emotiva; equilibrio di
              opinioni; disponibilit&agrave; e affidabilit&agrave; delle fonti
              di informazione; separazione di fatti e commenti. I media nella
              lista nera trascurano costantemente questi standard quando
              riferiscono sull&#39;Ucraina.
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c7">Propriet&agrave; e trasparenza</span>
            <span className="c2">
              . I media devono riferire pubblicamente sul suo proprietario, sul
              finanziamento e sul possibile conflitto di interessi. Ad esempio,
              alcuni media italiani e tedeschi sono direttamente collegati alle
              agenzie di stampa statali russe. Pertanto, molto probabilmente
              tali media diffonderanno disinformazione sull&#39;Ucraina.
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c7">
              Risultati del monitoraggio dei media da Media Bias/Fact Check
            </span>
            <span className="c9">
              . Abbiamo selezionato alcuni dei media in base alla risorsa{" "}
            </span>
            <span className="c5">
              <a
                className="c3"
                href="https://www.google.com/url?q=https://mediabiasfactcheck.com/&amp;sa=D&amp;source=editors&amp;ust=1648822303046360&amp;usg=AOvVaw2efcN0GYnxj22YSD1ZodqC"
              >
                Media Bias / Fact Check
              </a>
            </span>
            <span className="c2">
              , un sito Web indipendente che valuta la distorsione,
              l&#39;accuratezza dei fatti e la credibilit&agrave; delle fonti.
              Secondo questa risorsa, i media selezionati nella lista nera hanno
              un livello di rendicontazione fattuale molto basso o misto. I
              media nella lista bianca sono classificati come le fonti meno
              distorte e hanno un alto livello di resoconto dei fatti.
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c7">
              Risultati del monitoraggio dei media da EUvsDisinfo
            </span>
            <span className="c9">
              . Inoltre, abbiamo utilizzato i database EUvsDisinfo su{" "}
            </span>
            <span className="c5">
              <a
                className="c3"
                href="https://www.google.com/url?q=https://euvsdisinfo.eu/disinformation-cases/?text%3D%26date%3D%26disinfo_language%255B%255D%3DGerman%26disinfo_countries%255B%255D%3D77554%26per_page%3D&amp;sa=D&amp;source=editors&amp;ust=1648822303046890&amp;usg=AOvVaw2ABFn2GhK6Ylcx8FcEe735"
              >
                Germania
              </a>
            </span>
            <span className="c9">&nbsp;e </span>
            <span className="c5">
              <a
                className="c3"
                href="https://www.google.com/url?q=https://euvsdisinfo.eu/disinformation-cases/?text%3D%26date%3D%26disinfo_language%255B%255D%3DItalian%26disinfo_countries%255B%255D%3D77582%26per_page%3D&amp;sa=D&amp;source=editors&amp;ust=1648822303047163&amp;usg=AOvVaw0C3BPa5Py12u7B2YtC7bwq"
              >
                Italia
              </a>
            </span>
            <span className="c9">
              , nonch&eacute; casi di falsa distribuzione registrati da
              fact-checker tedeschi e italiani, che hanno firmato il codice di
              principio IFCN.{" "}
            </span>
            <span className="c5">
              <a
                className="c3"
                href="https://www.google.com/url?q=https://euvsdisinfo.eu/about/&amp;sa=D&amp;source=editors&amp;ust=1648822303047351&amp;usg=AOvVaw3_azYzVU0QEyGquplyx6iu"
              >
                EUvsDisinfo
              </a>
            </span>
            <span className="c2">
              &nbsp;&egrave; il progetto della East StratCom Task Force del
              Servizio europeo per l&#39;azione esterna. &Egrave; stato
              istituito appositamente per monitorare e contrastare le campagne
              di disinformazione russe in Europa.
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c7">
              Risultati del nostro monitoraggio dei media.{" "}
            </span>
            <span className="c2">
              Quando abbiamo selezionato i media per il monitoraggio, ci siamo
              concentrati sulla qualit&agrave; dei rapporti sull&#39;Ucraina. Le
              fonti che hanno pubblicato in precedenza la disinformazione russa
              sono state aggiunte alla lista nera.
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c7">
              Consultazioni con fact-checker e giornalisti tedeschi e italiani.{" "}
            </span>
            <span className="c2">
              Abbiamo anche chiesto consiglio ai colleghi che lavorano in
              Germania e in Italia. Rappresentanti di diverse organizzazioni ci
              hanno consigliato di prestare attenzione ad alcuni media che in
              precedenza diffondevano notizie false.
            </span>
          </li>
        </ul>
        <p className="c1">
          <span className="c2"></span>
        </p>
        <p className="c6">
          <span className="c4">disinformazione</span>
        </p>
        <p className="c1">
          <span className="c2"></span>
        </p>
        <p className="c6">
          <span className="c2">
            Il database &egrave; composto da centinaia di notizie manipolative
            provenienti dai media tedeschi e italiani. Per classificare questo
            set di dati abbiamo classificato le notizie in narrazioni pericolose
            e destabilizzanti della campagna di disinformazione russa.
          </span>
        </p>
        <p className="c1">
          <span className="c2"></span>
        </p>
        <p className="c6">
          <span className="c2">
            I diversi notiziari sono esempi di un&#39;unica narrativa di
            disinformazione quando trasmettono lo stesso messaggio, esplicito o
            nascosto, inteso a influenzare l&#39;opinione pubblica nei paesi
            rilevanti distorcendo il quadro della realt&agrave;. Tutte le
            narrazioni nel database sono messaggi tipici della campagna di
            disinformazione russa contro l&#39;Ucraina. Ad esempio,
            &quot;L&#39;Ucraina sta continuando il rafforzamento militare nel
            Donbas&quot; e &quot;L&#39;Ucraina sta violando il regime di cessate
            il fuoco&quot; possono essere chiari esempi della narrativa
            &quot;L&#39;Ucraina non riesce a mantenere gli impegni previsti
            dagli accordi di Minsk&quot;, poich&eacute; hanno lo stesso
            significato e scopo in termini di disinformazione.
          </span>
        </p>
        <p className="c1">
          <span className="c2"></span>
        </p>
        <p className="c6">
          <span className="c2">
            Ci sono anche sottotipi di narrazioni di disinformazione. Questi
            sottotipi specificano la narrativa generale. Ad esempio, &quot;Il
            colpo di stato organizzato dagli Stati Uniti in Ucraina nel
            2014&quot; &egrave; un sottotipo della narrativa &quot;Maidan nel
            2014 &egrave; stato un colpo di stato&quot;.
          </span>
        </p>
        <p className="c1">
          <span className="c2"></span>
        </p>
        <p className="c6">
          <span className="c2">
            Tuttavia, spesso &egrave; impossibile identificare le motivazioni
            esatte degli autori, che hanno partecipato alla diffusione di
            notizie false. Pertanto non possiamo confermare che tutti questi
            autori e media diffondano apposta disinformazione sull&#39;Ucraina.
            Allo stesso tempo, le narrazioni in questi media sono simili o quasi
            identiche a quelle diffuse dai funzionari della Federazione Russa.
          </span>
        </p>
        <p className="c1">
          <span className="c2"></span>
        </p>
        <p className="c6">
          <span className="c4">Tipi di disinformazione</span>
        </p>
        <p className="c1">
          <span className="c2"></span>
        </p>
        <p className="c6">
          <span className="c2">
            La disinformazione &egrave; un&#39;informazione falsa o fuorviante
            diffusa per influenzare l&#39;opinione pubblica e/o oscurare la
            verit&agrave;. &Egrave; spesso usato deliberatamente come strumento
            nella guerra dell&#39;informazione. Nel caso del conflitto
            Ucraina-Russia, la disinformazione viene utilizzata per distorcere i
            fatti sulla politica estera e interna dell&#39;Ucraina e per creare
            un&#39;immagine negativa dell&#39;Ucraina nei media e nella politica
            internazionale.
          </span>
        </p>
        <p className="c1">
          <span className="c2"></span>
        </p>
        <p className="c6">
          <span className="c2">
            Durante la valutazione dei media tedeschi e italiani dalla lista
            nera emettiamo i seguenti verdetti per ogni materiale di
            disinformazione:
          </span>
        </p>
        <p className="c1">
          <span className="c2"></span>
        </p>
        <ul className="c10 lst-kix_rjlda8yf3zfp-0 start">
          <li className="c0 li-bullet-0">
            <span className="c7">Falso</span>
            <span className="c2">
              : l&#39;informazione &egrave; completamente falsa e basata su
              fonti discutibili.
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c7">Manipolazione</span>
            <span className="c2">
              : le informazioni sono in parte vere, ma presentate in un contesto
              distorto o non completamente. L&#39;autore della manipolazione sta
              cercando di trasmettere un messaggio falso.
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c7">Teoria del complotto: </span>
            <span className="c2">
              l&#39;informazione &egrave; falsa, ma si basa su affermazioni
              completamente non verificabili, ovvero alcune teorie che spiegano
              gli eventi come risultato di un complotto segreto.
            </span>
          </li>
        </ul>
        <p className="c1">
          <span className="c2"></span>
        </p>
        <p className="c6">
          <span className="c2">
            Questi tipi di disinformazione sono metodi comuni delle campagne
            russe contro l&#39;Ucraina. Gli argomenti pi&ugrave; comuni tra le
            sue narrazioni di disinformazione sono:
          </span>
        </p>
        <p className="c1">
          <span className="c2"></span>
        </p>
        <ul className="c10 lst-kix_3j55d85lsur5-0 start">
          <li className="c0 li-bullet-0">
            <span className="c2">
              l&#39;Euromaidan/la Rivoluzione della dignit&agrave; in Ucraina;
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c2">annessione della Crimea;</span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c2">
              la guerra Ucraina-Russia in corso nel Donbas;
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c2">
              eventi storici, in particolare legati alla storia delle relazioni
              Ucraina-Russia;
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c2">
              relazioni dell&#39;Ucraina con USA, NATO, UE e altri partner;
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c2">riforme in Ucraina;</span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c2">l&#39;economia dell&#39;Ucraina;</span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c2">
              &ldquo;nazisti e ultranazionalisti&rdquo; in Ucraina;
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c2">
              teorie del complotto sul &ldquo;governo esterno&rdquo; in Ucraina,
              cio&egrave; l&#39;influenza dell&#39;Occidente sulla politica
              estera e interna dell&#39;Ucraina.
            </span>
          </li>
        </ul>
        <p className="c1">
          <span className="c2"></span>
        </p>
        <p className="c6">
          <span className="c4">Processo di verifica</span>
        </p>
        <p className="c1">
          <span className="c2"></span>
        </p>
        <p className="c6">
          <span className="c2">
            dei fatti Gli autori di VoxCheck seguono una politica trasparente
            durante la verifica dei fatti e sfatando la disinformazione russa
            sull&#39;Ucraina. Nei nostri articoli, forniamo tutte le fonti per
            la revisione in modo sufficientemente dettagliato in modo che i
            lettori possano riprodurre il nostro lavoro, a meno che la sicurezza
            personale della fonte possa essere compromessa. In questi casi,
            forniamo le informazioni pi&ugrave; dettagliate. La qualit&agrave;
            del fact-checking &egrave; assicurata dalla redazione del progetto.{" "}
          </span>
        </p>
        <p className="c1">
          <span className="c2"></span>
        </p>
        <p className="c6">
          <span className="c9">VoxCheck come </span>
          <span className="c5">
            <a
              className="c3"
              href="https://www.google.com/url?q=https://ifcncodeofprinciples.poynter.org/signatories&amp;sa=D&amp;source=editors&amp;ust=1648822303050514&amp;usg=AOvVaw279Rm4erZ7FdXp7Hgvwk84"
            >
              firmatario
            </a>
          </span>
          <span className="c9">
            &nbsp;del Codice di principi IFCN si attiene agli{" "}
          </span>
          <span className="c5">
            <a
              className="c3"
              href="https://www.google.com/url?q=https://www.ifcncodeofprinciples.poynter.org/know-more/the-commitments-of-the-code-of-principles&amp;sa=D&amp;source=editors&amp;ust=1648822303050856&amp;usg=AOvVaw1_4vPH_rEHnAVT5rCsqLyD"
            >
              impegni di
            </a>
          </span>
          <span className="c2">:</span>
        </p>
        <p className="c1">
          <span className="c2"></span>
        </p>
        <ul className="c10 lst-kix_swpaqy9nkgqt-0 start">
          <li className="c0 li-bullet-0">
            <span className="c2">non parzialit&agrave; e correttezza;</span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c2">standard e trasparenza delle fonti;</span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c2">
              trasparenza dei finanziamenti e dell&#39;organizzazione;
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c2">
              standard e trasparenza della metodologia;
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c2">politica di correzione aperta e onesta.</span>
          </li>
        </ul>
        <p className="c1">
          <span className="c2"></span>
        </p>
        <p className="c6">
          <span className="c9">
            &Egrave; possibile trovare ulteriori informazioni sulle nostre
            politiche e principi sul nostro{" "}
          </span>
          <span className="c5">
            <a
              className="c3"
              href="https://www.google.com/url?q=https://voxcheck.voxukraine.org/&amp;sa=D&amp;source=editors&amp;ust=1648822303051563&amp;usg=AOvVaw0zN7cKyt9L-BuYuD82S3_w"
            >
              sito Web ufficiale
            </a>
          </span>
          <span className="c2">.</span>
        </p>
      </div>
    </div>
  );
}
