import Head from "next/head";
import styles from "../../styles/Home.module.css";
import Table from "../../components/Table/Table";
import { tableRu } from "../../data/tableRu";

export default function MethodRu() {
  return (
    <div>
      <Head>
        <title>Propaganda Diary | How</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container + " " + styles.aboutPageWrap}>
        <p className="c10">
          <span className="c1">
            Проект “Propaganda diary” по дезинформации об Украине в немецких и
            итальянских СМИ основан на методологии. Здесь вы можете получить
            информацию о наших методах и политиках.
          </span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c10">
          <span className="c7 c14 c29">Белые и черные списки медиа</span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c10">
          <span className="c1">
            Во-первых, для формирования базы данных по дезинформации необходимо
            было определить ключевые СМИ в соответствующих странах и отличить
            заслуживающие доверия источники от сомнительных. Таким образом, мы
            создали белые и черные списки СМИ в Германии и Италии.
          </span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c10">
          <span className="c1">
            СМИ в белом списке – это качественные СМИ, предоставляющие
            достоверную информацию о внешней и внутренней политике Украины.
            Наоборот, источники из черного списка регулярно распространяют фейки
            об Украине.
          </span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c10">
          <span className="c1">
            Для дифференциации источников и создания этих списков мы
            использовали следующие критерии:
          </span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c7 c14">Содержание</span>
          <span className="c1">
            . Все СМИ, как в белом, так и в черном списке, регулярно сообщают
            новости и публикуют аналитические статьи о политике, международных
            отношениях, Украине в частности.
          </span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c7 c14">Профессиональные стандарты</span>
          <span className="c1">
            . Качественные СМИ из белого списка должны соответствовать
            журналистским стандартам: полнота и беспристрастность освещения
            новостей; объективность и эмоциональная нейтральность; баланс
            мнений; доступность и надежность источников информации; разделение
            фактов и комментариев. СМИ из черного списка постоянно пренебрегают
            этими стандартами, рассказывая об Украине.
          </span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c7 c14">Собственность и прозрачность</span>
          <span className="c1">
            . СМИ должны публично сообщать о своем владельце, финансировании и
            возможном конфликте интересов. Например, некоторые итальянские и
            немецкие СМИ напрямую связаны с российскими государственными
            информационными агентствами. Таким образом, такие СМИ, скорее всего,
            будут распространять дезинформацию об Украине.
          </span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c7 c14">
            Результаты мониторинга СМИ от Media Bias/Fact Check{" "}
          </span>
          <span className="c7">
            . Мы выбрали некоторые СМИ в соответствии с ресурсом
          </span>
          <span className="c7">
            <a
              className="c12"
              href="https://www.google.com/url?q=https://mediabiasfactcheck.com/&amp;sa=D&amp;source=editors&amp;ust=1652628948924164&amp;usg=AOvVaw0Gnr8VI8xbRBKReDuQr8EQ"
            >
              &nbsp;
            </a>
          </span>
          <span className="c22">
            <a
              className="c12"
              href="https://www.google.com/url?q=https://mediabiasfactcheck.com/&amp;sa=D&amp;source=editors&amp;ust=1652628948924421&amp;usg=AOvVaw05Y5UxV5z64Vc_Nfm-ZUJT"
            >
              Media Bias/Fact Check
            </a>
          </span>
          <span className="c22">&nbsp;</span>
          <span className="c1">
            , независимым веб-сайтом, который оценивает предвзятость,
            фактическую точность и достоверность источников. По данным этого
            ресурса, выбранные СМИ в черном списке имеют очень низкий или
            смешанный уровень фактического освещения. СМИ в белом списке
            оцениваются как наименее предвзятые источники и имеют высокий
            уровень фактического освещения.
          </span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c7 c14">
            Результаты мониторинга СМИ от EUvsDisinfo
          </span>
          <span className="c7">
            . Кроме того, мы использовали базы данных EUvsDisinfo по
          </span>
          <span className="c7">
            <a
              className="c12"
              href="https://www.google.com/url?q=https://euvsdisinfo.eu/disinformation-cases/?text%3D%26date%3D%26disinfo_language%255B%255D%3DGerman%26disinfo_countries%255B%255D%3D77554%26per_page%3D&amp;sa=D&amp;source=editors&amp;ust=1652628948924919&amp;usg=AOvVaw2DuQH_ebdU0YTSBPuc5kzh"
            >
              &nbsp;
            </a>
          </span>
          <span className="c22">
            <a
              className="c12"
              href="https://www.google.com/url?q=https://euvsdisinfo.eu/disinformation-cases/?text%3D%26date%3D%26disinfo_language%255B%255D%3DGerman%26disinfo_countries%255B%255D%3D77554%26per_page%3D&amp;sa=D&amp;source=editors&amp;ust=1652628948925156&amp;usg=AOvVaw2e2T5jMBwMsS54YLZzKJCI"
            >
              Германии
            </a>
          </span>
          <span className="c7">&nbsp;</span>
          <span className="c7">и</span>
          <span className="c7">
            <a
              className="c12"
              href="https://www.google.com/url?q=https://euvsdisinfo.eu/disinformation-cases/?text%3D%26date%3D%26disinfo_language%255B%255D%3DItalian%26disinfo_countries%255B%255D%3D77582%26per_page%3D&amp;sa=D&amp;source=editors&amp;ust=1652628948925434&amp;usg=AOvVaw2JDalsspnkYeWjgL481uR6"
            >
              &nbsp;
            </a>
          </span>
          <span className="c22">
            <a
              className="c12"
              href="https://www.google.com/url?q=https://euvsdisinfo.eu/disinformation-cases/?text%3D%26date%3D%26disinfo_language%255B%255D%3DItalian%26disinfo_countries%255B%255D%3D77582%26per_page%3D&amp;sa=D&amp;source=editors&amp;ust=1652628948925665&amp;usg=AOvVaw0rxYkl5h5zfR8XFQOd_5ex"
            >
              Италии
            </a>
          </span>
          <span className="c7">&nbsp;</span>
          <span className="c7">
            , а также случаи распространения фейков, зафиксированные немецкими и
            итальянскими фактчекерами, подписавшими Кодекс принципов IFCN.
          </span>
          <span className="c7">
            <a
              className="c12"
              href="https://www.google.com/url?q=https://euvsdisinfo.eu/about/&amp;sa=D&amp;source=editors&amp;ust=1652628948925883&amp;usg=AOvVaw2R5X297C_WWlqWJ0GNNXVI"
            >
              &nbsp;
            </a>
          </span>
          <span className="c22">
            <a
              className="c12"
              href="https://www.google.com/url?q=https://euvsdisinfo.eu/about/&amp;sa=D&amp;source=editors&amp;ust=1652628948926039&amp;usg=AOvVaw1GCfNII_2xpTr86E5SMNg6"
            >
              EUvsDisinfo
            </a>
          </span>
          <span className="c7">&nbsp;</span>
          <span className="c1">
            — это проект рабочей группы East StratCom Task Force Европейской
            службы внешних действий (European External Action Service’s East
            StratCom Task Force). Он был создан специально для мониторинга и
            противодействия российским дезинформационным кампаниям в Европе.
          </span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c7 c14">
            Результаты собственного мониторинга СМИ.{" "}
          </span>
          <span className="c1">
            При выборе СМИ для мониторинга мы ориентировались на качество
            освещения Украины. Источники, ранее публиковавшие российскую
            дезинформацию, были добавлены в черный список.
          </span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c7 c14">
            Консультации с немецкими и итальянскими фактчекерами и журналистами.{" "}
          </span>
          <span className="c1">
            Мы также обратились за советом к коллегам, работающим в Германии и
            Италии. Представители различных организаций посоветовали нам
            обратить внимание на некоторые СМИ, которые ранее распространяли
            фейковые новости.
          </span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c10">
          <span className="c29 c7 c14">Дезинформационные нарративы</span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c10">
          <span className="c1">
            База данных состоит из сотен манипулятивных новостных сообщений из
            немецких и итальянских СМИ. Чтобы классифицировать этот набор
            данных, мы разделили новостные сообщения на опасные и
            дестабилизирующие нарративы российской дезинформационной кампании.
          </span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c10">
          <span className="c1">
            Различные новостные сообщения являются примерами единого
            дезинформационного нарратива, когда они передают одно и то же
            сообщение, открытое или скрытое, с целью повлиять на общественное
            мнение в соответствующих странах путем искажения картины реальности.
            Все нарративы в базе данных являются типичными посланиями российской
            дезинформационной кампании против Украины. Например, «Украина
            продолжает наращивание военной мощи на Донбассе» и «Украина нарушает
            режим прекращения огня» могут быть яркими примерами нарратива
            «Украина не выполняет обязательства по Минским соглашениям», так как
            имеют одинаковый смысл и цель с точки зрения дезинформации.
          </span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c10">
          <span className="c1">
            Существуют также подтипы дезинформационных нарративов. Эти подтипы
            определяют общее повествование. Например, «США организовали
            государственный переворот в Украине в 2014 году» является подтипом
            нарратива «Майдан 2014 года был государственным переворотом».
          </span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c10">
          <span className="c1">
            Однако зачастую невозможно установить точные мотивы авторов,
            участвовавших в распространении фейковых новостей. Поэтому мы не
            можем утверждать, что все эти авторы и СМИ намеренно распространяют
            дезинформацию об Украине. В то же время нарративы в этих СМИ
            аналогичны или почти идентичны нарративам, распространяемым
            официальными лицами Российской Федерации.
          </span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c10">
          <span className="c29 c7 c14">Типы дезинформации</span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c10">
          <span className="c1">
            Дезинформация – это ложная или вводящая в заблуждение информация,
            распространяемая с целью повлиять на общественное мнение и/или
            скрыть правду. Он часто преднамеренно используется как инструмент
            информационной войны. В случае украинско-российской войны
            дезинформация используется для искажения фактов о внешней и
            внутренней политике Украины и создания негативного образа Украины в
            СМИ и международной политике.
          </span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c10">
          <span className="c1">
            При оценке немецких и итальянских СМИ из черного списка мы выносим
            следующие вердикты по каждому дезинформационному материалу:
          </span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c7 c14">Фейк</span>
          <span className="c1">
            : информация полностью ложная и основана на сомнительных источниках.
          </span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c7 c14">Манипуляция</span>
          <span className="c1">
            : информация частично правдива, но представлена в искаженном
            контексте или не полностью. Автор манипуляции пытается донести
            ложный посыл.
          </span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c7 c14">Теория заговора: </span>
          <span className="c1">
            информация ложная, но она основана на совершенно не поддающихся
            проверке утверждениях, то есть на некоторых теориях, объясняющих
            события результатом тайного заговора.
          </span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c10">
          <span className="c1">
            Эти виды дезинформации являются обычными методами российских
            кампаний против Украины. Наиболее распространенными темами среди его
            дезинформационных нарративов являются:
          </span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c1">
            Евромайдан/Революция Достоинства в Украине;
          </span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c1">аннексия Крыма;</span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c1">
            продолжающаяся украинско-российская война на Донбассе;
          </span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c1">
            исторические события, особенно связанные с историей
            украинско-российских отношений;
          </span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c1">
            отношения Украины с США, НАТО, ЕС и другими партнерами;
          </span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c1">реформы в Украине;</span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c1">экономика Украины;</span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c1">«нацисты и ультранационалисты» в Украине;</span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c1">
            теории заговора о «внешнем управлении» в Украине, то есть о влиянии
            Запада на внешнюю и внутреннюю политику Украины.
          </span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c10">
          <span className="c29 c7 c14">Процесс проверки фактов</span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c10">
          <span className="c1">
            Авторы VoxCheck проводят прозрачную политику при проверке фактов и
            развенчании российской дезинформации об Украине. В наших статьях мы
            достаточно подробно предоставляем все источники для ознакомления,
            чтобы читатели могли воспроизвести нашу работу, за исключением
            случаев, когда личная безопасность источника может быть
            скомпрометирована. В таких случаях мы предоставляем максимально
            подробную информацию. Качество фактчекинга обеспечивает редакция
            проекта.
          </span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c10">
          <span className="c7">VoxCheck, </span>
          <span className="c22">
            <a
              className="c12"
              href="https://www.google.com/url?q=https://ifcncodeofprinciples.poynter.org/signatories&amp;sa=D&amp;source=editors&amp;ust=1652628948929831&amp;usg=AOvVaw2Cj-WDq4NE1K8CeBInl__E"
            >
              подписавший
            </a>
          </span>
          <span className="c7">&nbsp;</span>
          <span className="c7">Кодекс принципов IFCN, соблюдает следующие</span>
          <span className="c7">
            <a
              className="c12"
              href="https://www.google.com/url?q=https://www.ifcncodeofprinciples.poynter.org/know-more/the-commitments-of-the-code-of-principles&amp;sa=D&amp;source=editors&amp;ust=1652628948930227&amp;usg=AOvVaw0awqG7cb3dPS3KkTJFP3kP"
            >
              &nbsp;
            </a>
          </span>
          <span className="c22">
            <a
              className="c12"
              href="https://www.google.com/url?q=https://www.ifcncodeofprinciples.poynter.org/know-more/the-commitments-of-the-code-of-principles&amp;sa=D&amp;source=editors&amp;ust=1652628948930476&amp;usg=AOvVaw1EiIARKiS_NB9xqlfXX6jX"
            >
              обязательства
            </a>
          </span>
          <span className="c22">&nbsp;</span>
          <span className="c1">:</span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c1">беспристрастность и справедливость;</span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c1">стандарты и прозрачность источников;</span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c1">прозрачность финансирования и организации;</span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c1">стандарты и прозрачность методологии;</span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c1">политика открытых и честных исправлений.</span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c10">
          <span className="c7">
            Вы можете найти дополнительную информацию о нашей политике и
            принципах на нашем
          </span>
          <span className="c7">
            <a
              className="c12"
              href="https://www.google.com/url?q=https://voxcheck.voxukraine.org/&amp;sa=D&amp;source=editors&amp;ust=1652628948931481&amp;usg=AOvVaw3WSb_HHdG60uvg61kmU6ag"
            >
              &nbsp;
            </a>
          </span>
          <span className="c22">
            <a
              className="c12"
              href="https://www.google.com/url?q=https://voxcheck.voxukraine.org/&amp;sa=D&amp;source=editors&amp;ust=1652628948931649&amp;usg=AOvVaw1x56JgCNIvYU3pyndPeOlB"
            >
              официальном сайте
            </a>
          </span>
          <span className="c22">&nbsp;</span>
          <span className="c1">.</span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <h3 className="c25" id="h.c8sh43aivrkm">
          <span className="c14 c50">
            Первоисточники проверенной информации об Украине
          </span>
        </h3>
        <p className="c10">
          <span className="c14 c47">&nbsp;</span>
        </p>
        <p className="c10">
          <span className="c4">&nbsp;</span>
        </p>
        <a id="t.4e05bc2f70a9342250671efb904619ea14af1026"></a>
        <a id="t.0"></a>
        <Table data={tableRu} />
        <p className="c10">
          <span className="c4">&nbsp;</span>
        </p>
        <p className="c10 c15">
          <span className="c4">&nbsp;</span>
        </p>
        <p className="c0 c31">
          <span className="c1"></span>
        </p>
      </div>
    </div>
  );
}
