import Head from "next/head";
import styles from "../../styles/Home.module.css";

export default function MethodRu() {
  return (
    <div>
      <Head>
        <title>Propaganda Diary | How</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container + " " + styles.aboutPageWrap}>
        <p className="c10">
          <span className="c1">
            Проект “Propaganda diary” по дезинформации об Украине в немецких и
            итальянских СМИ основан на методологии. Здесь вы можете получить
            информацию о наших методах и политиках.
          </span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c10">
          <span className="c7 c14 c29">Белые и черные списки медиа</span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c10">
          <span className="c1">
            Во-первых, для формирования базы данных по дезинформации необходимо
            было определить ключевые СМИ в соответствующих странах и отличить
            заслуживающие доверия источники от сомнительных. Таким образом, мы
            создали белые и черные списки СМИ в Германии и Италии.
          </span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c10">
          <span className="c1">
            СМИ в белом списке – это качественные СМИ, предоставляющие
            достоверную информацию о внешней и внутренней политике Украины.
            Наоборот, источники из черного списка регулярно распространяют фейки
            об Украине.
          </span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c10">
          <span className="c1">
            Для дифференциации источников и создания этих списков мы
            использовали следующие критерии:
          </span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c7 c14">Содержание</span>
          <span className="c1">
            . Все СМИ, как в белом, так и в черном списке, регулярно сообщают
            новости и публикуют аналитические статьи о политике, международных
            отношениях, Украине в частности.
          </span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c7 c14">Профессиональные стандарты</span>
          <span className="c1">
            . Качественные СМИ из белого списка должны соответствовать
            журналистским стандартам: полнота и беспристрастность освещения
            новостей; объективность и эмоциональная нейтральность; баланс
            мнений; доступность и надежность источников информации; разделение
            фактов и комментариев. СМИ из черного списка постоянно пренебрегают
            этими стандартами, рассказывая об Украине.
          </span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c7 c14">Собственность и прозрачность</span>
          <span className="c1">
            . СМИ должны публично сообщать о своем владельце, финансировании и
            возможном конфликте интересов. Например, некоторые итальянские и
            немецкие СМИ напрямую связаны с российскими государственными
            информационными агентствами. Таким образом, такие СМИ, скорее всего,
            будут распространять дезинформацию об Украине.
          </span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c7 c14">
            Результаты мониторинга СМИ от Media Bias/Fact Check{" "}
          </span>
          <span className="c7">
            . Мы выбрали некоторые СМИ в соответствии с ресурсом
          </span>
          <span className="c7">
            <a
              className="c12"
              href="https://www.google.com/url?q=https://mediabiasfactcheck.com/&amp;sa=D&amp;source=editors&amp;ust=1652628948924164&amp;usg=AOvVaw0Gnr8VI8xbRBKReDuQr8EQ"
            >
              &nbsp;
            </a>
          </span>
          <span className="c22">
            <a
              className="c12"
              href="https://www.google.com/url?q=https://mediabiasfactcheck.com/&amp;sa=D&amp;source=editors&amp;ust=1652628948924421&amp;usg=AOvVaw05Y5UxV5z64Vc_Nfm-ZUJT"
            >
              Media Bias/Fact Check
            </a>
          </span>
          <span className="c22">&nbsp;</span>
          <span className="c1">
            , независимым веб-сайтом, который оценивает предвзятость,
            фактическую точность и достоверность источников. По данным этого
            ресурса, выбранные СМИ в черном списке имеют очень низкий или
            смешанный уровень фактического освещения. СМИ в белом списке
            оцениваются как наименее предвзятые источники и имеют высокий
            уровень фактического освещения.
          </span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c7 c14">
            Результаты мониторинга СМИ от EUvsDisinfo
          </span>
          <span className="c7">
            . Кроме того, мы использовали базы данных EUvsDisinfo по
          </span>
          <span className="c7">
            <a
              className="c12"
              href="https://www.google.com/url?q=https://euvsdisinfo.eu/disinformation-cases/?text%3D%26date%3D%26disinfo_language%255B%255D%3DGerman%26disinfo_countries%255B%255D%3D77554%26per_page%3D&amp;sa=D&amp;source=editors&amp;ust=1652628948924919&amp;usg=AOvVaw2DuQH_ebdU0YTSBPuc5kzh"
            >
              &nbsp;
            </a>
          </span>
          <span className="c22">
            <a
              className="c12"
              href="https://www.google.com/url?q=https://euvsdisinfo.eu/disinformation-cases/?text%3D%26date%3D%26disinfo_language%255B%255D%3DGerman%26disinfo_countries%255B%255D%3D77554%26per_page%3D&amp;sa=D&amp;source=editors&amp;ust=1652628948925156&amp;usg=AOvVaw2e2T5jMBwMsS54YLZzKJCI"
            >
              Германии
            </a>
          </span>
          <span className="c7">&nbsp;</span>
          <span className="c7">и</span>
          <span className="c7">
            <a
              className="c12"
              href="https://www.google.com/url?q=https://euvsdisinfo.eu/disinformation-cases/?text%3D%26date%3D%26disinfo_language%255B%255D%3DItalian%26disinfo_countries%255B%255D%3D77582%26per_page%3D&amp;sa=D&amp;source=editors&amp;ust=1652628948925434&amp;usg=AOvVaw2JDalsspnkYeWjgL481uR6"
            >
              &nbsp;
            </a>
          </span>
          <span className="c22">
            <a
              className="c12"
              href="https://www.google.com/url?q=https://euvsdisinfo.eu/disinformation-cases/?text%3D%26date%3D%26disinfo_language%255B%255D%3DItalian%26disinfo_countries%255B%255D%3D77582%26per_page%3D&amp;sa=D&amp;source=editors&amp;ust=1652628948925665&amp;usg=AOvVaw0rxYkl5h5zfR8XFQOd_5ex"
            >
              Италии
            </a>
          </span>
          <span className="c7">&nbsp;</span>
          <span className="c7">
            , а также случаи распространения фейков, зафиксированные немецкими и
            итальянскими фактчекерами, подписавшими Кодекс принципов IFCN.
          </span>
          <span className="c7">
            <a
              className="c12"
              href="https://www.google.com/url?q=https://euvsdisinfo.eu/about/&amp;sa=D&amp;source=editors&amp;ust=1652628948925883&amp;usg=AOvVaw2R5X297C_WWlqWJ0GNNXVI"
            >
              &nbsp;
            </a>
          </span>
          <span className="c22">
            <a
              className="c12"
              href="https://www.google.com/url?q=https://euvsdisinfo.eu/about/&amp;sa=D&amp;source=editors&amp;ust=1652628948926039&amp;usg=AOvVaw1GCfNII_2xpTr86E5SMNg6"
            >
              EUvsDisinfo
            </a>
          </span>
          <span className="c7">&nbsp;</span>
          <span className="c1">
            — это проект рабочей группы East StratCom Task Force Европейской
            службы внешних действий (European External Action Service’s East
            StratCom Task Force). Он был создан специально для мониторинга и
            противодействия российским дезинформационным кампаниям в Европе.
          </span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c7 c14">
            Результаты собственного мониторинга СМИ.{" "}
          </span>
          <span className="c1">
            При выборе СМИ для мониторинга мы ориентировались на качество
            освещения Украины. Источники, ранее публиковавшие российскую
            дезинформацию, были добавлены в черный список.
          </span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c7 c14">
            Консультации с немецкими и итальянскими фактчекерами и журналистами.{" "}
          </span>
          <span className="c1">
            Мы также обратились за советом к коллегам, работающим в Германии и
            Италии. Представители различных организаций посоветовали нам
            обратить внимание на некоторые СМИ, которые ранее распространяли
            фейковые новости.
          </span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c10">
          <span className="c29 c7 c14">Дезинформационные нарративы</span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c10">
          <span className="c1">
            База данных состоит из сотен манипулятивных новостных сообщений из
            немецких и итальянских СМИ. Чтобы классифицировать этот набор
            данных, мы разделили новостные сообщения на опасные и
            дестабилизирующие нарративы российской дезинформационной кампании.
          </span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c10">
          <span className="c1">
            Различные новостные сообщения являются примерами единого
            дезинформационного нарратива, когда они передают одно и то же
            сообщение, открытое или скрытое, с целью повлиять на общественное
            мнение в соответствующих странах путем искажения картины реальности.
            Все нарративы в базе данных являются типичными посланиями российской
            дезинформационной кампании против Украины. Например, «Украина
            продолжает наращивание военной мощи на Донбассе» и «Украина нарушает
            режим прекращения огня» могут быть яркими примерами нарратива
            «Украина не выполняет обязательства по Минским соглашениям», так как
            имеют одинаковый смысл и цель с точки зрения дезинформации.
          </span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c10">
          <span className="c1">
            Существуют также подтипы дезинформационных нарративов. Эти подтипы
            определяют общее повествование. Например, «США организовали
            государственный переворот в Украине в 2014 году» является подтипом
            нарратива «Майдан 2014 года был государственным переворотом».
          </span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c10">
          <span className="c1">
            Однако зачастую невозможно установить точные мотивы авторов,
            участвовавших в распространении фейковых новостей. Поэтому мы не
            можем утверждать, что все эти авторы и СМИ намеренно распространяют
            дезинформацию об Украине. В то же время нарративы в этих СМИ
            аналогичны или почти идентичны нарративам, распространяемым
            официальными лицами Российской Федерации.
          </span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c10">
          <span className="c29 c7 c14">Типы дезинформации</span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c10">
          <span className="c1">
            Дезинформация – это ложная или вводящая в заблуждение информация,
            распространяемая с целью повлиять на общественное мнение и/или
            скрыть правду. Он часто преднамеренно используется как инструмент
            информационной войны. В случае украинско-российской войны
            дезинформация используется для искажения фактов о внешней и
            внутренней политике Украины и создания негативного образа Украины в
            СМИ и международной политике.
          </span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c10">
          <span className="c1">
            При оценке немецких и итальянских СМИ из черного списка мы выносим
            следующие вердикты по каждому дезинформационному материалу:
          </span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c7 c14">Фейк</span>
          <span className="c1">
            : информация полностью ложная и основана на сомнительных источниках.
          </span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c7 c14">Манипуляция</span>
          <span className="c1">
            : информация частично правдива, но представлена в искаженном
            контексте или не полностью. Автор манипуляции пытается донести
            ложный посыл.
          </span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c7 c14">Теория заговора: </span>
          <span className="c1">
            информация ложная, но она основана на совершенно не поддающихся
            проверке утверждениях, то есть на некоторых теориях, объясняющих
            события результатом тайного заговора.
          </span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c10">
          <span className="c1">
            Эти виды дезинформации являются обычными методами российских
            кампаний против Украины. Наиболее распространенными темами среди его
            дезинформационных нарративов являются:
          </span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c1">
            Евромайдан/Революция Достоинства в Украине;
          </span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c1">аннексия Крыма;</span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c1">
            продолжающаяся украинско-российская война на Донбассе;
          </span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c1">
            исторические события, особенно связанные с историей
            украинско-российских отношений;
          </span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c1">
            отношения Украины с США, НАТО, ЕС и другими партнерами;
          </span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c1">реформы в Украине;</span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c1">экономика Украины;</span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c1">«нацисты и ультранационалисты» в Украине;</span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c1">
            теории заговора о «внешнем управлении» в Украине, то есть о влиянии
            Запада на внешнюю и внутреннюю политику Украины.
          </span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c10">
          <span className="c29 c7 c14">Процесс проверки фактов</span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c10">
          <span className="c1">
            Авторы VoxCheck проводят прозрачную политику при проверке фактов и
            развенчании российской дезинформации об Украине. В наших статьях мы
            достаточно подробно предоставляем все источники для ознакомления,
            чтобы читатели могли воспроизвести нашу работу, за исключением
            случаев, когда личная безопасность источника может быть
            скомпрометирована. В таких случаях мы предоставляем максимально
            подробную информацию. Качество фактчекинга обеспечивает редакция
            проекта.
          </span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c10">
          <span className="c7">VoxCheck, </span>
          <span className="c22">
            <a
              className="c12"
              href="https://www.google.com/url?q=https://ifcncodeofprinciples.poynter.org/signatories&amp;sa=D&amp;source=editors&amp;ust=1652628948929831&amp;usg=AOvVaw2Cj-WDq4NE1K8CeBInl__E"
            >
              подписавший
            </a>
          </span>
          <span className="c7">&nbsp;</span>
          <span className="c7">Кодекс принципов IFCN, соблюдает следующие</span>
          <span className="c7">
            <a
              className="c12"
              href="https://www.google.com/url?q=https://www.ifcncodeofprinciples.poynter.org/know-more/the-commitments-of-the-code-of-principles&amp;sa=D&amp;source=editors&amp;ust=1652628948930227&amp;usg=AOvVaw0awqG7cb3dPS3KkTJFP3kP"
            >
              &nbsp;
            </a>
          </span>
          <span className="c22">
            <a
              className="c12"
              href="https://www.google.com/url?q=https://www.ifcncodeofprinciples.poynter.org/know-more/the-commitments-of-the-code-of-principles&amp;sa=D&amp;source=editors&amp;ust=1652628948930476&amp;usg=AOvVaw1EiIARKiS_NB9xqlfXX6jX"
            >
              обязательства
            </a>
          </span>
          <span className="c22">&nbsp;</span>
          <span className="c1">:</span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c1">беспристрастность и справедливость;</span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c1">стандарты и прозрачность источников;</span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c1">прозрачность финансирования и организации;</span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c1">стандарты и прозрачность методологии;</span>
        </p>
        <p className="c6">
          <span className="c7">●</span>
          <span className="c5">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c1">политика открытых и честных исправлений.</span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c10">
          <span className="c7">
            Вы можете найти дополнительную информацию о нашей политике и
            принципах на нашем
          </span>
          <span className="c7">
            <a
              className="c12"
              href="https://www.google.com/url?q=https://voxcheck.voxukraine.org/&amp;sa=D&amp;source=editors&amp;ust=1652628948931481&amp;usg=AOvVaw3WSb_HHdG60uvg61kmU6ag"
            >
              &nbsp;
            </a>
          </span>
          <span className="c22">
            <a
              className="c12"
              href="https://www.google.com/url?q=https://voxcheck.voxukraine.org/&amp;sa=D&amp;source=editors&amp;ust=1652628948931649&amp;usg=AOvVaw1x56JgCNIvYU3pyndPeOlB"
            >
              официальном сайте
            </a>
          </span>
          <span className="c22">&nbsp;</span>
          <span className="c1">.</span>
        </p>
        <p className="c10">
          <span className="c1">&nbsp;</span>
        </p>
        <h3 className="c25" id="h.c8sh43aivrkm">
          <span className="c14 c50">
            Первоисточники проверенной информации об Украине
          </span>
        </h3>
        <p className="c10">
          <span className="c14 c47">&nbsp;</span>
        </p>
        <p className="c10">
          <span className="c4">&nbsp;</span>
        </p>
        <a id="t.4e05bc2f70a9342250671efb904619ea14af1026"></a>
        <a id="t.0"></a>
        <table className="c43">
          <tbody>
            <tr className="c48">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c46 c14">№</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c46 c14">Источник</span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c46 c14">Описание</span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c14 c46">Ссылка на английский сайт</span>
                </p>
              </td>
            </tr>
            <tr className="c44">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">1</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Государственная служба статистики Украины
                  </span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Государственная служба статистики Украины (Госстат) –
                    специально уполномоченный центральный орган исполнительной
                    власти в сфере статистики, деятельность которого
                    направляется и координируется Кабинетом Министров Украины и
                    который обеспечивает формирование и реализацию
                    государственной политики в сфере статистики. .
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=http://www.ukrstat.gov.ua/&amp;sa=D&amp;source=editors&amp;ust=1652628948934876&amp;usg=AOvVaw0rD2AKM_y6pYFwSBGIi0cu"
                    >
                      http://www.ukrstat.gov.ua/
                    </a>
                  </span>
                </p>
              </td>
            </tr>
            <tr className="c30">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">2</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">Офис Президента Украины</span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    В обязанности Аппарата входит оказание
                    административно-правовой, консультативно-совещательной,
                    медийной, аналитической и иной помощи Президенту при
                    осуществлении им полномочий.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=https://www.president.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652628948936149&amp;usg=AOvVaw0Gk9cUQf67AU1TwjcPtvbV"
                    >
                      https://www.president.gov.ua/en
                    </a>
                  </span>
                </p>
              </td>
            </tr>
            <tr className="c33">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">3</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">Служба безопасности Украины</span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Служба безопасности Украины является главным органом
                    безопасности Украины. Его основными приоритетами являются
                    контрразведка, защита национальной государственности,
                    противодействие терроризму, защита информационной
                    безопасности, защита государственной тайны.
                  </span>
                </p>
                <p className="c0">
                  <span className="c4">&nbsp;</span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=https://ssu.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652628948937504&amp;usg=AOvVaw05JRQI7Mdp1JJHYEDbWpCV"
                    >
                      https://ssu.gov.ua/en
                    </a>
                  </span>
                </p>
              </td>
            </tr>
            <tr className="c27">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">4</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Совет национальной безопасности и обороны Украины
                  </span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Совет национальной безопасности и обороны Украины является
                    координирующим органом по вопросам национальной безопасности
                    и обороны при Президенте Украины.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=https://www.rnbo.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652628948938648&amp;usg=AOvVaw1XDnMIBCFa67S7sckqO3x8"
                    >
                      https://www.rnbo.gov.ua/ru/
                    </a>
                  </span>
                </p>
              </td>
            </tr>
            <tr className="c40">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">5</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Центр противодействия дезинформации
                  </span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Центр противодействия дезинформации является рабочим органом
                    Совета национальной безопасности и обороны Украины. Центр
                    обеспечивает мероприятия по противодействию текущим и
                    прогнозируемым угрозам национальной безопасности и
                    национальным интересам Украины в информационной сфере.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">-</span>
                </p>
              </td>
            </tr>
            <tr className="c40">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">6</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">Правительство Украины</span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Правительство Украины или Кабинет Министров Украины является
                    высшим органом государственной исполнительной власти в
                    Украине. В состав органа входят Премьер-министр Украины,
                    вице-премьер-министры и другие министры из различных
                    учреждений. Премьер-министр возглавляет кабинет.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=https://www.kmu.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652628948940688&amp;usg=AOvVaw2FgGC3QGhFhDAp-GWI30JQ"
                    >
                      https://www.kmu.gov.ua/en
                    </a>
                  </span>
                </p>
              </td>
            </tr>
            <tr className="c21">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">7</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c10">
                  <span className="c4">Верховная Рада Украины</span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Верховная Рада — парламент Украины. Это единственный орган
                    законодательной власти в Украине. Парламент состоит из 450
                    депутатов, избираемых украинским народом.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=https://www.rada.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652628948941830&amp;usg=AOvVaw3KcktwSvnJAMpU6s38UtVb"
                    >
                      https://www.rada.gov.ua/en
                    </a>
                  </span>
                </p>
              </td>
            </tr>
            <tr className="c41">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">8</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c10">
                  <span className="c4">
                    Государственная казначейская служба Украины
                  </span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Государственная казначейская служба Украины является
                    центральным органом исполнительной власти Украины,
                    осуществляющим государственную политику в сфере
                    казначейского обслуживания бюджетных средств. Деятельность
                    службы направляется и координируется Кабинетом Министров
                    Украины через Министра финансов Украины.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=https://www.treasury.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652628948943321&amp;usg=AOvVaw1uBUvBb5rTRq1k2-B0Pp0M"
                    >
                      https://www.treasury.gov.ua/en
                    </a>
                  </span>
                </p>
              </td>
            </tr>
            <tr className="c16">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c10">
                  <span className="c4">9</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Государственная налоговая служба Украины
                  </span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Государственная налоговая служба Украины является
                    центральным органом исполнительной власти в сфере налогов в
                    Украине. Деятельность службы направляется и координируется
                    Кабинетом Министров Украины через Министра финансов.
                  </span>
                </p>
                <p className="c0">
                  <span className="c4">
                    Служба реализует государственную налоговую политику и
                    государственную политику в сфере противодействия
                    правонарушениям при применении налогового законодательства
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=https://tax.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652628948944620&amp;usg=AOvVaw26FY0F3362bcCU-oP_ONwt"
                    >
                      https://tax.gov.ua/ru/
                    </a>
                  </span>
                </p>
              </td>
            </tr>
            <tr className="c8">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c10">
                  <span className="c4">10</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">Таможенная служба Украины</span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Государственная таможенная служба Украины является
                    центральным органом исполнительной власти Украины, который
                    реализует национальную таможенную политику и национальную
                    политику в сфере борьбы с правонарушениями при применении
                    законодательства о национальном таможенном деле.
                    Деятельность службы направляется и координируется Кабинетом
                    Министров Украины через Министра финансов.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=https://customs.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652628948945799&amp;usg=AOvVaw2FWo4JA8fV4W4QS254GcNu"
                    >
                      https://customs.gov.ua/ru
                    </a>
                  </span>
                </p>
              </td>
            </tr>
            <tr className="c34">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">11</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Государственная пограничная служба Украины
                  </span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c39">
                    Государственная пограничная служба Украины является
                    правоохранительным органом, на который возложены задачи
                    обеспечения неприкосновенности государственных границ и
                    защиты суверенных прав Украины в пределах ее исключительной
                    (морской) экономической зоны.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=https://dpsu.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652628948947067&amp;usg=AOvVaw0V8b-kIwcGXRSKW1oxo4l1"
                    >
                      https://dpsu.gov.ua/ru/
                    </a>
                  </span>
                </p>
              </td>
            </tr>
            <tr className="c44">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">12</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">Национальный банк Украины</span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Национальный банк Украины является государственным органом,
                    осуществляющим единую государственную политику в сфере
                    денежного обращения страны, в том числе укрепления
                    национальной денежной единицы. Его миссия заключается в
                    обеспечении ценовой и финансовой стабильности с целью
                    содействия устойчивому экономическому развитию Украины.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=https://bank.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652628948948284&amp;usg=AOvVaw24R1A-WCxgI98qJlfY0rei"
                    >
                      https://bank.gov.ua/ru/
                    </a>
                  </span>
                </p>
              </td>
            </tr>
            <tr className="c45">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">13</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Министерство цифровой трансформации Украины
                  </span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Министерство цифровой трансформации Украины является
                    государственным органом. Его основная цель — способствовать
                    цифровизации в Украине, особенно развитию инфраструктуры,
                    созданию благоприятной среды для ИТ-сектора и популяризации
                    цифровой грамотности.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">-</span>
                </p>
              </td>
            </tr>
            <tr className="c38">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">14</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">Министерство финансов Украины</span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Министерство финансов Украины отвечает за формирование и
                    реализацию следующих основных направлений государственной
                    политики: бюджетной политики, налоговой и таможенной
                    политики, долговой политики. международное финансовое
                    сотрудничество. Миссия Министерства состоит в том, чтобы
                    обеспечить финансовую основу для надлежащего выполнения
                    государственных функций, поддерживаемых взвешенной бюджетной
                    политикой, а также создать благоприятные условия для
                    стабильного экономического развития.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=https://mof.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652628948950308&amp;usg=AOvVaw0ViaLEv0au7ai3WagZ1_EY"
                    >
                      https://mof.gov.ua/en
                    </a>
                  </span>
                </p>
              </td>
            </tr>
            <tr className="c8">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">15</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">Министерство обороны Украины</span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Министерство обороны Украины является основным (ведущим)
                    органом в системе центральных органов исполнительной власти
                    по обеспечению реализации государственной политики в сфере
                    обороны. Участвует в реализации государственной политики в
                    области обороны и военного строительства, координации
                    деятельности государственных органов и органов местного
                    самоуправления по подготовке государства к обороне.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=https://www.mil.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652628948951546&amp;usg=AOvVaw0QfsgGhgbTm8n-DI7sQ0MS"
                    >
                      https://www.mil.gov.ua/ru/
                    </a>
                  </span>
                </p>
              </td>
            </tr>
            <tr className="c27">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">16</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">Военная разведка</span>
                </p>
                <p className="c0">
                  <span className="c4">Министерства обороны Украины</span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c17 c26">
                    Служба военной разведки Украины ведет разведку в сфере
                    обороны, развития военного потенциала, военной и
                    военно-технической, а также кибербезопасности.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=https://gur.gov.ua/en.html&amp;sa=D&amp;source=editors&amp;ust=1652628948952835&amp;usg=AOvVaw1jGyWHruY8ovyHqx8ZENg7"
                    >
                      https://gur.gov.ua/en.html
                    </a>
                  </span>
                </p>
              </td>
            </tr>
            <tr className="c44">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">17</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Министерство реинтеграции временно оккупированных территорий
                    Украины
                  </span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Министерство реинтеграции временно оккупированных территорий
                    является государственным ведомством в Украине, которое
                    решает задачи оперативного реагирования на проблемы и
                    угрозы, связанные с проведением антитеррористической
                    операции в отдельных районах Донецкой и Луганской областей,
                    а также с временная оккупация территории Украины.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=https://minre.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652628948954072&amp;usg=AOvVaw19ZWdIZrFzufC6qIFw_WEh"
                    >
                      https://minre.gov.ua/en
                    </a>
                  </span>
                </p>
              </td>
            </tr>
            <tr className="c20">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">18</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">Децентрализация в Украине</span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Реформа децентрализации - официальный сайт реформы.
                    Децентрализация означает делегирование значительных
                    полномочий и бюджетов от государственных органов органам
                    местного самоуправления.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=https://decentralization.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652628948955552&amp;usg=AOvVaw3vcptTuvLMHItQaOpwH8Mp"
                    >
                      https://decentralization.gov.ua/en/
                    </a>
                  </span>
                </p>
              </td>
            </tr>
            <tr className="c18">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">19</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Министерство социальной политики Украины
                  </span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Министерство социальной политики Украины является
                    государственным ведомством Украины, ответственным за
                    установление трудовых отношений, семью и детей, иммиграцию и
                    торговлю людьми, права женщин, права детей и гуманитарную
                    помощь.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=https://www.msp.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652628948956764&amp;usg=AOvVaw2frLwztfZ3IbBv1jfE0i3y"
                    >
                      https://www.msp.gov.ua/ru/
                    </a>
                  </span>
                </p>
              </td>
            </tr>
            <tr className="c28">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">20</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Министерство развития громад и территорий Украины
                  </span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Министерство развития громад и территорий Украины
                    (Минрегион) осуществляет государственное регулирование в
                    сфере архитектуры, строительства и градостроительства.
                    Приоритетными задачами Министерства являются развитие и
                    совершенствование регулирования в области архитектуры,
                    строительства и градостроительства с учетом требований
                    законодательства ЕС в соответствующих областях, упрощение
                    разрешительных процедур и внедрение новых технологий.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=https://www.minregion.gov.ua/en/ministry-for-development-of-communities-and-territories-of-ukraine&amp;sa=D&amp;source=editors&amp;ust=1652628948957997&amp;usg=AOvVaw0ZNDiRs_20lb2PvXAm0izu"
                    >
                      https://www.minregion.gov.ua/en/
                    </a>
                  </span>
                </p>
              </td>
            </tr>
            <tr className="c28">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">21</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Министерство экологии и охраны окружающей среды Украины
                  </span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Министерство экологии и природных ресурсов Украины является
                    центральным органом исполнительной власти, деятельность
                    которого регулируется и координируется Кабинетом Министров
                    Украины. Министерство экологии и природных ресурсов работает
                    в области охраны окружающей среды, экологической
                    безопасности, обращения с отходами, опасными химическими
                    веществами, пестицидами и агрохимикатами и проводит
                    государственную экологическую экспертизу.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=https://mepr.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652628948959240&amp;usg=AOvVaw3eWTEotW9XKkWdXtScHfXS"
                    >
                      https://mepr.gov.ua/ru/
                    </a>
                  </span>
                </p>
              </td>
            </tr>
            <tr className="c32">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">22</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Министерство энергетики и угольной промышленности Украины
                  </span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Министерство энергетики и угля обеспечивает формирование и
                    реализацию государственной политики в электроэнергетическом,
                    атомно-промышленном, углепромышленном, торфодобывающем,
                    нефтегазовом и нефтегазоперерабатывающем комплексах, а также
                    обеспечивает формирование государственная политика в сфере
                    надзора (контроля) в электроэнергетике и теплоэнергетике.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">-</span>
                </p>
              </td>
            </tr>
            <tr className="c32">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">23</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Министерство здравоохранения Украины
                  </span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Министерство здравоохранения Украины является главным
                    органом здравоохранения в системе центрального
                    правительства. Он создан на базе бывших министерств
                    здравоохранения. Организационная структура Министерства
                    здравоохранения Украины состоит из девяти управлений,
                    четырех департаментов, трех отделов, четырех секторов и
                    патронажной службы.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=https://en.moz.gov.ua/&amp;sa=D&amp;source=editors&amp;ust=1652628948961607&amp;usg=AOvVaw2-MrNeeQYs-sGmt99OSI8o"
                    >
                      https://en.moz.gov.ua/
                    </a>
                  </span>
                </p>
              </td>
            </tr>
            <tr className="c28">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">24</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Государственное предприятие «Центр общественного здоровья»
                    МЗ Украины
                  </span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Государственное предприятие «Центр общественного здоровья»
                    Министерства здравоохранения Украины является учреждением
                    здравоохранения, ответственным за сохранение и укрепление
                    здоровья населения, социально-гигиенический мониторинг
                    заболеваний, эпидемиологический надзор и биобезопасность,
                    групповую и популяционную профилактику заболеваний, контроль
                    эпидемий и стратегического управления в области
                    общественного здравоохранения.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=https://phc.org.ua/&amp;sa=D&amp;source=editors&amp;ust=1652628948962774&amp;usg=AOvVaw0znITpwbPhfUXIAzyPBGNy"
                    >
                      https://phc.org.ua/
                    </a>
                  </span>
                </p>
              </td>
            </tr>
            <tr className="c44">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">25</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Национальная служба здравоохранения Украины
                  </span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Национальная служба здравоохранения Украины (НСЗУ) является
                    центральным органом исполнительной власти, реализующим
                    государственную политику в сфере государственных финансовых
                    гарантий медицинского обслуживания населения. Деятельность
                    НСЗУ направляет и координирует Кабинет Министров Украины
                    через Министра здравоохранения.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=https://nszu.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652628948963984&amp;usg=AOvVaw33gzGMlSm7UjUGsuxN7Bg2"
                    >
                      https://nszu.gov.ua/en
                    </a>
                  </span>
                </p>
              </td>
            </tr>
            <tr className="c33">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">26</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">Министерство экономики Украины</span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Министерство экономики является ведущим органом в системе
                    государственных органов и учреждений Украины, отвечающим за
                    реализацию единой государственной политики национального и
                    регионального экономического и социального развития и
                    сотрудничества с Европейским Союзом.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=https://www.me.gov.ua/?lang%3Den-GB&amp;sa=D&amp;source=editors&amp;ust=1652628948965182&amp;usg=AOvVaw27YRek4GgGLuOxdzf-EdxH"
                    >
                      https://www.me.gov.ua/?lang=en-RU
                    </a>
                  </span>
                </p>
              </td>
            </tr>
            <tr className="c40">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">27</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Министерство образования и науки Украины
                  </span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Министерство образования и науки Украины является
                    центральным исполнительным органом государственной власти в
                    системе государственной власти Украины, ответственным за
                    разработку, реализацию и мониторинг общегосударственной
                    политики в сфере образования и науки.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=https://mon.gov.ua/eng&amp;sa=D&amp;source=editors&amp;ust=1652628948966443&amp;usg=AOvVaw1J7qUTYI5qWeN7LOCkRr0y"
                    >
                      https://mon.gov.ua/eng
                    </a>
                  </span>
                  <span className="c4">&nbsp;</span>
                </p>
              </td>
            </tr>
            <tr className="c16">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">28</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">Министерство юстиции Украины</span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Министерство юстиции является центральным органом
                    государственной исполнительной власти и главным органом
                    среди центральных органов исполнительной власти, отвечающим
                    за реализацию государственной правовой политики. В
                    установленном порядке и в пределах своей компетенции
                    Министерство решает вопросы, вытекающие из общепризнанных
                    норм международного права и международных договоров,
                    ратифицированных Верховной Радой Украины.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=https://minjust.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652628948967625&amp;usg=AOvVaw3XgbWhCfMtU_rvnw_AiLxF"
                    >
                      https://minjust.gov.ua/ru/
                    </a>
                  </span>
                </p>
              </td>
            </tr>
            <tr className="c20">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">29</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Министерство культуры и информационной политики Украины
                  </span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Министерство культуры и информационной политики является
                    главным органом государственной власти в системе центральной
                    власти Украины, отвечающим за культурное развитие страны и
                    сохранение истории.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=https://mkip.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652628948968758&amp;usg=AOvVaw3qOlFOXgQ6wxTARft8q0tM"
                    >
                      https://mkip.gov.ua/ru/
                    </a>
                  </span>
                </p>
              </td>
            </tr>
            <tr className="c44">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">30</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">Центр стратегических коммуникаций</span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Центр стратегических коммуникаций создан при Министерстве
                    культуры и информационной политики Украины как один из
                    механизмов противодействия дезинформации совместными
                    усилиями государства и гражданского общества. Центр
                    ориентирован на связь, направленную на противодействие
                    внешним угрозам, в частности информационным атакам
                    Российской Федерации.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=https://spravdi.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652628948970028&amp;usg=AOvVaw3sMEOyQdh8F17hBWNu8naP"
                    >
                      https://spravdi.gov.ua/ru/
                    </a>
                  </span>
                </p>
              </td>
            </tr>
            <tr className="c37">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">31</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Министерство аграрной политики и продовольствия Украины
                  </span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span>
                    Министерство аграрной политики и продовольствия Украины
                    формирует и реализует государственную аграрную политику,
                    государственную политику в сферах сельского хозяйства и
                    продовольственной безопасности государства, защиты прав на
                    сорта растений, животноводства, растениеводства, развития
                    села и других направлений агропромышленного комплекса.
                    -промышленный комплекс{" "}
                  </span>
                  <span className="c24">.</span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=https://minagro.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652628948971239&amp;usg=AOvVaw1w3NOGrG8EtGT1YmXutOJF"
                    >
                      https://minagro.gov.ua/ru
                    </a>
                  </span>
                </p>
              </td>
            </tr>
            <tr className="c36">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">32</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Министерство внутренних дел Украины
                  </span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c35">
                    Министерство осуществляет государственную политику в области
                    защиты прав и свобод граждан, расследует противоправные
                    действия, противоречащие интересам общества и государства,
                    борется с преступностью, обеспечивает гражданский порядок,
                    обеспечивает гражданскую безопасность и безопасность
                    дорожного движения, гарантирует безопасность и защиту важных
                    лиц. .
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=https://mvs.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652628948972457&amp;usg=AOvVaw2AsvvodqIpY6BFIQhIjPbZ"
                    >
                      https://mvs.gov.ua/ru
                    </a>
                  </span>
                </p>
              </td>
            </tr>
            <tr className="c19">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">33</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Министерство инфраструктуры Украины
                  </span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c42">
                    Министерство инфраструктуры является центральным органом
                    исполнительной власти в области транспорта, дорог, почтовой
                    связи и инфраструктуры.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=https://mtu.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652628948973891&amp;usg=AOvVaw2Wi9NDmYct-1K7tuHqjWJ0"
                    >
                      https://mtu.gov.ua/ru/
                    </a>
                  </span>
                </p>
              </td>
            </tr>
            <tr className="c30">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">34</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Министерство иностранных дел Украины
                  </span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Министерство иностранных дел Украины является головным
                    органом в системе центральных органов исполнительной власти
                    по формированию и реализации государственной политики в
                    сфере внешних сношений Украины.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=https://mfa.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652628948975097&amp;usg=AOvVaw2sgXkhwZ59EfKaJ2ykgdKd"
                    >
                      https://mfa.gov.ua/en
                    </a>
                  </span>
                </p>
              </td>
            </tr>
            <tr className="c32">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">35</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Национальное антикоррупционное бюро
                  </span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Национальное антикоррупционное бюро Украины является
                    центральным органом исполнительной власти со специальным
                    статусом, осуществляющим деятельность по предупреждению,
                    выявлению, пресечению, расследованию и раскрытию
                    коррупционных и других уголовных правонарушений в пределах
                    своей компетенции, а также предупреждению совершения новых.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=https://nabu.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652628948976531&amp;usg=AOvVaw33MoYvpMK85LoQNRdlBPPi"
                    >
                      https://nabu.gov.ua/en
                    </a>
                  </span>
                </p>
              </td>
            </tr>
            <tr className="c30">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">36</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Национальное агентство по предупреждению коррупции
                  </span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Национальное агентство по предупреждению коррупции является
                    центральным органом исполнительной власти со специальным
                    статусом. Он отвечает за разработку антикоррупционной
                    политики и предотвращение коррупции.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=https://nazk.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652628948977811&amp;usg=AOvVaw0rSMEzK2tLl_gmjtEv0FX5"
                    >
                      https://nazk.gov.ua/ru/
                    </a>
                  </span>
                </p>
              </td>
            </tr>
            <tr className="c44">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">37</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Специализированная антикоррупционная прокуратура
                  </span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Специализированная антикоррупционная прокуратура является
                    самостоятельным структурным подразделением Генеральной
                    прокуратуры Украины и несет основную ответственность за
                    сопровождение и надзор за уголовными расследованиями,
                    возбужденными Национальным антикоррупционным бюро Украины.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">-</span>
                </p>
              </td>
            </tr>
            <tr className="c30">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">38</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">Укрзализныця</span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Укрзализныця осуществляет централизованное управление
                    перевозочным процессом во внутреннем и межгосударственном
                    сообщении, регулирует производственно-хозяйственную
                    деятельность железных дорог.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=https://www.uz.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652628948979887&amp;usg=AOvVaw2NpayKrNeKGx5fK9c5KZ__"
                    >
                      https://www.uz.gov.ua/ru/
                    </a>
                  </span>
                </p>
              </td>
            </tr>
            <tr className="c16">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">39</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">Пенсионный фонд Украины</span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Пенсионный фонд Украины является центральным органом
                    исполнительной власти, который управляет солидарной системой
                    обязательного государственного пенсионного обеспечения,
                    осуществляет сбор, аккумулирование и учет страховых взносов,
                    начисление пенсий и подготовку документов для их выплаты,
                    обеспечивает своевременное и полное финансирование и выплату
                    пенсий, пособий на погребение и другие социальные льготы.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">-</span>
                </p>
              </td>
            </tr>
            <tr className="c40">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">40</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">Нафтогаз</span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Нафтогаз — крупнейшая государственная компания Украины.
                    Осуществляет полный цикл разведки и разработки
                    месторождений, эксплуатационного и разведочного бурения,
                    хранения нефти и газа, переработки и реализации
                    нефтепродуктов, природного газа и сжиженного газа
                    потребителям.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=https://www.naftogaz.com/en/&amp;sa=D&amp;source=editors&amp;ust=1652628948982314&amp;usg=AOvVaw2scnkF32Dj1QuzkYD3BQKT"
                    >
                      https://www.naftogaz.com/ru/
                    </a>
                  </span>
                </p>
              </td>
            </tr>
            <tr className="c49">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">41</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">Укрпочта</span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    ГП «Укрпочта» — единственный национальный оператор почтовой
                    связи в Украине. Это главная почтовая служба страны.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=https://www.ukrposhta.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652628948983567&amp;usg=AOvVaw1VH9U4tsvRod4joydZEbTC"
                    >
                      https://www.ukrposhta.ua/ru
                    </a>
                  </span>
                </p>
              </td>
            </tr>
            <tr className="c21">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">42</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">Генеральная прокуратура</span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Генеральная прокуратура является центральным органом в
                    системе прокуратуры. Организует и координирует деятельность
                    всех органов прокуратуры.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c11">
                    <a
                      className="c12"
                      href="https://www.google.com/url?q=https://www.gp.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652628948984803&amp;usg=AOvVaw04XrFJAned0FWxq8wcCu0q"
                    >
                      https://www.gp.gov.ua/en
                    </a>
                  </span>
                </p>
              </td>
            </tr>
            <tr className="c27">
              <td className="c9" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">43</span>
                </p>
              </td>
              <td className="c2" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">Национальная гвардия Украины</span>
                </p>
              </td>
              <td className="c3" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">
                    Национальная гвардия Украины. является украинской
                    национальной жандармерией и внутренними войсками. Входит в
                    состав МВД, отвечает за общественную безопасность.
                  </span>
                </p>
              </td>
              <td className="c13" colSpan="1" rowSpan="1">
                <p className="c0">
                  <span className="c4">-</span>
                </p>
              </td>
            </tr>
          </tbody>
        </table>
        <p className="c10">
          <span className="c4">&nbsp;</span>
        </p>
        <p className="c10 c15">
          <span className="c4">&nbsp;</span>
        </p>
        <p className="c0 c31">
          <span className="c1"></span>
        </p>
      </div>
    </div>
  );
}
