import Head from "next/head";
import styles from "../../styles/Home.module.css";
import Table from "../../components/Table/Table";

import { tableUkr } from "../../data/tableUkr";

export default function MethodUkr() {
  return (
    <div>
      <Head>
        <title>Propaganda Diary | How</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container + " " + styles.aboutPageWrap}>
        <p className="c5">
          <span className="c6">
            Проект “Propaganda diary” щодо дезінформації про Україну в німецьких
            та італійських ЗМІ базується на методології. Тут ви можете отримати
            інформацію про наші методи та політику.
          </span>
        </p>
        <p className="c5">
          <span className="c6">&nbsp;</span>
        </p>
        <p className="c5">
          <span className="c20 c14 c25">Білий і чорний списки ЗМІ</span>
        </p>
        <p className="c5">
          <span className="c6">&nbsp;</span>
        </p>
        <p className="c5">
          <span className="c6">
            По-перше, для формування бази даних про дезінформацію необхідно було
            визначити ключові ЗМІ у відповідних країнах та відрізнити достовірні
            джерела від сумнівних. Таким чином ми створили білі та чорні списки
            ЗМІ Німеччини та Італії.
          </span>
        </p>
        <p className="c5">
          <span className="c6">&nbsp;</span>
        </p>
        <p className="c5">
          <span className="c6">
            ЗМІ в білому списку – це якісні ЗМІ, які надають достовірну
            інформацію про зовнішню та внутрішню політику України. Натомість
            джерела з чорного списку регулярно поширюють фейкові новини про
            Україну.
          </span>
        </p>
        <p className="c5">
          <span className="c6">&nbsp;</span>
        </p>
        <p className="c5">
          <span className="c6">
            Щоб розрізнити джерела та створити ці списки, ми використовували
            такі критерії:
          </span>
        </p>
        <p className="c5">
          <span className="c6">&nbsp;</span>
        </p>
        <p className="c5 c11">
          <span className="c14">●</span>
          <span className="c22 c14">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c20 c14">Зміст</span>
          <span className="c6">
            . Усі ЗМІ, як у білому, так і в чорному списках, регулярно
            повідомляють новини та публікують аналітичні статті про політику,
            міжнародні відносини, Україну зокрема.
          </span>
        </p>
        <p className="c5 c11">
          <span className="c14">●</span>
          <span className="c22 c14">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c20 c14">Професійні стандарти</span>
          <span className="c6">
            . Якісні ЗМІ в білому списку мають відповідати журналістським
            стандартам: всебічності та неупередженості висвітлення новин;
            об’єктивності та емоційної нейтральності; балансу думок; наявоісті
            та надійності джерел інформації; розділення фактів і думок. ЗМІ з
            чорного списку постійно нехтують цими стандартами, повідомляючи про
            Україну.
          </span>
        </p>
        <p className="c5 c11">
          <span className="c14">●</span>
          <span className="c22 c14">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c20 c14">Власність і прозорість</span>
          <span className="c6">
            . ЗМІ повинні публічно повідомляти про свого власника, фінансування
            та можливий конфлікт інтересів. Наприклад, деякі італійські та
            німецькі ЗМІ безпосередньо пов’язані з російськими державними
            інформаційними агентствами. Таким чином, такі ЗМІ, швидше за все,
            будуть поширювати дезінформацію про Україну.
          </span>
        </p>
        <p className="c5 c11">
          <span className="c14">●</span>
          <span className="c22 c14">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c20 c14">
            Результати моніторингу ЗМІ від Media Bias / Fact Check
          </span>
          <span className="c14">
            . Ми вибрали деякі ЗМІ відповідно до ресурсу
          </span>
          <span className="c14">
            <a
              className="c4"
              href="https://www.google.com/url?q=https://mediabiasfactcheck.com/&amp;sa=D&amp;source=editors&amp;ust=1652628409071381&amp;usg=AOvVaw1NevlMeF1UunSDrKtzR4O9"
            >
              &nbsp;
            </a>
          </span>
          <span className="c9">
            <a
              className="c4"
              href="https://www.google.com/url?q=https://mediabiasfactcheck.com/&amp;sa=D&amp;source=editors&amp;ust=1652628409071728&amp;usg=AOvVaw0qNnI6_eqZag_H1jLKMIup"
            >
              Media Bias / Fact Check
            </a>
          </span>
          <span className="c6">
            , незалежного веб-сайту, який оцінює упередженість, точність фактів
            і достовірність джерел. За даними цього ресурсу, вибрані ЗМІ з
            чорного списку мають дуже низький або змішаний рівень фактичної
            інформації. ЗМІ з білого списку оцінюються як найменш упереджені
            джерела та мають високий рівень репортажів щодо фактів.
          </span>
        </p>
        <p className="c5 c11">
          <span className="c14">●</span>
          <span className="c22 c14">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c14 c20">
            Результати моніторингу ЗМІ від EUvsDisinfo{" "}
          </span>
          <span className="c14">
            . Крім того, ми використовували бази даних EUvsDisinfo про
          </span>
          <span className="c14">
            <a
              className="c4"
              href="https://www.google.com/url?q=https://euvsdisinfo.eu/disinformation-cases/?text%3D%26date%3D%26disinfo_language%255B%255D%3DGerman%26disinfo_countries%255B%255D%3D77554%26per_page%3D&amp;sa=D&amp;source=editors&amp;ust=1652628409072175&amp;usg=AOvVaw1LaYybEroh01TYoCgNGT2e"
            >
              &nbsp;
            </a>
          </span>
          <span className="c9">
            <a
              className="c4"
              href="https://www.google.com/url?q=https://euvsdisinfo.eu/disinformation-cases/?text%3D%26date%3D%26disinfo_language%255B%255D%3DGerman%26disinfo_countries%255B%255D%3D77554%26per_page%3D&amp;sa=D&amp;source=editors&amp;ust=1652628409072436&amp;usg=AOvVaw05vdEVECl1We4FvsgaDuBq"
            >
              Німеччину
            </a>
          </span>
          <span className="c14">&nbsp;</span>
          <span className="c14">та</span>
          <span className="c14">
            <a
              className="c4"
              href="https://www.google.com/url?q=https://euvsdisinfo.eu/disinformation-cases/?text%3D%26date%3D%26disinfo_language%255B%255D%3DItalian%26disinfo_countries%255B%255D%3D77582%26per_page%3D&amp;sa=D&amp;source=editors&amp;ust=1652628409072746&amp;usg=AOvVaw3mcUDObX-qCIqsZhpkc7pJ"
            >
              &nbsp;
            </a>
          </span>
          <span className="c9">
            <a
              className="c4"
              href="https://www.google.com/url?q=https://euvsdisinfo.eu/disinformation-cases/?text%3D%26date%3D%26disinfo_language%255B%255D%3DItalian%26disinfo_countries%255B%255D%3D77582%26per_page%3D&amp;sa=D&amp;source=editors&amp;ust=1652628409072973&amp;usg=AOvVaw0Nwi4KLh0VD9FbOp2KI-GE"
            >
              Італію
            </a>
          </span>
          <span className="c14">
            , а також випадки розповсюдження фейків, зафіксовані німецькими та
            італійськими фактчекерами, які підписали Кодекс етики IFCN.
          </span>
          <span className="c14">
            <a
              className="c4"
              href="https://www.google.com/url?q=https://euvsdisinfo.eu/about/&amp;sa=D&amp;source=editors&amp;ust=1652628409073185&amp;usg=AOvVaw1dviSgFoxs_ZgDsIggCclZ"
            >
              &nbsp;
            </a>
          </span>
          <span className="c9">
            <a
              className="c4"
              href="https://www.google.com/url?q=https://euvsdisinfo.eu/about/&amp;sa=D&amp;source=editors&amp;ust=1652628409073332&amp;usg=AOvVaw0p2BNWIvkRWT0j9_h_zkTa"
            >
              EUvsDisinfo
            </a>
          </span>
          <span className="c9">&nbsp;</span>
          <span className="c6">
            – це проект робочої групи East StratCom Європейської служби
            зовнішніх дій (European External Action Service’s East StratCom Task
            Force). Він був створений спеціально для моніторингу та протидії
            російським дезінформаційним кампаніям у Європі.
          </span>
        </p>
        <p className="c5 c11">
          <span className="c14">●</span>
          <span className="c22 c14">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c20 c14">Результати власного моніторингу ЗМІ. </span>
          <span className="c6">
            При виборі ЗМІ для моніторингу ми орієнтувалися на якість репортажу
            про Україну. Джерела, які раніше публікували російську
            дезінформацію, були додані до чорного списку.
          </span>
        </p>
        <p className="c5 c11">
          <span className="c14">●</span>
          <span className="c22 c14">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c20 c14">
            Консультації з німецькими та італійськими фактчекерами та
            журналістами.{" "}
          </span>
          <span className="c6">
            Ми також зверталися за порадою до колег, які працюють у Німеччині та
            Італії. Представники різних організацій порадили звернути увагу на
            деякі ЗМІ, які раніше поширювали фейкові новини.
          </span>
        </p>
        <p className="c5">
          <span className="c6">&nbsp;</span>
        </p>
        <p className="c5">
          <span className="c25 c20 c14">Дезінформаційні наративи</span>
        </p>
        <p className="c5">
          <span className="c6">&nbsp;</span>
        </p>
        <p className="c5">
          <span className="c6">
            База даних складається з сотень маніпулятивних повідомлень німецьких
            та італійських ЗМІ. Щоб класифікувати цей набір даних, ми
            класифікували новини за небезпечними та дестабілізуючими наративами
            російської дезінформаційної кампанії.
          </span>
        </p>
        <p className="c5">
          <span className="c6">&nbsp;</span>
        </p>
        <p className="c5">
          <span className="c6">
            Різні репортажі новин є прикладами одного наративу дезінформації,
            коли вони передають одне й те саме повідомлення, чи то відверто, чи
            приховане, спрямоване на вплив на громадську думку у відповідних
            країнах шляхом спотворення картини реальності. Усі наративи в базі
            даних є типовими повідомленнями для російської дезінформаційної
            кампанії проти України. Наприклад, «Україна продовжує нарощування
            військ на Донбасі» та «Україна порушує режим припинення вогню»
            можуть бути яскравими прикладами наративу «Україна не виконує
            зобов’язань за Мінськими домовленостями», оскільки вони мають
            однакове значення та мету з точки зору дезінформації.
          </span>
        </p>
        <p className="c5">
          <span className="c6">&nbsp;</span>
        </p>
        <p className="c5">
          <span className="c6">
            Існують також підвиди наративів дезінформації. Ці підтипи визначають
            загальний наратив. Наприклад, «США організували державний переворот
            в Україні 2014 року» є підтипом наративу «Майдан 2014 року був
            державним переворотом».
          </span>
        </p>
        <p className="c5">
          <span className="c6">&nbsp;</span>
        </p>
        <p className="c5">
          <span className="c6">
            Проте часто неможливо визначити точні мотиви авторів, які брали
            участь у поширенні фейкових новин. Тому ми не можемо підтвердити, що
            всі ці автори та ЗМІ навмисно поширювали дезінформацію про Україну.
            У той же час наративи в цих ЗМІ подібні або майже ідентичні
            наративам, які поширюють чиновники Російської Федерації.
          </span>
        </p>
        <p className="c5">
          <span className="c6">&nbsp;</span>
        </p>
        <p className="c5">
          <span className="c25 c20 c14">Види дезінформації</span>
        </p>
        <p className="c5">
          <span className="c6">&nbsp;</span>
        </p>
        <p className="c5">
          <span className="c6">
            Дезінформація – це неправдива або оманлива інформація, яка
            поширюється з метою впливу на громадську думку та/або приховування
            правди. Часто її навмисно використовують як інструмент в
            інформаційній війні. У випадку українсько-російської війни
            дезінформація використовується для спотворення фактів про зовнішню
            та внутрішню політику України та для створення негативного іміджу
            України в ЗМІ та міжнародній політиці.
          </span>
        </p>
        <p className="c5">
          <span className="c6">&nbsp;</span>
        </p>
        <p className="c5">
          <span className="c6">
            Під час оцінки німецьких та італійських ЗМІ з чорного списку ми
            виносимо такі вердикти щодо кожного дезінформаційного матеріалу:
          </span>
        </p>
        <p className="c5">
          <span className="c6">&nbsp;</span>
        </p>
        <p className="c5 c11">
          <span className="c14">●</span>
          <span className="c22 c14">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c20 c14">Фейк</span>
          <span className="c6">
            : інформація є повністю неправдивою та заснована на сумнівних
            джерелах.
          </span>
        </p>
        <p className="c5 c11">
          <span className="c14">●</span>
          <span className="c14 c22">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c20 c14">Маніпуляція</span>
          <span className="c6">
            : інформація частково правдива, але представлена в спотвореному
            контексті або не повністю. Автор маніпуляції намагається донести
            неправдиве повідомлення.
          </span>
        </p>
        <p className="c5 c11">
          <span className="c14">●</span>
          <span className="c22 c14">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c20 c14">Теорія змови: </span>
          <span className="c6">
            інформація неправдива, але ґрунтується на твердженнях, які не
            підтверджуються фактами, тобто деяких теоріях, що пояснюють події в
            результаті таємної змови.
          </span>
        </p>
        <p className="c5">
          <span className="c6">&nbsp;</span>
        </p>
        <p className="c5">
          <span className="c6">
            Ці види дезінформації є поширеними методами російських кампаній
            проти України. Найпоширенішими темами серед його наративів
            дезінформації є:
          </span>
        </p>
        <p className="c5">
          <span className="c6">&nbsp;</span>
        </p>
        <p className="c5 c11">
          <span className="c14">●</span>
          <span className="c22 c14">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c6">Євромайдан/Революція Гідності в Україні;</span>
        </p>
        <p className="c5 c11">
          <span className="c14">●</span>
          <span className="c22 c14">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c6">анексія Криму;</span>
        </p>
        <p className="c5 c11">
          <span className="c14">●</span>
          <span className="c22 c14">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c6">українсько-російська війна на Донбасі;</span>
        </p>
        <p className="c5 c11">
          <span className="c14">●</span>
          <span className="c22 c14">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c6">
            історичні події, особливо пов&apos;язані з історією
            українсько-російських відносин;
          </span>
        </p>
        <p className="c5 c11">
          <span className="c14">●</span>
          <span className="c22 c14">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c6">
            відносини України зі США, НАТО, ЄС та іншими партнерами;
          </span>
        </p>
        <p className="c5 c11">
          <span className="c14">●</span>
          <span className="c22 c14">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c6">реформи в Україні;</span>
        </p>
        <p className="c5 c11">
          <span className="c14">●</span>
          <span className="c22 c14">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c6">економіка України;</span>
        </p>
        <p className="c5 c11">
          <span className="c14">●</span>
          <span className="c22 c14">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c6">«нацисти та ультранаціоналісти» в Україні;</span>
        </p>
        <p className="c5 c11">
          <span className="c14">●</span>
          <span className="c22 c14">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c6">
            теорії змови про «зовнішнє управління» в Україні, тобто вплив Заходу
            на зовнішню та внутрішню політику України.
          </span>
        </p>
        <p className="c5">
          <span className="c6">&nbsp;</span>
        </p>
        <p className="c5">
          <span className="c25 c20 c14">Процес перевірки фактів</span>
        </p>
        <p className="c5">
          <span className="c6">&nbsp;</span>
        </p>
        <p className="c5">
          <span className="c6">
            Автори VoxCheck дотримуються прозорої політики під час перевірки
            фактів та розвінчування російської дезінформації про Україну. У
            наших статтях ми надаємо всі джерела для перегляду з достатньою
            детальністю, щоб читачі могли відтворити нашу роботу, за винятком
            випадків, коли особиста безпека джерела може бути порушена. У таких
            випадках ми надаємо найбільш детальну інформацію. Якість
            фактчеккінгу забезпечує редколегія проекту.
          </span>
        </p>
        <p className="c5">
          <span className="c6">&nbsp;</span>
        </p>
        <p className="c5">
          <span className="c14">VoxCheck,</span>
          <span className="c14">
            <a
              className="c4"
              href="https://www.google.com/url?q=https://ifcncodeofprinciples.poynter.org/signatories&amp;sa=D&amp;source=editors&amp;ust=1652628409076664&amp;usg=AOvVaw2JiYCZEPdIXGyU0UXra6r5"
            >
              &nbsp;
            </a>
          </span>
          <span className="c9">
            <a
              className="c4"
              href="https://www.google.com/url?q=https://ifcncodeofprinciples.poynter.org/signatories&amp;sa=D&amp;source=editors&amp;ust=1652628409076856&amp;usg=AOvVaw20tw3WPMFSQLivx0-uT6D7"
            >
              який підписав
            </a>
          </span>
          <span className="c14">&nbsp;</span>
          <span className="c14">Кодекс принципів IFCN, дотримується</span>
          <span className="c14">
            <a
              className="c4"
              href="https://www.google.com/url?q=https://www.ifcncodeofprinciples.poynter.org/know-more/the-commitments-of-the-code-of-principles&amp;sa=D&amp;source=editors&amp;ust=1652628409077088&amp;usg=AOvVaw2IUjfBTonC71eY7VaI900W"
            >
              &nbsp;
            </a>
          </span>
          <span className="c9">
            <a
              className="c4"
              href="https://www.google.com/url?q=https://www.ifcncodeofprinciples.poynter.org/know-more/the-commitments-of-the-code-of-principles&amp;sa=D&amp;source=editors&amp;ust=1652628409077282&amp;usg=AOvVaw3XfB7oT41p3hVIQjHLro0O"
            >
              зобов&apos;язань щодо
            </a>
          </span>
          <span className="c9">&nbsp;</span>
          <span className="c6">:</span>
        </p>
        <p className="c5">
          <span className="c6">&nbsp;</span>
        </p>
        <p className="c5 c11">
          <span className="c14">●</span>
          <span className="c22 c14">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c6">безпартійності і справедливості;</span>
        </p>
        <p className="c5 c11">
          <span className="c14">●</span>
          <span className="c22 c14">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c6">стандартів та прозорості джерел;</span>
        </p>
        <p className="c5 c11">
          <span className="c14">●</span>
          <span className="c22 c14">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c6">прозорості фінансування та організації;</span>
        </p>
        <p className="c5 c11">
          <span className="c14">●</span>
          <span className="c22 c14">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c6">
            стандартизованості та прозорості методології;
          </span>
        </p>
        <p className="c5 c11">
          <span className="c14">●</span>
          <span className="c22 c14">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </span>
          <span className="c6">відкритої та чесної політики виправлень.</span>
        </p>
        <p className="c5">
          <span className="c6">&nbsp;</span>
        </p>
        <p className="c5">
          <span className="c14">
            Ви можете знайти додаткову інформацію про нашу політику та принципи
            на{" "}
          </span>
          <span className="c9">
            <a
              className="c4"
              href="https://www.google.com/url?q=https://voxcheck.voxukraine.org/&amp;sa=D&amp;source=editors&amp;ust=1652628409078261&amp;usg=AOvVaw3rLBoNo-z4ca63UQtpAP8S"
            >
              офіційному веб-сайті
            </a>
          </span>
          <span className="c9">&nbsp;VoxCheck</span>
          <span className="c6">.</span>
        </p>
        <p className="c5">
          <span className="c6">&nbsp;</span>
        </p>
        <h3 className="c27" id="h.pbocq961dn0">
          <span className="c20 c28">
            Основні джерела перевіреної інформації про Україну
          </span>
        </h3>
        <p className="c5">
          <span className="c20 c26">&nbsp;</span>
        </p>
        <p className="c5">
          <span className="c1">&nbsp;</span>
        </p>
        <a id="t.18f51b844711974066ab570f3d67610ffe6d8477"></a>
        <a id="t.0"></a>
        <Table data={tableUkr} />
        <p className="c5">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c5 c44">
          <span className="c1">&nbsp;</span>
        </p>
        <p className="c0 c37">
          <span className="c6"></span>
        </p>
      </div>
    </div>
  );
}
