import Head from "next/head";
import styles from "../../styles/Home.module.css";

export default function LangDe() {
  return (
    <div>
      <Head>
        <title>Propaganda Diary | DE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>German Lang</div>
    </div>
  );
}
