import Head from "next/head";
import styles from "../../styles/Home.module.css";

export default function AboutRu() {
  return (
    <div>
      <Head>
        <title>Propaganda Diary | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container + " " + styles.aboutPageWrap}>
        <p className="c7">
          <span className="c6"></span>
        </p>
        <p className="c8">
          <span className="c4">
            Российская информационная стратегия использует существующую
            напряженность, преувеличивая споры и разногласия между людьми и
            усугубляя народные беспорядки, когда это возможно (например, Россия
            пыталась усилить социальные беспорядки во время протестов «желтых
            жилетов» во Франции). Внутренняя напряженность и столкновение
            подрывают развитые демократии и заставляют эти страны
            сосредоточиться на своей внутренней повестке, а не пытаться
            продвигать свои ценности и поддерживать прогресс в развивающихся
            странах. Это негативно влияет на такие страны, как Украина, которые
            ищут политическую поддержку со стороны Запада.
          </span>
        </p>
        <p className="c7">
          <span className="c4"></span>
        </p>
        <p className="c8">
          <span className="c4">
            Методы, используемые российской пропагандой, хорошо известны –
            манипуляции (размывание фактов неправильным толкованием),
            представление лжи как «альтернативных точек зрения» и
            высокоэмоциональная откровенная ложь, в которую трудно поверить, но
            легко запомнить. Знание их методов и нарративов может помочь
            ограничить потребление фейков и других деструктивных заявлений
            России. Поэтому VoxCheck создал базу российских фейков,
            дезинформации и пропаганды в двух европейских странах – Италии и
            Германии.
          </span>
        </p>
        <p className="c7">
          <span className="c4"></span>
        </p>
        <p className="c8">
          <span className="c4">
            Также рекомендуем прочитать дополнительную информацию об Украине,
            российско-украинской войне и российской пропаганде в следующих
            статьях:
          </span>
        </p>
        <p className="c7">
          <span className="c6"></span>
        </p>
        <ol className="c5 lst-kix_lgpdao1segwj-0 start" start="1">
          <li className="c0 li-bullet-0">
            <span className="c3">
              <a
                className="c2"
                href="https://voxukraine.org/ru/rashyzm-yly-pochemu-rossyyane-novye-natsysty/"
              >
                Рашизм, или почему россияне – новые нацисты
              </a>
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c3">
              <a
                className="c2"
                href="https://voxukraine.org/ru/obzor-provokatsyj-y-dezynformatsyy-rf/"
              >
                ОБНОВЛЯЕТСЯ. Обзор провокаций и дезинформации РФ
              </a>
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c3">
              <a
                className="c2"
                href="https://voxukraine.org/en/faq-on-the-russian-war-in-ukraine-what-are-we-fighting-for/"
              >
                FAQ о российско-украинской войне: за что мы боремся?
              </a>
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c3">
              <a
                className="c2"
                href="https://voxukraine.org/en/five-failures-of-putin-s-blitzkrieg-in-ukraine/"
              >
                5 провалов путинского блицкрига в Украине
              </a>
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c3">
              <a
                className="c2"
                href="https://voxukraine.org/ru/try-rossyjskyh-myfa-ot-kotoryh-stoyt-yzbavytsya-nemedlenno/"
              >
                Три российских мифа, от которых стоит избавиться немедленно
              </a>
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c1">
              <a
                className="c2"
                href="https://voxukraine.org/en/the-best-macroeconomic-policy-for-russia/"
              >
                Лучшая макроэкономическая политика для России{" "}
              </a>
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c3">
              <a
                className="c2"
                href="https://voxukraine.org/chym-my-ukrayintsi-vidriznyayemosya-vid-rosiyan-pragnennya-do-svobody-liberalnoyi-demokratiyi-ta-inklyuzyvnogo-suspilstva-yak-osnovni-markery-ukrayinsko-rosijskogo-rozryvu/"
              >
                Чем мы, украинцы, отличаемся от россиян? Желание свободы,
                либеральной демократии и инклюзивного общества как основные
                маркеры украинско-российского разрыва.{" "}
              </a>
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c3">
              <a
                className="c2"
                href="https://voxukraine.org/ru/gaagskyj-trybunal-za-chto-y-kak-budut-sudyt-rossyyu-obyasnyaet-voxcheck/"
              >
                Гаагский трибунал. За что и как будут судить россию? Объясняет
                VoxCheck
              </a>
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c3">
              <a
                className="c2"
                href="https://voxukraine.org/ru/zhenevskye-konventsyy-kak-yh-narushaet-rossyya-a-obvynyaet-v-etom-ukrayne-obyasnyaet-voxcheck/"
              >
                Женевские конвенции: как их нарушает россия, а обвиняет в этом
                Украине? Объясняет VoxCheck
              </a>
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c1">
              <a
                className="c2"
                href="https://voxukraine.org/en/democracy-under-the-bombs/"
              >
                Демократия под бомбами{" "}
              </a>
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c3">
              <a
                className="c2"
                href="https://voxukraine.org/en/it-s-not-putin-it-s-russia/"
              >
                Это не Путин, это Россия
              </a>
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c3">
              <a
                className="c2"
                href="https://voxukraine.org/en/sanctions-on-russian-oil-have-a-bite/"
              >
                Санкциии на нефть будут болючими для России, но не достаточно
                болючими для ЕС{" "}
              </a>
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c3">
              <a
                className="c2"
                href="https://voxukraine.org/ru/fynansovye-y-ekonomycheskye-sanktsyy-kogda-budet-dostatochno/"
              >
                Финансовые и экономические санкции: когда будет достаточно?
              </a>
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c3">
              <a
                className="c2"
                href="https://voxukraine.org/ru/ostanovyte-russkye-korruptsyonnye-dengy"
              >
                Остановите русские коррупционные деньги
              </a>
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c3">
              <a
                className="c2"
                href="https://voxukraine.org/ru/bespoletnaya-zona-nad-ukraynoj-ne-trebuet-ny-rezolyutsyy-nato-ny-soveta-bezopasnosty-oon-neobhodyma-volya-k-sotrudnychestvu-y-ne-dopustyt-chtoby-zlo-unychtozhylo-nashu-planetu/"
              >
                Бесполетная зона над Украиной не требует ни резолюции НАТО, ни
                Совета Безопасности ООН: необходима воля к сотрудничеству и не
                допустить, чтобы зло уничтожило нашу планету
              </a>
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c3">
              <a
                className="c2"
                href="https://voxukraine.org/en/the-moral-bankruptcy-of-buying-russian-energy/"
              >
                Моральное банкрутство покупки российских энергоносителей{" "}
              </a>
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c3">
              <a
                className="c2"
                href="https://voxukraine.org/en/the-cost-of-peace-without-a-reformed-russia-will-weigh-on-the-world-for-generations/"
              >
                Цена мира без реформированной России - будет стоить миллиарды
                многим следующим поколениям{" "}
              </a>
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c1">
              <a
                className="c2"
                href="https://voxukraine.org/en/hard-truths-about-likely-outcomes-of-russia-s-attack-on-ukraine/"
              >
                Жестокая правда о вероятных последствиях нападения России на
                Украину{" "}
              </a>
            </span>
          </li>
          <li className="c0 li-bullet-0">
            <span className="c3">
              <a
                className="c2"
                href="https://voxukraine.org/ru/chto-budet-s-pobezhdennoj-rossyjskoj-ymperyej/"
              >
                Что будет с побежденной российской империей?
              </a>
            </span>
          </li>
        </ol>
        <p className="c7">
          <span className="c6"></span>
        </p>
      </div>
    </div>
  );
}
