import Head from "next/head";
import FakeList from '../../components/FakeList/FakeList'
import styles from '../../styles/Home.module.css'

import { dataRu } from "../../data/dataRu";

export default function LangRu() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Propaganda Diary | RU</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FakeList data={dataRu} />
    </div>
  );
}
