import Head from 'next/head'
export default function About() {
  return (
    <div>
    <Head>
        <title>Propaganda Diary | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <p>About</p>
    </div>
  )
}
