import Head from "next/head";
import { useRouter } from "next/router";

import AboutUkr from "../pages/AboutPages/AboutUKR";
import AboutEn from "../pages/AboutPages/AboutEn";
import AboutRu from "../pages/AboutPages/AboutRu";
import AboutIt from "../pages/AboutPages/AboutIt";
import AboutDe from "../pages/AboutPages/AboutDe";

export default function About() {
  const router = useRouter();
  const { locale } = router;
  return (
    <div>
      <Head>
        <title>Propaganda Diary | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {locale == "ua" ? (
        <AboutUkr />
      ) : locale == "en" ? (
        <AboutEn />
      ) : locale == "ru" ? (
        <AboutRu />
      ) : locale == "it" ? (
        <AboutIt />
      ) : locale == "de" ? (
        <AboutDe />
      ) : null}
    </div>
  );
}
