import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function About() {
  return (
    <div>
      <Head>
        <title>Propaganda Diary | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container + " " + styles.aboutPageWrap}>
        <body className="c9">
          {/* <h2 className="c10" id="h.gbabkuuanz0">
            <span className="c11">Eng, It, De </span>
          </h2> */}
          <p className="c7">
            <span className="c4"></span>
          </p>
          <p className="c8">
            <span className="c4">
              Russian information strategy utilizes existing tensions by
              exaggerating disputes and disagreements between people and amplify
              popular unrest whenever possible (e.g. Russia tried to amplify
              social unrest during ‘yellow vest’ protests in France). Internal
              tensions and clashes undermine developed democracies and cause
              these countries to focus on their domestic agenda rather than
              trying to promote their values and support progress in the
              developing world. This adversely impacts countries such as Ukraine
              which look for guidance and political support from the West.
            </span>
          </p>
          <p className="c7">
            <span className="c4"></span>
          </p>
          <p className="c8">
            <span className="c4">
              The methods used by Russian propaganda are well known -
              manipulations (blurring facts with misinterpretations), presenting
              lies as ‘alternative points of view’, and highly emotional blatant
              lies that are hard to believe but easy to remember. Knowing their
              methods and narratives can help limit the consumption of fakes and
              controversies. Therefore, VoxCheck created the database of Russian
              fakes, disinformation, and propaganda in two European countries -
              Italy and Germany.
            </span>
          </p>
          <p className="c7">
            <span className="c4"></span>
          </p>
          <p className="c8">
            <span className="c4">
              We also recommend you to read additional information about
              Ukraine, Russia-Ukranian war and Russian propaganda in the next
              articles:{" "}
            </span>
          </p>
          <p className="c7">
            <span className="c4"></span>
          </p>
          <ol className="c5 lst-kix_wg6xnvezo99m-0 start" start="1">
            <li className="c0 li-bullet-0">
              <span className="c3">
                <a
                  className="c2"
                  href="https://www.google.com/url?q=https://voxukraine.org/en/rashism-or-why-russians-are-the-new-nazi/&amp;sa=D&amp;source=editors&amp;ust=1652630915860952&amp;usg=AOvVaw3McBqhMHJDqJh8BO4eILWl"
                >
                  Rashism or why russians are the new Nazi
                </a>
              </span>
            </li>
            <li className="c0 li-bullet-0">
              <span className="c1">
                <a
                  className="c2"
                  href="https://www.google.com/url?q=https://voxukraine.org/en/provocation-and-disinformation-overview/&amp;sa=D&amp;source=editors&amp;ust=1652630915861328&amp;usg=AOvVaw0tZR3rTlRIEfzlOpv31dm5"
                >
                  UPDATED. Provocation and Disinformation Overview
                </a>
              </span>
            </li>
            <li className="c0 li-bullet-0">
              <span className="c3">
                <a
                  className="c2"
                  href="https://www.google.com/url?q=https://voxukraine.org/en/faq-on-the-russian-war-in-ukraine-what-are-we-fighting-for/&amp;sa=D&amp;source=editors&amp;ust=1652630915861536&amp;usg=AOvVaw3wbR7rlpE64yxSaJUHfg62"
                >
                  FAQ on the Russian war in Ukraine: what are we fighting for?
                </a>
              </span>
            </li>
            <li className="c0 li-bullet-0">
              <span className="c3">
                <a
                  className="c2"
                  href="https://www.google.com/url?q=https://voxukraine.org/en/five-failures-of-putin-s-blitzkrieg-in-ukraine/&amp;sa=D&amp;source=editors&amp;ust=1652630915861774&amp;usg=AOvVaw2MVC-18zZM0t1LrNTW5mHv"
                >
                  Five failures of putin’s blitzkrieg in Ukraine
                </a>
              </span>
            </li>
            <li className="c0 li-bullet-0">
              <span className="c3">
                <a
                  className="c2"
                  href="https://www.google.com/url?q=https://voxukraine.org/en/three-russian-myths-that-you-should-abandon-right-away/&amp;sa=D&amp;source=editors&amp;ust=1652630915861999&amp;usg=AOvVaw0tn4XRBouJ-3CFfT_ukyDx"
                >
                  Three Russian myths that you should abandon right away
                </a>
              </span>
            </li>
            <li className="c0 li-bullet-0">
              <span className="c1">
                <a
                  className="c2"
                  href="https://www.google.com/url?q=https://voxukraine.org/en/the-best-macroeconomic-policy-for-russia/&amp;sa=D&amp;source=editors&amp;ust=1652630915862380&amp;usg=AOvVaw3FcIz1d50Ts7tMCLNb8PDL"
                >
                  The best macroeconomic policy for Russia
                </a>
              </span>
            </li>
            <li className="c0 li-bullet-0">
              <span className="c1">
                <a
                  className="c2"
                  href="https://www.google.com/url?q=https://voxukraine.org/en/what-makes-us-ukrainians-different-from-russians-aspirations-for-freedom-liberal-democracy-and-inclusive-society-as-the-primary-markers-for-the-ukrainian-russian-divide/&amp;sa=D&amp;source=editors&amp;ust=1652630915862664&amp;usg=AOvVaw0tQILk3j8rK7mA82XIN2b9"
                >
                  What makes us, Ukrainians, different from Russians?
                  Aspirations for freedom, liberal democracy, and inclusive
                  society as the primary markers for the Ukrainian-Russian
                  divide!
                </a>
              </span>
            </li>
            <li className="c0 li-bullet-0">
              <span className="c1">
                <a
                  className="c2"
                  href="https://www.google.com/url?q=https://voxukraine.org/en/the-hague-tribunal-what-will-russia-be-tried-for-and-how-voxcheck-explains/&amp;sa=D&amp;source=editors&amp;ust=1652630915862891&amp;usg=AOvVaw3ZSJ8p7dVrIFAWYINdyVET"
                >
                  The Hague Tribunal: What will russia be tried for and how?
                  VoxCheck explains
                </a>
              </span>
            </li>
            <li className="c0 li-bullet-0">
              <span className="c3">
                <a
                  className="c2"
                  href="https://www.google.com/url?q=https://voxukraine.org/en/the-geneva-conventions-how-russia-breaches-them-and-blames-ukraine-for-it-voxcheck-explains/&amp;sa=D&amp;source=editors&amp;ust=1652630915863120&amp;usg=AOvVaw3FAf0TQ1h05HBYKZCcN1Xi"
                >
                  The Geneva Conventions: How Russia breaches them and blames
                  Ukraine for it. VoxCheck explains
                </a>
              </span>
            </li>
            <li className="c0 li-bullet-0">
              <span className="c1">
                <a
                  className="c2"
                  href="https://www.google.com/url?q=https://voxukraine.org/en/democracy-under-the-bombs/&amp;sa=D&amp;source=editors&amp;ust=1652630915863347&amp;usg=AOvVaw3VGFdZ9_A4aAJjNcjua_S8"
                >
                  Democracy under the bombs
                </a>
              </span>
            </li>
            <li className="c0 li-bullet-0">
              <span className="c3">
                <a
                  className="c2"
                  href="https://www.google.com/url?q=https://voxukraine.org/en/it-s-not-putin-it-s-russia/&amp;sa=D&amp;source=editors&amp;ust=1652630915863579&amp;usg=AOvVaw16aPwqjuBpIs72okBwgdLe"
                >
                  It’s not Putin, it’s Russia
                </a>
              </span>
            </li>
            <li className="c0 li-bullet-0">
              <span className="c3">
                <a
                  className="c2"
                  href="https://www.google.com/url?q=https://voxukraine.org/en/sanctions-on-russian-oil-have-a-bite/&amp;sa=D&amp;source=editors&amp;ust=1652630915863795&amp;usg=AOvVaw3lzz_mPx8CPXI5uVsEbPRZ"
                >
                  Sanctions on Russian oil have a bite
                </a>
              </span>
            </li>
            <li className="c0 li-bullet-0">
              <span className="c1">
                <a
                  className="c2"
                  href="https://www.google.com/url?q=https://voxukraine.org/en/financial-and-economic-sanctions-when-enough-is-enough/&amp;sa=D&amp;source=editors&amp;ust=1652630915864030&amp;usg=AOvVaw3Ny_fUmyl1is_N5xTHFvtv"
                >
                  Financial and economic sanctions: When enough is enough?
                </a>
              </span>
            </li>
            <li className="c0 li-bullet-0">
              <span className="c1">
                <a
                  className="c2"
                  href="https://www.google.com/url?q=https://voxukraine.org/en/stop-the-corruption-of-russian-money/&amp;sa=D&amp;source=editors&amp;ust=1652630915864227&amp;usg=AOvVaw1R3m37I6EsM9Cn70xfR6X0"
                >
                  Stop the corruption of Russian money
                </a>
              </span>
            </li>
            <li className="c0 li-bullet-0">
              <span className="c1">
                <a
                  className="c2"
                  href="https://www.google.com/url?q=https://voxukraine.org/en/ukraine-s-no-fly-zone-does-not-require-nato-nor-a-un-security-council-resolution-it-needs-good-to-cooperate-prevent-evil-from-destroying-our-planet/&amp;sa=D&amp;source=editors&amp;ust=1652630915864496&amp;usg=AOvVaw0ZQavluSMgyDfWuIFe7Yrw"
                >
                  Ukraine’s no-fly zone does not require NATO nor a UN Security
                  Council Resolution: it needs good to cooperate &amp; prevent
                  evil from destroying our planet
                </a>
              </span>
            </li>
            <li className="c0 li-bullet-0">
              <span className="c3">
                <a
                  className="c2"
                  href="https://www.google.com/url?q=https://voxukraine.org/en/the-moral-bankruptcy-of-buying-russian-energy/&amp;sa=D&amp;source=editors&amp;ust=1652630915864690&amp;usg=AOvVaw1eORjLUziLZ50eHZxZJvmn"
                >
                  The Moral Bankruptcy of Buying Russian Energy
                </a>
              </span>
            </li>
            <li className="c0 li-bullet-0">
              <span className="c3">
                <a
                  className="c2"
                  href="https://www.google.com/url?q=https://voxukraine.org/en/the-cost-of-peace-without-a-reformed-russia-will-weigh-on-the-world-for-generations/&amp;sa=D&amp;source=editors&amp;ust=1652630915864936&amp;usg=AOvVaw0UKk8mpFIo3zd8t9EH1XVS"
                >
                  The Cost of “Peace” without a reformed Russia will weigh on
                  the world for generations
                </a>
              </span>
            </li>
            <li className="c0 li-bullet-0">
              <span className="c1">
                <a
                  className="c2"
                  href="https://www.google.com/url?q=https://voxukraine.org/en/hard-truths-about-likely-outcomes-of-russia-s-attack-on-ukraine/&amp;sa=D&amp;source=editors&amp;ust=1652630915865184&amp;usg=AOvVaw2aJw5tJP4ztI6J8rDmudTk"
                >
                  Hard truths about likely outcomes of Russia’s attack on
                  Ukraine
                </a>
              </span>
            </li>
            <li className="c0 li-bullet-0">
              <span className="c3">
                <a
                  className="c2"
                  href="https://www.google.com/url?q=https://voxukraine.org/en/what-will-happen-to-a-defeated-russian-empire/&amp;sa=D&amp;source=editors&amp;ust=1652630915865375&amp;usg=AOvVaw1oR2cX2kMGe96q0qE36qBV"
                >
                  What will happen to a defeated russian empire?
                </a>
              </span>
            </li>
          </ol>
          <p className="c7">
            <span className="c4"></span>
          </p>
          
          
        </body>
      </div>
    </div>
  );
}
