import Head from "next/head";
import MediaList from "../components/MediaList/MediaList";
import { black_list_germany } from '../data/black_list_germany'
import { black_list_italy } from "../data/black_list_italy";

import styles from '../components/Sidebar/Sidebar.module.css'

export default function BlackList() {
  return (
    <div>
      <Head>
        <title>Propaganda Diary | Black List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <h4 className={styles.countryMedia}>GERMANY</h4>
        <MediaList data={black_list_germany} />
        <h4 className={styles.countryMedia}>ITALY</h4>
        <MediaList data={black_list_italy} />
      </>
    </div>
  );
}
