import Head from "next/head";
export default function Download() {
  return (
    <div>
      <Head>
        <title>Propaganda Diary | Download</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Download</p>
    </div>
  );
}
