import Head from "next/head";
import FakeList from "../components/FakeList/FakeList";
import PopupCookie from "../components/PopupCookie/PopupCookie";
import styles from "../styles/Home.module.css";

import { useRouter } from "next/router";

import { dataEng } from "../data/dataEng";
import { dataUkr } from "../data/dataUkr";
import { dataRu } from "../data/dataRu";
import { dataDe } from "../data/dataDe";
import { dataIt } from "../data/dataIt";

export default function Home() {
  const router = useRouter();
  const { locale } = router;

  const data =
    locale == "en"
      ? dataEng
      : locale == "ua"
      ? dataUkr
      : locale == "ru"
      ? dataRu
      : locale == "de"
      ? dataDe
      : locale == "it"
      ? dataIt
      : dataEng;

  return (
    <div className={styles.container}>
      <Head>
        <title>Propaganda Diary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FakeList data={data} />
      <PopupCookie />
    </div>
  );
}
