import Head from "next/head";
import { useRouter } from "next/router";

import MethodUkr from "./MethodPages/MethodUkr";
import MethodRu from "./MethodPages/MethodRu";
import MethodIt from "./MethodPages/MethodIt";
import MethodEn from "./MethodPages/MethodEn";
import MethodDe from "./MethodPages/MethodDE";

export default function How() {
  const router = useRouter();
  const { locale } = router;
  return (
    <div>
      <Head>
        <title>Propaganda Diary | How</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {locale == "ua" ? (
        <MethodUkr />
      ) : locale == "en" ? (
        <MethodEn />
      ) : locale == "ru" ? (
        <MethodRu />
      ) : locale == "it" ? (
        <MethodIt />
      ) : locale == "de" ? (
        <MethodDe />
      ) : null}
     
    </div>
  );
}
