import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function How() {
  return (
    <div>
      <Head>
        <title>Propaganda Diary | How</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container + " " + styles.aboutPageWrap}>
        <body className="c28">
          <p className="c14 c6">
            <span className="c13">
              The project “Propaganda diary” on disinformation about Ukraine in
              German and Italian media is based on methodology. Here you can get
              the information about our methods and policies.
            </span>
          </p>
          <p className="c4">
            <span className="c13"></span>
          </p>
          <p className="c14 c6">
            <span className="c10">White and black lists of media</span>
          </p>
          <p className="c4">
            <span className="c13"></span>
          </p>
          <p className="c14 c6">
            <span className="c13">
              First, to form the database on disinformation it was necessary to
              identify key media outlets in relevant countries and distinguish
              credible sources from questionable ones. Thus, we created white
              and black lists of media in Germany and Italy.{" "}
            </span>
          </p>
          <p className="c4">
            <span className="c13"></span>
          </p>
          <p className="c14 c6">
            <span className="c13">
              Media on the white list are high-quality media providing reliable
              information about Ukraine’s foreign and domestic policies. On the
              contrary, sources on the black list spread fake news about Ukraine
              on a regular basis.
            </span>
          </p>
          <p className="c4">
            <span className="c13"></span>
          </p>
          <p className="c14 c6">
            <span className="c13">
              To differentiate sources and create these lists we used the
              following criteria:
            </span>
          </p>
          <p className="c4">
            <span className="c13"></span>
          </p>
          <ul className="c15 lst-kix_706aym3aycb-0 start">
            <li className="c19 c6 li-bullet-0">
              <span className="c17">Content</span>
              <span className="c13">
                . All media outlets, either on the white list or on the black
                list, regularly report news and publish analytical articles
                about politics, international relations, Ukraine in particular.
              </span>
            </li>
            <li className="c19 c6 li-bullet-0">
              <span className="c17">Professional standards</span>
              <span className="c13">
                . The high-quality media on the white list must meet the
                journalistic standards: comprehensiveness and impartiality of
                news coverage; objectivity and emotional neutrality; balance of
                opinions; availability and reliability of information sources;
                separation of facts and comments. Media on the black list
                constantly neglect these standards when reporting about Ukraine.
              </span>
            </li>
            <li className="c19 c6 li-bullet-0">
              <span className="c17">Ownership and transparency</span>
              <span className="c13">
                . The media must publicly report about its owner, funding, and
                possible conflict of interest. For example, some Italian and
                German media are directly linked to Russian state-owned news
                agencies. Thus, such media will most likely spread
                disinformation about Ukraine.
              </span>
            </li>
            <li className="c19 c6 li-bullet-0">
              <span className="c17">
                Results of media monitoring from Media Bias / Fact Check
              </span>
              <span className="c21">
                . We selected some of the media according to the resource{" "}
              </span>
              <span className="c0">
                <a
                  className="c8"
                  href="https://www.google.com/url?q=https://mediabiasfactcheck.com/&amp;sa=D&amp;source=editors&amp;ust=1652627142327710&amp;usg=AOvVaw0cf1sv_p4wXPsvLHB8JNxX"
                >
                  Media Bias / Fact Check
                </a>
              </span>
              <span className="c13">
                , an independent website that rates the bias, factual accuracy,
                and credibility of sources. According to this resource, the
                selected media on the black list have a very low or mixed level
                of factual reporting. The media on the white list are rated at
                the least biased sources and have a high level of factual
                reporting.
              </span>
            </li>
            <li className="c19 c6 li-bullet-0">
              <span className="c17">
                Results of media monitoring from EUvsDisinfo
              </span>
              <span className="c21">
                . In addition, we used EUvsDisinfo databases on{" "}
              </span>
              <span className="c0">
                <a
                  className="c8"
                  href="https://www.google.com/url?q=https://euvsdisinfo.eu/disinformation-cases/?text%3D%26date%3D%26disinfo_language%255B%255D%3DGerman%26disinfo_countries%255B%255D%3D77554%26per_page%3D&amp;sa=D&amp;source=editors&amp;ust=1652627142328321&amp;usg=AOvVaw3J5DF4y5q6upgH87sCQYP4"
                >
                  Germany
                </a>
              </span>
              <span className="c21">&nbsp;and </span>
              <span className="c0">
                <a
                  className="c8"
                  href="https://www.google.com/url?q=https://euvsdisinfo.eu/disinformation-cases/?text%3D%26date%3D%26disinfo_language%255B%255D%3DItalian%26disinfo_countries%255B%255D%3D77582%26per_page%3D&amp;sa=D&amp;source=editors&amp;ust=1652627142328653&amp;usg=AOvVaw0v5pw1g04H4UafrM5u27o4"
                >
                  Italy
                </a>
              </span>
              <span className="c21">
                , as well as cases of fake distribution recorded by German and
                Italian fact-checkers, who signed the IFCN Code of Principle.{" "}
              </span>
              <span className="c0">
                <a
                  className="c8"
                  href="https://www.google.com/url?q=https://euvsdisinfo.eu/about/&amp;sa=D&amp;source=editors&amp;ust=1652627142328955&amp;usg=AOvVaw0Wcu_MdadqoQ9DRPpFPB22"
                >
                  EUvsDisinfo
                </a>
              </span>
              <span className="c13">
                &nbsp;is the project of the European External Action Service’s
                East StratCom Task Force. It was established specifically to
                monitor and counter the Russian disinformation campaigns in
                Europe.
              </span>
            </li>
            <li className="c6 c19 li-bullet-0">
              <span className="c17">Results of our own media monitoring. </span>
              <span className="c13">
                When selecting media for monitoring, we have focused on the
                quality of reporting about Ukraine. The sources that published
                Russian disinformation previously were added to the black list.
              </span>
            </li>
            <li className="c19 c6 li-bullet-0">
              <span className="c17">
                Consultations with German and Italian fact-checkers and
                journalists.{" "}
              </span>
              <span className="c13">
                We also sought advice from colleagues working in Germany and
                Italy. Representatives from different organizations advised us
                to pay attention to some media which were previously spreading
                fake news.
              </span>
            </li>
          </ul>
          <p className="c4">
            <span className="c13"></span>
          </p>
          <p className="c14 c6">
            <span className="c10">Disinformation narratives</span>
          </p>
          <p className="c4">
            <span className="c13"></span>
          </p>
          <p className="c14 c6">
            <span className="c13">
              The database consists of hundreds of manipulative news reports
              from German and Italian media. To categorize this dataset we
              classNameified news reports into dangerous and destabilizing
              narratives of the Russian disinformation campaign.
            </span>
          </p>
          <p className="c4">
            <span className="c13"></span>
          </p>
          <p className="c14 c6">
            <span className="c13">
              Different news reports are examples of a single disinformation
              narrative when they convey the same message, either explicit or
              hidden, intended to influence public opinion in relevant countries
              by distorting the picture of reality. All the narratives in the
              database are typical messages for the Russian disinformation
              campaign against Ukraine. For instance, “Ukraine is continuing
              military buildup in Donbas” and “Ukraine is violating the
              ceasefire regime” can be clear examples of the narrative “Ukraine
              fails to deliver commitments under the Minsk Agreements”, as they
              have the same meaning and purpose in terms of disinformation.
            </span>
          </p>
          <p className="c4">
            <span className="c13"></span>
          </p>
          <p className="c14 c6">
            <span className="c13">
              There are also subtypes of disinformation narratives. These
              subtypes specify the general narrative. For example, “The U.S.
              organized coup d&apos;état in Ukraine in 2014” is a subtype of the
              narrative “Maidan in 2014 was a coup d&apos;état”.
            </span>
          </p>
          <p className="c4">
            <span className="c13"></span>
          </p>
          <p className="c14 c6">
            <span className="c13">
              However, it is often impossible to identify the exact motives of
              authors, who participated in spreading fake news. Therefore we
              cannot confirm that all these authors and media spread
              disinformation about Ukraine on purpose. At the same time
              narratives in these media are similar or almost identical to those
              spread by the Russian Federation officials.
            </span>
          </p>
          <p className="c4">
            <span className="c13"></span>
          </p>
          <p className="c14 c6">
            <span className="c10">Types of disinformation</span>
          </p>
          <p className="c4">
            <span className="c13"></span>
          </p>
          <p className="c14 c6">
            <span className="c13">
              Disinformation is false or misleading information spread to
              influence public opinion and/or obscure the truth. It is
              frequently used deliberately as a tool in information warfare. In
              the case of the Ukraine-Russia war, disinformation is used to
              distort facts about Ukraine’s foreign and domestic policies and to
              create a negative image of Ukraine in the media and international
              politics.
            </span>
          </p>
          <p className="c4">
            <span className="c13"></span>
          </p>
          <p className="c6 c14">
            <span className="c13">
              During the evaluation of the German and Italian media from the
              black list we render the following verdicts for each
              disinformation material:
            </span>
          </p>
          <p className="c4">
            <span className="c13"></span>
          </p>
          <ul className="c15 lst-kix_eu6uxl4iqrd6-0 start">
            <li className="c19 c6 li-bullet-0">
              <span className="c17">Fake</span>
              <span className="c13">
                : the information is completely false and based on questionable
                sources.
              </span>
            </li>
            <li className="c19 c6 li-bullet-0">
              <span className="c17">Manipulation</span>
              <span className="c13">
                : the information is partly true, but presented in a distorted
                context or not completely. The author of the manipulation is
                trying to convey a false message.
              </span>
            </li>
            <li className="c19 c6 li-bullet-0">
              <span className="c17">Conspiracy theory: </span>
              <span className="c13">
                the information is false, but it is based on completely
                non-fact-checkable claims, i.e. some theories that explain
                events as a result of a secret plot.
              </span>
            </li>
          </ul>
          <p className="c4">
            <span className="c13"></span>
          </p>
          <p className="c14 c6">
            <span className="c13">
              These types of disinformation are common methods of the Russian
              campaigns against Ukraine. The most common topics among its
              disinformation narratives are:
            </span>
          </p>
          <p className="c4">
            <span className="c13"></span>
          </p>
          <ul className="c15 lst-kix_ginqog1vm1du-0 start">
            <li className="c19 c6 li-bullet-0">
              <span className="c13">
                the Euromaidan/the Revolution of Dignity in Ukraine;
              </span>
            </li>
            <li className="c19 c6 li-bullet-0">
              <span className="c13">annexation of Crimea;</span>
            </li>
            <li className="c19 c6 li-bullet-0">
              <span className="c13">the ongoing Ukraine-Russia war in Donbas;</span>
            </li>
            <li className="c19 c6 li-bullet-0">
              <span className="c13">
                historic events, especially connected with the history of
                Ukraine-Russia relations;
              </span>
            </li>
            <li className="c19 c6 li-bullet-0">
              <span className="c13">
                relations of Ukraine with the U.S., NATO, EU and other partners;
              </span>
            </li>
            <li className="c19 c6 li-bullet-0">
              <span className="c13">reforms in Ukraine;</span>
            </li>
            <li className="c19 c6 li-bullet-0">
              <span className="c13">Ukraine’s economy;</span>
            </li>
            <li className="c19 c6 li-bullet-0">
              <span className="c13">
                “nazis and ultra-nationalists” in Ukraine;
              </span>
            </li>
            <li className="c19 c6 li-bullet-0">
              <span className="c13">
                conspiracy theories about “external governance” in Ukraine, i.e.
                influence of the West on Ukraine’s foreign and domestic
                policies.
              </span>
            </li>
          </ul>
          <p className="c4">
            <span className="c13"></span>
          </p>
          <p className="c14 c6">
            <span className="c10">Fact-checking process</span>
          </p>
          <p className="c4">
            <span className="c13"></span>
          </p>
          <p className="c14 c6">
            <span className="c13">
              Authors of VoxCheck follow a transparent policy during
              fact-checking and debunking Russian disinformation about Ukraine.
              In our articles, we provide all sources for review in sufficient
              detail so that readers can reproduce our work, except when the
              personal security of the source may be compromised. In such cases,
              we provide the most detailed information. The quality of
              fact-checking is ensured by the project&apos;s editorial board.{" "}
            </span>
          </p>
          <p className="c4">
            <span className="c13"></span>
          </p>
          <p className="c14 c6">
            <span className="c21">VoxCheck as </span>
            <span className="c0">
              <a
                className="c8"
                href="https://www.google.com/url?q=https://ifcncodeofprinciples.poynter.org/signatories&amp;sa=D&amp;source=editors&amp;ust=1652627142333946&amp;usg=AOvVaw3UgXtZq39D20CTsyNyTwss"
              >
                a signatory
              </a>
            </span>
            <span className="c21">
              &nbsp;of the IFCN Code of principles abides by the{" "}
            </span>
            <span className="c0">
              <a
                className="c8"
                href="https://www.google.com/url?q=https://www.ifcncodeofprinciples.poynter.org/know-more/the-commitments-of-the-code-of-principles&amp;sa=D&amp;source=editors&amp;ust=1652627142334368&amp;usg=AOvVaw1f7mkLz98SWS4KBwd58Prh"
              >
                commitments to
              </a>
            </span>
            <span className="c13">:</span>
          </p>
          <p className="c4">
            <span className="c13"></span>
          </p>
          <ul className="c15 lst-kix_1mm8poilrjoc-0 start">
            <li className="c19 c6 li-bullet-0">
              <span className="c13">non-partisanship and fairness;</span>
            </li>
            <li className="c19 c6 li-bullet-0">
              <span className="c13">standards and transparency of sources;</span>
            </li>
            <li className="c19 c6 li-bullet-0">
              <span className="c13">transparency of funding and organization;</span>
            </li>
            <li className="c19 c6 li-bullet-0">
              <span className="c13">
                standards and transparency of methodology;
              </span>
            </li>
            <li className="c19 c6 li-bullet-0">
              <span className="c13">open and honest corrections policy.</span>
            </li>
          </ul>
          <p className="c4">
            <span className="c13"></span>
          </p>
          <p className="c14 c6">
            <span className="c21">
              You can find additional information about our policies and
              principles on our{" "}
            </span>
            <span className="c0">
              <a
                className="c8"
                href="https://www.google.com/url?q=https://voxcheck.voxukraine.org/&amp;sa=D&amp;source=editors&amp;ust=1652627142335444&amp;usg=AOvVaw0B5X4bImxi3yxpxTUUV3R4"
              >
                official website
              </a>
            </span>
            <span className="c13">.</span>
          </p>
          <p className="c4">
            <span className="c13"></span>
          </p>
          <h3 className="c6 c33" id="h.7145rrc6hi1k">
            <span className="c24">
              Primary sources of fact-checked information about Ukraine
            </span>
          </h3>
          <p className="c22 c6">
            <span className="c25"></span>
          </p>
          <p className="c6 c22">
            <span className="c12"></span>
          </p>
          <a id="t.5a5e73bde5096445504d8dfc2a9545de78b5058b"></a>
          <a id="t.0"></a>
          <table className="c26">
            <tbody>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c11">№</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c11">Source</span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c11">Description</span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c11">Link to ENG website</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">1</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">State Statistics Service of Ukraine</span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">
                      The State Statistics Service of Ukraine (Gosstat) is a
                      specially authorized central executive body in the field
                      of statistics, whose activities are directed and
                      coordinated by the Cabinet of Ministers of Ukraine and
                      which ensures the formation and implementation of state
                      policy in the field of statistics.
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=http://www.ukrstat.gov.ua/&amp;sa=D&amp;source=editors&amp;ust=1652627142339003&amp;usg=AOvVaw3eSpoDFuftyDFgSfbspKiy"
                      >
                        http://www.ukrstat.gov.ua/
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">2</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">The Presidential Office of Ukraine</span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">
                      The duties of the Office are to provide administrative,
                      legal, consultative, advisory, media, analytical and other
                      assistance to the President when exercising authorities.
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=https://www.president.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652627142340940&amp;usg=AOvVaw0qx4D-EtXZYFejQ3kiOcvl"
                      >
                        https://www.president.gov.ua/en
                      </a>
                    </span>
                    <span className="c12">&nbsp;</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">3</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">The Security Service of Ukraine</span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">
                      The Security Service of Ukraine is the main security
                      agency of Ukraine. Its main priorities are
                      counterintelligence, protection of national statehood,
                      counterterrorism, protection of informational security,
                      protection of state secrets.
                    </span>
                  </p>
                  <p className="c3 c27">
                    <span className="c12"></span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=https://ssu.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652627142343196&amp;usg=AOvVaw394yg2G8ajgWT8EncP7NaH"
                      >
                        https://ssu.gov.ua/en
                      </a>
                    </span>
                    <span className="c12">&nbsp;</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">4</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">
                      National Security and Defense Council of Ukraine
                    </span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">
                      The National Security and Defense Council of Ukraine is
                      the coordinating body in matters pertaining to national
                      security and defense under the President of Ukraine.
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=https://www.rnbo.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652627142344648&amp;usg=AOvVaw1CtRS1WpgUHHtC0N-ETQ8X"
                      >
                        https://www.rnbo.gov.ua/en/
                      </a>
                    </span>
                    <span className="c12">&nbsp;</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">5</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">
                      Center for Countering Disinformation
                    </span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">
                      The Center for Countering Disinformation is a working body
                      of the National Security and Defense Council of Ukraine.
                      The Center provides measures to counter current and
                      projected threats to national security and national
                      interests of Ukraine in the information sphere.
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">-</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">6</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">The Government of Ukraine</span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">
                      The Government of Ukraine or The Cabinet of Ministers of
                      Ukraine is the highest body of state executive power in
                      Ukraine. The body consist of Prime Minister of Ukraine,
                      vice prime ministers and other ministers from different
                      institutions. The prime minister presides over the
                      cabinet.{" "}
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=https://www.kmu.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652627142347075&amp;usg=AOvVaw2Ov01os2bwLQdGWR0-SJqG"
                      >
                        https://www.kmu.gov.ua/en
                      </a>
                    </span>
                    <span className="c12">&nbsp;</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">7</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c23 c6">
                    <span className="c12">Verkhovna Rada of Ukraine</span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">
                      The Verkhovna Rada is the parliament of Ukraine.It is the
                      sole organ of legislative power in Ukraine.The parliament
                      consists of 450 deputies elected by Ukrainian people.{" "}
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=https://www.rada.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652627142348394&amp;usg=AOvVaw3DnGjL2gQyPFoI71dYon8Z"
                      >
                        https://www.rada.gov.ua/en
                      </a>
                    </span>
                    <span className="c12">&nbsp;</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">8</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c23 c6">
                    <span className="c12">State Treasury Service of Ukraine</span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">
                      The State Treasury Service of Ukraine is the central
                      executive body of Ukraine that implements the state policy
                      in the field of treasury service of budget funds. The
                      activities of the service are directed and coordinated by
                      the Cabinet of Ministers of Ukraine through the Minister
                      of Finance of Ukraine.
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=https://www.treasury.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652627142349694&amp;usg=AOvVaw3_742c4AnixQAwIgtC5ml6"
                      >
                        https://www.treasury.gov.ua/en
                      </a>
                    </span>
                    <span className="c12">&nbsp;</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c23 c6">
                    <span className="c12">9</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">State Tax Service of Ukraine</span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">
                      The State Tax Service of Ukraine is the central executive
                      body in the field of taxes in Ukraine. The activities of
                      the service are directed and coordinated by the Cabinet of
                      Ministers of Ukraine through the Minister of Finance.
                    </span>
                  </p>
                  <p className="c3">
                    <span className="c12">
                      The service implements the national tax policy and
                      national policy in the field of combating offenses during
                      the application of tax legislation
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=https://tax.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652627142351333&amp;usg=AOvVaw2yi5eO3W3KxNn8HNLGt8eQ"
                      >
                        https://tax.gov.ua/en/
                      </a>
                    </span>
                    <span className="c12">&nbsp;</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c6 c23">
                    <span className="c12">10</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">Custom Service of Ukraine</span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">
                      The State Customs Service of Ukraine is the central
                      executive body of Ukraine, which implements the national
                      customs policy and the national policy in the field of
                      combating offenses during the application of the
                      legislation on national customs affairs. The activities of
                      the service are directed and coordinated by the Cabinet of
                      Ministers of Ukraine through the Minister of Finance.
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=https://customs.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652627142352646&amp;usg=AOvVaw26S0mFjHLAN-h41ixRzAkX"
                      >
                        https://customs.gov.ua/en
                      </a>
                    </span>
                    <span className="c12">&nbsp;</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">11</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">
                      State Border Guard Service of Ukraine
                    </span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c29">
                      The State Border Guard Service of Ukraine is law
                      enforcement agence charged with the tasks of ensuring
                      inviolability of state borders and protection of sovereign
                      rights of Ukraine within its exclusive (maritime) economic
                      zone.
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=https://dpsu.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652627142353994&amp;usg=AOvVaw3-jg6gAtWCiGXoYdu4pcSM"
                      >
                        https://dpsu.gov.ua/en/
                      </a>
                    </span>
                    <span className="c12">&nbsp; ​​</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">12</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">National Bank of Ukraine</span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">
                      The National Bank of Ukraine is a government body
                      responsible for unified state policy in the field of
                      country&apos;s monetary circulation, including strengthening of
                      the national currency unit. Its mission is to ensure price
                      and financial stability, with the goal of contributing to
                      Ukraine’s sustainable economic development.
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=https://bank.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652627142355434&amp;usg=AOvVaw2IYlSNjvxma565YirUmFLr"
                      >
                        https://bank.gov.ua/en/
                      </a>
                    </span>
                    <span className="c12">&nbsp;</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">13</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">
                      Ministry of Digital transformation of Ukraine
                    </span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">
                      Ministry of Digital transformation of Ukraine is a
                      governmental body. Its main goal is to promote
                      digitalisation in Ukraine, especially infrastructure
                      development, creation of favorable environment for IT
                      sector, and promotion of digital literacy.{" "}
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">-</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">14</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">Ministry of Finance of Ukraine</span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">
                      The Ministry of Finance of Ukraine is responsible for the
                      formation and implementation of the following key areas of
                      government policy: budgetary policy, tax and customs
                      policy, debt policy. international financial cooperation.
                      The mission of the Ministry is to provide financial basis
                      for the proper delivery of public functions supported by a
                      well-balanced budgetary policy as well as to create
                      favorable conditions for a stable economic development.
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=https://mof.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652627142357901&amp;usg=AOvVaw0ACWG_hattqj1SQ3qejDAd"
                      >
                        https://mof.gov.ua/en
                      </a>
                    </span>
                    <span className="c12">&nbsp;</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">15</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">Ministry of Defense of Ukraine</span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">
                      The Ministry of Defense of Ukraine is the main (leading)
                      body in the system of central executive bodies to ensure
                      the implementation of state policy in the field of
                      defense. It participates in the implementation of state
                      policy on defense and military construction, coordination
                      of activities of state bodies and local governments to
                      prepare the state for defense.
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=https://www.mil.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652627142359305&amp;usg=AOvVaw3JhL_Jo0LGuG-uP-m_hxWv"
                      >
                        https://www.mil.gov.ua/en/
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">16</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">Defence Intelligence</span>
                  </p>
                  <p className="c3 c6">
                    <span className="c12">
                      of the Ministry of Defence of Ukraine
                    </span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c31">
                      The Defence Intelligence of Ukraine conducts intelligence
                      in the defence, development of military capability,
                      military and military-technical as well as cybersecurity
                      areas.
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=https://gur.gov.ua/en.html&amp;sa=D&amp;source=editors&amp;ust=1652627142360812&amp;usg=AOvVaw3T07SOHcdamD5gf5e6_5ar"
                      >
                        https://gur.gov.ua/en.html
                      </a>
                    </span>
                    <span className="c12">&nbsp;</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">17</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">
                      Ministry for Reintegration of the Temporary Occupied
                      Territories of Ukraine
                    </span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">
                      The Ministry of Reintegration of Temporarily Occupied
                      Territories is government ministry in Ukraine, which
                      solves the tasks of prompt response to problems and
                      threats associated with the conduct of an anti-terrorist
                      operation in certain areas of the Donetsk and Luhansk
                      regions, as well as with the temporary occupation of the
                      territory of Ukraine.{" "}
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=https://minre.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652627142362086&amp;usg=AOvVaw0G2PMogtNN1yp_hBv12yA9"
                      >
                        https://minre.gov.ua/en
                      </a>
                    </span>
                    <span className="c12">&nbsp;</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">18</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">Decentralization in Ukraine</span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">
                      Decentralization reform is the official website for
                      reform. Decentralization means delegating considerable
                      authority and budgets from the state bodies to local
                      authorities
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=https://decentralization.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652627142363396&amp;usg=AOvVaw0tVAuW8cb6tC1024GtKGVa"
                      >
                        https://decentralization.gov.ua/en/
                      </a>
                    </span>
                    <span className="c12">&nbsp;</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">19</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">
                      Ministry of Social Policy of Ukraine
                    </span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">
                      The Ministry of Social Policy of Ukraine is the Ukrainian
                      government department responsible for instituting labor
                      relations, family and children, immigration and
                      trafficking, women&apos;s rights, children&apos;s rights, and
                      humanitarian aid.
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=https://www.msp.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652627142364706&amp;usg=AOvVaw2rrVQYoW7VgB8XP5H0O3-f"
                      >
                        https://www.msp.gov.ua/en/
                      </a>
                    </span>
                    <span className="c12">&nbsp;</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">20</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">
                      Ministry for Communities and Territories Development of
                      Ukraine
                    </span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">
                      The Ministry for Communities and Territories Development
                      of Ukraine (MinRegion) carries out state regulation in
                      architecture, construction, and urban planning. The
                      Ministry`s priority tasks are developing and improving
                      regulation in architecture, construction, and urban
                      planning, considering EU legislation requirements in
                      relevant areas, simplifying permitting procedures, and
                      implementing new technologies.
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=https://www.minregion.gov.ua/en/ministry-for-development-of-communities-and-territories-of-ukraine&amp;sa=D&amp;source=editors&amp;ust=1652627142366109&amp;usg=AOvVaw201O5hpfhncn0Ixdi8F9rW"
                      >
                        https://www.minregion.gov.ua/en/
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">21</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">
                      Ministry of Ecology and Environment Protection of Ukraine
                    </span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">
                      Ministry of Ecology and Natural Resources of Ukraine is a
                      central executive authority activity of which is governed
                      and coordinated by the Cabinet of Ministers of Ukraine.
                      Ministry of Ecology and Natural resources operates in the
                      field of environmental protection, ecological safety,
                      treatment of waste, hazardous chemicals, pesticides and
                      agricultural chemicals and perform state ecological
                      expertise.
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=https://mepr.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652627142367573&amp;usg=AOvVaw3MHfCRuGyHZ-UUbWH9qUaP"
                      >
                        https://mepr.gov.ua/en/
                      </a>
                    </span>
                    <span className="c12">&nbsp;</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">22</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">
                      Ministry of Energy and Coal Industry of Ukraine
                    </span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">
                      The Ministry of Energy and Coal provides the formulation
                      and implementation of the state policy in the electric
                      power, nuclear-industrial, coal-industrial, peat-mining,
                      oil and gas and oil-and-gas processing complexes, and also
                      provides the formation of the state policy in the sphere
                      of supervision (control) in the power and heat power
                      industries.
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">-</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">23</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">Ministry of Health of Ukraine</span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">
                      The Ministry of Healthcare of Ukraine is the main
                      healthcare body in the system of central government. It is
                      based on former Ministries of Healthcare.The Ministry of
                      Health of Ukraine organizational structure is composed of
                      nine directorates, four departments, three divisions, four
                      sectors and patronage service.{" "}
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=https://en.moz.gov.ua/&amp;sa=D&amp;source=editors&amp;ust=1652627142370146&amp;usg=AOvVaw0A6RbIEXXrd69hBVwhoM9j"
                      >
                        https://en.moz.gov.ua/
                      </a>
                    </span>
                    <span className="c12">&nbsp;</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">24</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">
                      State Enterprise Center of Public Health of the Ministry
                      of Health of Ukraine
                    </span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">
                      State Enterprise Center of Public Health of the Ministry
                      of Health of Ukraine it is a health care institution
                      responsible for maintaining and improving the health of
                      the population, social and hygienic monitoring of
                      diseases, epidemiological surveillance and biosafety,
                      group and population prevention of diseases, control of
                      epidemics and strategic management in the field of public
                      health.{" "}
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=https://phc.org.ua/&amp;sa=D&amp;source=editors&amp;ust=1652627142371629&amp;usg=AOvVaw2ftCynB7xw6d8mf5Eukl8z"
                      >
                        https://phc.org.ua/
                      </a>
                    </span>
                    <span className="c12">&nbsp;</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">25</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">National Health Service of Ukraine</span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">
                      The National Health Service of Ukraine (NHSU) is the
                      central executive body that implements state policy in the
                      field &nbsp;of state financial guarantees for heathcare
                      servising of the population. &nbsp;Activities of the NHSU
                      are directed and coordinated by the &nbsp;Cabinet of
                      Ministers of Ukraine through the Minister of Health.
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=https://nszu.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652627142373180&amp;usg=AOvVaw0KGr7inhxmwuJRN8vI8W5E"
                      >
                        https://nszu.gov.ua/en
                      </a>
                    </span>
                    <span className="c12">&nbsp;</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">26</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">Ministry of Economy of Ukraine</span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">
                      The Ministry of Economy is a leading agency within the
                      system of Ukraine’s government agencies and institutions,
                      responsible for implementation of the uniform government
                      policy of national and regional economic and social
                      development and cooperation with the European Union.
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=https://www.me.gov.ua/?lang%3Den-GB&amp;sa=D&amp;source=editors&amp;ust=1652627142374675&amp;usg=AOvVaw1CjdnsXqFAImvomvtT-FUI"
                      >
                        https://www.me.gov.ua/?lang=en-GB
                      </a>
                    </span>
                    <span className="c12">&nbsp;</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">27</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">
                      Ministry of Education and Science of Ukraine
                    </span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">
                      The Ministry of Education and Science of Ukraine is the
                      central executive public body in the system of Ukrainian
                      government responsible for developing, implementation and
                      monitoring nation-wide policies in the areas of education
                      and science.
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=https://mon.gov.ua/eng&amp;sa=D&amp;source=editors&amp;ust=1652627142376256&amp;usg=AOvVaw0SBQ-V6yqd8CkJAUuaT1BG"
                      >
                        https://mon.gov.ua/eng
                      </a>
                    </span>
                    <span className="c12">&nbsp; </span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">28</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">Ministry of Justice of Ukraine</span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">
                      The Ministry of Justice is a central state executive body
                      and the main body among the central executive authorities
                      responsible for the implementation of state law policy. In
                      the established manner and within its terms of reference,
                      the Ministry resolves issues arising from the generally
                      accepted norms of international law and the international
                      treaties ratified by the Verkhovna Rada of Ukraine.
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=https://minjust.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652627142377698&amp;usg=AOvVaw0y-4FU0KXbbcYYWv1s84UA"
                      >
                        https://minjust.gov.ua/en/
                      </a>
                    </span>
                    <span className="c12">&nbsp;</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">29</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">
                      Ministry of Culture and Informational Policy of Ukraine
                    </span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">
                      The Ministry of Culture and Information Policy is the main
                      state authority in the system of central government of
                      Ukraine responsible for country&apos;s cultural development and
                      history preservation.
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=https://mkip.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652627142379122&amp;usg=AOvVaw1uCM1I28Qd9iHnhmGCmQ4j"
                      >
                        https://mkip.gov.ua/en/
                      </a>
                    </span>
                    <span className="c12">&nbsp;</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">30</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">Centre for Strategic Communication</span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">
                      Centre for Strategic Communication was established under
                      &nbsp;the Ministry of Culture and Information Policy of
                      Ukraine as one of the mechanisms for countering
                      &nbsp;disinformation by joint efforts of the state and
                      civil society. The Centre is focused on communication that
                      is aiming to counter &nbsp;external threats, in particular
                      information attacks of the Russian Federation.
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=https://spravdi.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652627142380570&amp;usg=AOvVaw1icwjeD512Hk6kOAw3ATKu"
                      >
                        https://spravdi.gov.ua/en/
                      </a>
                    </span>
                    <span className="c12">&nbsp;</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">31</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">
                      Ministry of Agrarian Policy and Food of Ukraine
                    </span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span>
                      The Ministry of Agrarian Policy and Food of Ukraine forms
                      and implements the state agricultural policy, state policy
                      in the domains of agriculture and food security of the
                      state, protection of plant variety rights, animal
                      husbandry, plant cultivation, rural development and other
                      areas of agro-industrial complex
                    </span>
                    <span className="c32">.</span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=https://minagro.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652627142382104&amp;usg=AOvVaw0h0NybnVWsvekrdBKHMIrP"
                      >
                        https://minagro.gov.ua/en
                      </a>
                    </span>
                    <span className="c12">&nbsp;</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">32</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">
                      Ministry of Internal Affairs of Ukraine
                    </span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c30">
                      The ministry carries out state policy for the protection
                      of rights and liberties of citizens, investigates unlawful
                      acts against the interest of society and state, fights
                      crime, provides civil order, ensures civil security and
                      traffic safety, and guarantees the security and protection
                      of important individuals.
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=https://mvs.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652627142383586&amp;usg=AOvVaw1FFk_hUAw9yoVbQEJQzOOD"
                      >
                        https://mvs.gov.ua/en
                      </a>
                    </span>
                    <span className="c12">&nbsp;</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">33</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">
                      Ministry of Infrastructure of Ukraine
                    </span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c7">
                      The Ministry of Infrastructure is the central body of
                      executive power in the areas of transport, roads, postal
                      service and infrastructure.
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=https://mtu.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652627142385155&amp;usg=AOvVaw0jVnUJsxVtcIspWZc7QCTi"
                      >
                        https://mtu.gov.ua/en/
                      </a>
                    </span>
                    <span className="c12">&nbsp;</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">34</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">
                      Ministry of Foreign Affairs of Ukraine
                    </span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">
                      The Ministry of Foreign Affairs of Ukraine is the main
                      body in the system of central executive bodies in the
                      formation and implementation of state policy in the field
                      of foreign relations of Ukraine.
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=https://mfa.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652627142386709&amp;usg=AOvVaw3qBThJ5iCAsz9xoopyMX7z"
                      >
                        https://mfa.gov.ua/en
                      </a>
                    </span>
                    <span className="c12">&nbsp;</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">35</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">National Anti-сorruption Bureau</span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">
                      The National Anti-Corruption Bureau of Ukraine is a
                      central executive agency with a special status responsible
                      for preventing, detecting, terminating, investigating, and
                      disclosing corruption and other criminal offences within
                      its jurisdiction, as well as preventing the commission of
                      new ones.{" "}
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=https://nabu.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652627142388187&amp;usg=AOvVaw3D2hZwKs04GYl_-D_4bhNB"
                      >
                        https://nabu.gov.ua/en
                      </a>
                    </span>
                    <span className="c12">&nbsp;</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">36</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">
                      National Agency on Corruption Prevention
                    </span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">
                      The National Agency on Corruption Prevention is a central
                      executive body with a special status. It is responsible
                      for the development of anti-corruption policy and
                      prevention of corruption.{" "}
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=https://nazk.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652627142389686&amp;usg=AOvVaw3fAPUVyqDUvqBsW0NX6Jox"
                      >
                        https://nazk.gov.ua/en/
                      </a>
                    </span>
                    <span className="c12">&nbsp;</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">37</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">
                      Specialized Anti-Corruption Prosecutor&apos;s Office
                    </span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">
                      The Specialized Anti-Corruption Prosecutor&apos;s Offic is an
                      independent structural unit of the General Prosecutor of
                      Ukraine, and is primarily responsible for supporting and
                      overseeing criminal investigations launched by the
                      National Anti-Corruption Bureau of Ukraine.
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">-</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">38</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">Ukrzaliznytsia</span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">
                      Ukrzaliznytsia accomplishes centralized management of the
                      transportation process in inland and interstate
                      communication regulates railway industrial and economic
                      activity.
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=https://www.uz.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652627142392533&amp;usg=AOvVaw0uOe9JcQ2H1RRrF_vIDwVg"
                      >
                        https://www.uz.gov.ua/en/
                      </a>
                    </span>
                    <span className="c12">&nbsp;</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">39</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">Pension Fund of Ukraine</span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">
                      The Pension Fund of Ukraine is a central executive body
                      that manages a solidarity system of compulsory state
                      pension provision, collects, accumulates and records
                      insurance premiums, allocates pensions and prepares
                      documents for their payment, provides timely and full
                      financing and payment pensions, burial assistance and
                      other social benefits.
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">-</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">40</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">Naftogaz</span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">
                      Naftogaz is the largest state-owned company in Ukraine. It
                      engages in a full cycle of field exploration and
                      development, production and exploration drilling, storage
                      of oil and gas, processing and distribution of oil
                      products, natural gas and liquefied gas to consumers.
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=https://www.naftogaz.com/en/&amp;sa=D&amp;source=editors&amp;ust=1652627142395821&amp;usg=AOvVaw2W5JhBiksTSGfveMnB8XPb"
                      >
                        https://www.naftogaz.com/en/
                      </a>
                    </span>
                    <span className="c12">&nbsp;</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">41</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">Ukrposhta</span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">
                      SC Ukrposhta is the only national postal operator in
                      Ukraine. It is the country’s main postal service.
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=https://www.ukrposhta.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652627142397835&amp;usg=AOvVaw3g5GZmb-95pzAYt1w8GmHW"
                      >
                        https://www.ukrposhta.ua/en
                      </a>
                    </span>
                    <span className="c12">&nbsp;</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">42</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">Office of the Prosecutor General</span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">
                      The Office of the Prosecutor General is the central body
                      in the prosecution system. It organizes and coordinates
                      the activities of all bodies of the prosecution system.
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c16">
                      <a
                        className="c8"
                        href="https://www.google.com/url?q=https://www.gp.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652627142399942&amp;usg=AOvVaw36g1M2JbVffYFveeNeSZB-"
                      >
                        https://www.gp.gov.ua/en
                      </a>
                    </span>
                    <span className="c12">&nbsp;</span>
                  </p>
                </td>
              </tr>
              <tr className="c5">
                <td className="c18" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">43</span>
                  </p>
                </td>
                <td className="c9" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">National Guard of Ukraine</span>
                  </p>
                </td>
                <td className="c2" colSpan="1" rowSpan="1">
                  <p className="c3 c6">
                    <span className="c12">
                      The National Guard of Ukraine. is the Ukrainian national
                      gendarmerie and internal military force. It is part of the
                      Ministry of Internal Affairs, responsible for public
                      security.{" "}
                    </span>
                  </p>
                </td>
                <td className="c1" colSpan="1" rowSpan="1">
                  <p className="c3">
                    <span className="c12">-</span>
                  </p>
                </td>
              </tr>
            </tbody>
          </table>
          <p className="c22 c6">
            <span className="c12"></span>
          </p>
          <p className="c4 c20">
            <span className="c12"></span>
          </p>
        </body>
      </div>
    </div>
  );
}
