import Head from "next/head";
import MediaList from "../components/MediaList/MediaList";
import { white_list_germany } from '../data/white_list_germany'
import { white_list_italy } from "../data/white_list_italy";

import styles from '../components/Sidebar/Sidebar.module.css'

export default function WhiteList() {
  return (
    <div>
      <Head>
        <title>Propaganda Diary | White List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <h4 className={styles.countryMedia}>GERMANY</h4>
        <MediaList data={white_list_germany} />
        <h4 className={styles.countryMedia}>ITALY</h4>
        <MediaList data={white_list_italy} />
      </>
    </div>
  );
}
