import Head from 'next/head'
import styles from '../../styles/Home.module.css'

export default function AboutUkr() {
  return (
    <div>
    <Head>
        <title>Propaganda Diary | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container + ' ' + styles.aboutPageWrap}>
      
          <p className="c7">
            <span className="c4"></span>
          </p>
          <p className="c8">
            <span className="c4">
              Російська інформаційна стратегія використовує існуючу
              напруженість, перебільшуючи суперечки та розбіжності між людьми та
              посилюючи народні заворушення, коли це можливо (наприклад, Росія
              намагалася посилити соціальні заворушення під час протестів
              «жовтих жилетів» у Франції). Внутрішня напруженість і зіткнення
              підривають розвинені демократії і змушують ці країни зосередитися
              на своєму внутрішньому порядку денному, а не намагатися просувати
              свої цінності та підтримувати прогрес у країнах, що розвиваються.
              Це негативно впливає на такі країни, як Україна, які шукають
              політичної підтримки з боку Заходу.
            </span>
          </p>
          <p className="c7">
            <span className="c4"></span>
          </p>
          <p className="c8">
            <span className="c4">
              Методи, які використовує російська пропаганда, добре відомі –
              маніпуляції (розмивання фактів неправильним тлумаченням), подання
              брехні як «альтернативних точок зору» та високоемоційна відверта
              брехня, у яку важко повірити, але легко запам’ятати. Знання їхніх
              методів і наративів може допомогти обмежити споживання фейків та
              інших деструктивних заяв Росії. Тому VoxCheck створив базу
              російських фейків, дезінформації та пропаганди у двух європейських
              країнах - Італії та Німеччині.{" "}
            </span>
          </p>
          <p className="c7">
            <span className="c4"></span>
          </p>
          <p className="c8">
            <span className="c4">
              Також рекомендуємо прочитати додаткову інформацію про Україну,
              російсько-українську війну та пропаганду Росії в наступних
              статтях:
            </span>
          </p>
          <p className="c7">
            <span className="c4"></span>
          </p>
          <ol className="c5 lst-kix_107m5i733v97-0 start" start="1">
            <li className="c0 li-bullet-0">
              <span className="c3">
                <a
                  className="c2"
                  href="https://voxukraine.org/rashyzm-abo-chomu-rosiyany-novi-natsysty/"
                >
                  Рашизм, або чому росіяни - нові нацисти{" "}
                </a>
              </span>
            </li>
            <li className="c0 li-bullet-0">
              <span className="c3">
                <a
                  className="c2"
                  href="https://voxukraine.org/oglyad-provokatsij-ta-dezinformatsiyi-rf/"
                >
                  Огляд провокацій та дезінформації РФ{" "}
                </a>
              </span>
            </li>
            <li className="c0 li-bullet-0">
              <span className="c3">
                <a
                  className="c2"
                  href="https://voxukraine.org/en/faq-on-the-russian-war-in-ukraine-what-are-we-fighting-for/"
                >
                  FAQ про російсько-українську війну: за що ми боремося?{" "}
                </a>
              </span>
            </li>
            <li className="c0 li-bullet-0">
              <span className="c3">
                <a
                  className="c2"
                  href="https://voxukraine.org/p-yat-prorahunkiv-blits-krygu-putina-v-ukrayini/"
                >
                  П’ять провалів бліцкригу Путіна в Україні{" "}
                </a>
              </span>
            </li>
            <li className="c0 li-bullet-0">
              <span className="c3">
                <a
                  className="c2"
                  href="https://voxukraine.org/try-rosijski-mify-vid-yakyh-treba-pozbutysya-negajno/"
                >
                  Три російські міфи, від яких треба позбутися негайно
                </a>
              </span>
            </li>
            <li className="c0 li-bullet-0">
              <span className="c3">
                <a
                  className="c2"
                  href="https://voxukraine.org/najkrashha-makroekonomichna-polityka-dlya-rosiyi/"
                >
                  Найкраща макроекономічна політика для Росії{" "}
                </a>
              </span>
            </li>
            <li className="c0 li-bullet-0">
              <span className="c3">
                <a
                  className="c2"
                  href="https://voxukraine.org/chym-my-ukrayintsi-vidriznyayemosya-vid-rosiyan-pragnennya-do-svobody-liberalnoyi-demokratiyi-ta-inklyuzyvnogo-suspilstva-yak-osnovni-markery-ukrayinsko-rosijskogo-rozryvu/"
                >
                  Чим ми, УКРАЇНЦІ, відрізняємося від росіян? Прагнення до
                  свободи, ліберальної демократії та інклюзивного суспільства як
                  основні маркери українсько-російського розриву!
                </a>
              </span>
            </li>
            <li className="c0 li-bullet-0">
              <span className="c3">
                <a
                  className="c2"
                  href="https://voxukraine.org/gaazkyj-trybunal-za-shho-i-yak-sudytymut-rosiyu-poyasnyuye-voxcheck/"
                >
                  Гаазький трибунал. За що і як судитимуть росію? Пояснює
                  VoxCheck
                </a>
              </span>
            </li>
            <li className="c0 li-bullet-0">
              <span className="c3">
                <a
                  className="c2"
                  href="https://voxukraine.org/zhenevski-konventsiyi-yak-yih-porushuye-rosiya-a-zvynuvachuye-v-tsomu-ukrayinu/"
                >
                  Женевські конвенції: як їх порушує росія, а звинувачує в цьому
                  Україну? Пояснює VoxCheck
                </a>
              </span>
            </li>
            <li className="c0 li-bullet-0">
              <span className="c3">
                <a
                  className="c2"
                  href="https://voxukraine.org/demokratiya-pid-bombamy/"
                >
                  Демократія під бомбами
                </a>
              </span>
            </li>
            <li className="c0 li-bullet-0">
              <span className="c3">
                <a
                  className="c2"
                  href="https://voxukraine.org/tse-ne-putin-tse-rosiya/"
                >
                  Це не Путін, це Росія{" "}
                </a>
              </span>
            </li>
            <li className="c0 li-bullet-0">
              <span className="c3">
                <a
                  className="c2"
                  href="https://voxukraine.org/sanktsiyi-na-rosijsku-naftu-budut-bolyuchymy-dlya-rosiyi-ale-ne-nadto-bolyuchymy-dlya-yes/"
                >
                  Санкції на російську нафту будуть болючими для Росії, але не
                  надто болючими – для ЄС
                </a>
              </span>
            </li>
            <li className="c0 li-bullet-0">
              <span className="c3">
                <a
                  className="c2"
                  href="https://voxukraine.org/finansovi-ta-ekonomichni-sanktsiyi-koly-bude-dostatno/"
                >
                  Фінансові та економічні санкції: коли буде достатньо?
                </a>
              </span>
            </li>
            <li className="c0 li-bullet-0">
              <span className="c3">
                <a
                  className="c2"
                  href="https://voxukraine.org/zupynit-rosijski-koruptsijni-groshi/"
                >
                  Зупиніть російські корупційні гроші
                </a>
              </span>
            </li>
            <li className="c0 li-bullet-0">
              <span className="c3">
                <a
                  className="c2"
                  href="https://voxukraine.org/bezpolotna-zona-nad-ukrayinoyu-ne-potrebuye-rezolyutsiyi-nato-chy-rady-bezpeky-oon-neobhidno-spivpratsyuvaty-ta-ne-dopustyty-shhob-zlo-znyshhylo-nashu-planetu/"
                >
                  Безпольотна зона над Україною не потребує резолюції НАТО чи
                  Ради Безпеки ООН: необхідно співпрацювати та не допустити, щоб
                  зло знищило нашу планету
                </a>
              </span>
            </li>
            <li className="c0 li-bullet-0">
              <span className="c3">
                <a
                  className="c2"
                  href="https://voxukraine.org/moralne-bankrutstvo-kupivli-rosijskyh-energonosiyiv/&amp;sa=D&amp;source=editors&amp;ust=1652630915871690&amp;usg=AOvVaw2ULxIhfjEhNWw-hgvLWHLQ"
                >
                  Моральне банкрутство купівлі російських енергоносіїв
                </a>
              </span>
            </li>
            <li className="c0 li-bullet-0">
              <span className="c3">
                <a
                  className="c2"
                  href="https://voxukraine.org/tsina-myru-bez-reformovanoyi-rosiyi-dlya-svitu-milyardy-shhorichno-vprodovzh-bagatoh-pokolin/"
                >
                  Ціна «миру» без реформованої Росії для світу – мільярди
                  щорічно впродовж багатьох поколінь
                </a>
              </span>
            </li>
            <li className="c0 li-bullet-0">
              <span className="c3">
                <a
                  className="c2"
                  href="https://voxukraine.org/zhorstka-pravda-pro-jmovirni-naslidky-napadu-rosiyi-na-ukrayinu/"
                >
                  Жорстка правда про ймовірні наслідки нападу Росії на Україну{" "}
                </a>
              </span>
            </li>
            <li className="c0 li-bullet-0">
              <span className="c3">
                <a
                  className="c2"
                  href="https://voxukraine.org/shho-bude-z-peremozhenoyu-rosijskoyu-imperiyeyu/"
                >
                  Що буде з переможеною російською імперією?
                </a>
              </span>
            </li>
          </ol>
          <p className="c7">
            <span className="c4"></span>
          </p>
    </div>
    </div>
  )
}
