import Head from "next/head";
import styles from '../../styles/Home.module.css'

export default function LangUk() {
  return (
    <div>
      <Head>
        <title>Propaganda Diary | UKR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>Ukrainian Lang</div>
    </div>
  );
}
