import Head from "next/head";
import styles from "../../styles/Home.module.css";

export default function HowUkr() {
  return (
    <div>
      <Head>
        <title>Propaganda Diary | How</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container + " " + styles.aboutPageWrap}>
        <body className="c29">
          <p className="c5">
            <span className="c6">
              Проект “Propaganda diary” щодо дезінформації про Україну в
              німецьких та італійських ЗМІ базується на методології. Тут ви
              можете отримати інформацію про наші методи та політику.
            </span>
          </p>
          <p className="c5">
            <span className="c6">&nbsp;</span>
          </p>
          <p className="c5">
            <span className="c20 c14 c25">Білий і чорний списки ЗМІ</span>
          </p>
          <p className="c5">
            <span className="c6">&nbsp;</span>
          </p>
          <p className="c5">
            <span className="c6">
              По-перше, для формування бази даних про дезінформацію необхідно
              було визначити ключові ЗМІ у відповідних країнах та відрізнити
              достовірні джерела від сумнівних. Таким чином ми створили білі та
              чорні списки ЗМІ Німеччини та Італії.
            </span>
          </p>
          <p className="c5">
            <span className="c6">&nbsp;</span>
          </p>
          <p className="c5">
            <span className="c6">
              ЗМІ в білому списку – це якісні ЗМІ, які надають достовірну
              інформацію про зовнішню та внутрішню політику України. Натомість
              джерела з чорного списку регулярно поширюють фейкові новини про
              Україну.
            </span>
          </p>
          <p className="c5">
            <span className="c6">&nbsp;</span>
          </p>
          <p className="c5">
            <span className="c6">
              Щоб розрізнити джерела та створити ці списки, ми використовували
              такі критерії:
            </span>
          </p>
          <p className="c5">
            <span className="c6">&nbsp;</span>
          </p>
          <p className="c5 c11">
            <span className="c14">●</span>
            <span className="c22 c14">
              &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </span>
            <span className="c20 c14">Зміст</span>
            <span className="c6">
              . Усі ЗМІ, як у білому, так і в чорному списках, регулярно
              повідомляють новини та публікують аналітичні статті про політику,
              міжнародні відносини, Україну зокрема.
            </span>
          </p>
          <p className="c5 c11">
            <span className="c14">●</span>
            <span className="c22 c14">
              &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </span>
            <span className="c20 c14">Професійні стандарти</span>
            <span className="c6">
              . Якісні ЗМІ в білому списку мають відповідати журналістським
              стандартам: всебічності та неупередженості висвітлення новин;
              об’єктивності та емоційної нейтральності; балансу думок; наявоісті
              та надійності джерел інформації; розділення фактів і думок. ЗМІ з
              чорного списку постійно нехтують цими стандартами, повідомляючи
              про Україну.
            </span>
          </p>
          <p className="c5 c11">
            <span className="c14">●</span>
            <span className="c22 c14">
              &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </span>
            <span className="c20 c14">Власність і прозорість</span>
            <span className="c6">
              . ЗМІ повинні публічно повідомляти про свого власника,
              фінансування та можливий конфлікт інтересів. Наприклад, деякі
              італійські та німецькі ЗМІ безпосередньо пов’язані з російськими
              державними інформаційними агентствами. Таким чином, такі ЗМІ,
              швидше за все, будуть поширювати дезінформацію про Україну.
            </span>
          </p>
          <p className="c5 c11">
            <span className="c14">●</span>
            <span className="c22 c14">
              &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </span>
            <span className="c20 c14">
              Результати моніторингу ЗМІ від Media Bias / Fact Check
            </span>
            <span className="c14">
              . Ми вибрали деякі ЗМІ відповідно до ресурсу
            </span>
            <span className="c14">
              <a
                className="c4"
                href="https://www.google.com/url?q=https://mediabiasfactcheck.com/&amp;sa=D&amp;source=editors&amp;ust=1652628409071381&amp;usg=AOvVaw1NevlMeF1UunSDrKtzR4O9"
              >
                &nbsp;
              </a>
            </span>
            <span className="c9">
              <a
                className="c4"
                href="https://www.google.com/url?q=https://mediabiasfactcheck.com/&amp;sa=D&amp;source=editors&amp;ust=1652628409071728&amp;usg=AOvVaw0qNnI6_eqZag_H1jLKMIup"
              >
                Media Bias / Fact Check
              </a>
            </span>
            <span className="c6">
              , незалежного веб-сайту, який оцінює упередженість, точність
              фактів і достовірність джерел. За даними цього ресурсу, вибрані
              ЗМІ з чорного списку мають дуже низький або змішаний рівень
              фактичної інформації. ЗМІ з білого списку оцінюються як найменш
              упереджені джерела та мають високий рівень репортажів щодо фактів.
            </span>
          </p>
          <p className="c5 c11">
            <span className="c14">●</span>
            <span className="c22 c14">
              &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </span>
            <span className="c14 c20">
              Результати моніторингу ЗМІ від EUvsDisinfo{" "}
            </span>
            <span className="c14">
              . Крім того, ми використовували бази даних EUvsDisinfo про
            </span>
            <span className="c14">
              <a
                className="c4"
                href="https://www.google.com/url?q=https://euvsdisinfo.eu/disinformation-cases/?text%3D%26date%3D%26disinfo_language%255B%255D%3DGerman%26disinfo_countries%255B%255D%3D77554%26per_page%3D&amp;sa=D&amp;source=editors&amp;ust=1652628409072175&amp;usg=AOvVaw1LaYybEroh01TYoCgNGT2e"
              >
                &nbsp;
              </a>
            </span>
            <span className="c9">
              <a
                className="c4"
                href="https://www.google.com/url?q=https://euvsdisinfo.eu/disinformation-cases/?text%3D%26date%3D%26disinfo_language%255B%255D%3DGerman%26disinfo_countries%255B%255D%3D77554%26per_page%3D&amp;sa=D&amp;source=editors&amp;ust=1652628409072436&amp;usg=AOvVaw05vdEVECl1We4FvsgaDuBq"
              >
                Німеччину
              </a>
            </span>
            <span className="c14">&nbsp;</span>
            <span className="c14">та</span>
            <span className="c14">
              <a
                className="c4"
                href="https://www.google.com/url?q=https://euvsdisinfo.eu/disinformation-cases/?text%3D%26date%3D%26disinfo_language%255B%255D%3DItalian%26disinfo_countries%255B%255D%3D77582%26per_page%3D&amp;sa=D&amp;source=editors&amp;ust=1652628409072746&amp;usg=AOvVaw3mcUDObX-qCIqsZhpkc7pJ"
              >
                &nbsp;
              </a>
            </span>
            <span className="c9">
              <a
                className="c4"
                href="https://www.google.com/url?q=https://euvsdisinfo.eu/disinformation-cases/?text%3D%26date%3D%26disinfo_language%255B%255D%3DItalian%26disinfo_countries%255B%255D%3D77582%26per_page%3D&amp;sa=D&amp;source=editors&amp;ust=1652628409072973&amp;usg=AOvVaw0Nwi4KLh0VD9FbOp2KI-GE"
              >
                Італію
              </a>
            </span>
            <span className="c14">
              , а також випадки розповсюдження фейків, зафіксовані німецькими та
              італійськими фактчекерами, які підписали Кодекс етики IFCN.
            </span>
            <span className="c14">
              <a
                className="c4"
                href="https://www.google.com/url?q=https://euvsdisinfo.eu/about/&amp;sa=D&amp;source=editors&amp;ust=1652628409073185&amp;usg=AOvVaw1dviSgFoxs_ZgDsIggCclZ"
              >
                &nbsp;
              </a>
            </span>
            <span className="c9">
              <a
                className="c4"
                href="https://www.google.com/url?q=https://euvsdisinfo.eu/about/&amp;sa=D&amp;source=editors&amp;ust=1652628409073332&amp;usg=AOvVaw0p2BNWIvkRWT0j9_h_zkTa"
              >
                EUvsDisinfo
              </a>
            </span>
            <span className="c9">&nbsp;</span>
            <span className="c6">
              – це проект робочої групи East StratCom Європейської служби
              зовнішніх дій (European External Action Service’s East StratCom
              Task Force). Він був створений спеціально для моніторингу та
              протидії російським дезінформаційним кампаніям у Європі.
            </span>
          </p>
          <p className="c5 c11">
            <span className="c14">●</span>
            <span className="c22 c14">
              &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </span>
            <span className="c20 c14">Результати власного моніторингу ЗМІ. </span>
            <span className="c6">
              При виборі ЗМІ для моніторингу ми орієнтувалися на якість
              репортажу про Україну. Джерела, які раніше публікували російську
              дезінформацію, були додані до чорного списку.
            </span>
          </p>
          <p className="c5 c11">
            <span className="c14">●</span>
            <span className="c22 c14">
              &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </span>
            <span className="c20 c14">
              Консультації з німецькими та італійськими фактчекерами та
              журналістами.{" "}
            </span>
            <span className="c6">
              Ми також зверталися за порадою до колег, які працюють у Німеччині
              та Італії. Представники різних організацій порадили звернути увагу
              на деякі ЗМІ, які раніше поширювали фейкові новини.
            </span>
          </p>
          <p className="c5">
            <span className="c6">&nbsp;</span>
          </p>
          <p className="c5">
            <span className="c25 c20 c14">Дезінформаційні наративи</span>
          </p>
          <p className="c5">
            <span className="c6">&nbsp;</span>
          </p>
          <p className="c5">
            <span className="c6">
              База даних складається з сотень маніпулятивних повідомлень
              німецьких та італійських ЗМІ. Щоб класифікувати цей набір даних,
              ми класифікували новини за небезпечними та дестабілізуючими
              наративами російської дезінформаційної кампанії.
            </span>
          </p>
          <p className="c5">
            <span className="c6">&nbsp;</span>
          </p>
          <p className="c5">
            <span className="c6">
              Різні репортажі новин є прикладами одного наративу дезінформації,
              коли вони передають одне й те саме повідомлення, чи то відверто,
              чи приховане, спрямоване на вплив на громадську думку у
              відповідних країнах шляхом спотворення картини реальності. Усі
              наративи в базі даних є типовими повідомленнями для російської
              дезінформаційної кампанії проти України. Наприклад, «Україна
              продовжує нарощування військ на Донбасі» та «Україна порушує режим
              припинення вогню» можуть бути яскравими прикладами наративу
              «Україна не виконує зобов’язань за Мінськими домовленостями»,
              оскільки вони мають однакове значення та мету з точки зору
              дезінформації.
            </span>
          </p>
          <p className="c5">
            <span className="c6">&nbsp;</span>
          </p>
          <p className="c5">
            <span className="c6">
              Існують також підвиди наративів дезінформації. Ці підтипи
              визначають загальний наратив. Наприклад, «США організували
              державний переворот в Україні 2014 року» є підтипом наративу
              «Майдан 2014 року був державним переворотом».
            </span>
          </p>
          <p className="c5">
            <span className="c6">&nbsp;</span>
          </p>
          <p className="c5">
            <span className="c6">
              Проте часто неможливо визначити точні мотиви авторів, які брали
              участь у поширенні фейкових новин. Тому ми не можемо підтвердити,
              що всі ці автори та ЗМІ навмисно поширювали дезінформацію про
              Україну. У той же час наративи в цих ЗМІ подібні або майже
              ідентичні наративам, які поширюють чиновники Російської Федерації.
            </span>
          </p>
          <p className="c5">
            <span className="c6">&nbsp;</span>
          </p>
          <p className="c5">
            <span className="c25 c20 c14">Види дезінформації</span>
          </p>
          <p className="c5">
            <span className="c6">&nbsp;</span>
          </p>
          <p className="c5">
            <span className="c6">
              Дезінформація – це неправдива або оманлива інформація, яка
              поширюється з метою впливу на громадську думку та/або приховування
              правди. Часто її навмисно використовують як інструмент в
              інформаційній війні. У випадку українсько-російської війни
              дезінформація використовується для спотворення фактів про зовнішню
              та внутрішню політику України та для створення негативного іміджу
              України в ЗМІ та міжнародній політиці.
            </span>
          </p>
          <p className="c5">
            <span className="c6">&nbsp;</span>
          </p>
          <p className="c5">
            <span className="c6">
              Під час оцінки німецьких та італійських ЗМІ з чорного списку ми
              виносимо такі вердикти щодо кожного дезінформаційного матеріалу:
            </span>
          </p>
          <p className="c5">
            <span className="c6">&nbsp;</span>
          </p>
          <p className="c5 c11">
            <span className="c14">●</span>
            <span className="c22 c14">
              &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </span>
            <span className="c20 c14">Фейк</span>
            <span className="c6">
              : інформація є повністю неправдивою та заснована на сумнівних
              джерелах.
            </span>
          </p>
          <p className="c5 c11">
            <span className="c14">●</span>
            <span className="c14 c22">
              &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </span>
            <span className="c20 c14">Маніпуляція</span>
            <span className="c6">
              : інформація частково правдива, але представлена в спотвореному
              контексті або не повністю. Автор маніпуляції намагається донести
              неправдиве повідомлення.
            </span>
          </p>
          <p className="c5 c11">
            <span className="c14">●</span>
            <span className="c22 c14">
              &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </span>
            <span className="c20 c14">Теорія змови: </span>
            <span className="c6">
              інформація неправдива, але ґрунтується на твердженнях, які не
              підтверджуються фактами, тобто деяких теоріях, що пояснюють події
              в результаті таємної змови.
            </span>
          </p>
          <p className="c5">
            <span className="c6">&nbsp;</span>
          </p>
          <p className="c5">
            <span className="c6">
              Ці види дезінформації є поширеними методами російських кампаній
              проти України. Найпоширенішими темами серед його наративів
              дезінформації є:
            </span>
          </p>
          <p className="c5">
            <span className="c6">&nbsp;</span>
          </p>
          <p className="c5 c11">
            <span className="c14">●</span>
            <span className="c22 c14">
              &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </span>
            <span className="c6">Євромайдан/Революція Гідності в Україні;</span>
          </p>
          <p className="c5 c11">
            <span className="c14">●</span>
            <span className="c22 c14">
              &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </span>
            <span className="c6">анексія Криму;</span>
          </p>
          <p className="c5 c11">
            <span className="c14">●</span>
            <span className="c22 c14">
              &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </span>
            <span className="c6">українсько-російська війна на Донбасі;</span>
          </p>
          <p className="c5 c11">
            <span className="c14">●</span>
            <span className="c22 c14">
              &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </span>
            <span className="c6">
              історичні події, особливо пов'язані з історією
              українсько-російських відносин;
            </span>
          </p>
          <p className="c5 c11">
            <span className="c14">●</span>
            <span className="c22 c14">
              &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </span>
            <span className="c6">
              відносини України зі США, НАТО, ЄС та іншими партнерами;
            </span>
          </p>
          <p className="c5 c11">
            <span className="c14">●</span>
            <span className="c22 c14">
              &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </span>
            <span className="c6">реформи в Україні;</span>
          </p>
          <p className="c5 c11">
            <span className="c14">●</span>
            <span className="c22 c14">
              &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </span>
            <span className="c6">економіка України;</span>
          </p>
          <p className="c5 c11">
            <span className="c14">●</span>
            <span className="c22 c14">
              &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </span>
            <span className="c6">«нацисти та ультранаціоналісти» в Україні;</span>
          </p>
          <p className="c5 c11">
            <span className="c14">●</span>
            <span className="c22 c14">
              &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </span>
            <span className="c6">
              теорії змови про «зовнішнє управління» в Україні, тобто вплив
              Заходу на зовнішню та внутрішню політику України.
            </span>
          </p>
          <p className="c5">
            <span className="c6">&nbsp;</span>
          </p>
          <p className="c5">
            <span className="c25 c20 c14">Процес перевірки фактів</span>
          </p>
          <p className="c5">
            <span className="c6">&nbsp;</span>
          </p>
          <p className="c5">
            <span className="c6">
              Автори VoxCheck дотримуються прозорої політики під час перевірки
              фактів та розвінчування російської дезінформації про Україну. У
              наших статтях ми надаємо всі джерела для перегляду з достатньою
              детальністю, щоб читачі могли відтворити нашу роботу, за винятком
              випадків, коли особиста безпека джерела може бути порушена. У
              таких випадках ми надаємо найбільш детальну інформацію. Якість
              фактчеккінгу забезпечує редколегія проекту.
            </span>
          </p>
          <p className="c5">
            <span className="c6">&nbsp;</span>
          </p>
          <p className="c5">
            <span className="c14">VoxCheck,</span>
            <span className="c14">
              <a
                className="c4"
                href="https://www.google.com/url?q=https://ifcncodeofprinciples.poynter.org/signatories&amp;sa=D&amp;source=editors&amp;ust=1652628409076664&amp;usg=AOvVaw2JiYCZEPdIXGyU0UXra6r5"
              >
                &nbsp;
              </a>
            </span>
            <span className="c9">
              <a
                className="c4"
                href="https://www.google.com/url?q=https://ifcncodeofprinciples.poynter.org/signatories&amp;sa=D&amp;source=editors&amp;ust=1652628409076856&amp;usg=AOvVaw20tw3WPMFSQLivx0-uT6D7"
              >
                який підписав
              </a>
            </span>
            <span className="c14">&nbsp;</span>
            <span className="c14">Кодекс принципів IFCN, дотримується</span>
            <span className="c14">
              <a
                className="c4"
                href="https://www.google.com/url?q=https://www.ifcncodeofprinciples.poynter.org/know-more/the-commitments-of-the-code-of-principles&amp;sa=D&amp;source=editors&amp;ust=1652628409077088&amp;usg=AOvVaw2IUjfBTonC71eY7VaI900W"
              >
                &nbsp;
              </a>
            </span>
            <span className="c9">
              <a
                className="c4"
                href="https://www.google.com/url?q=https://www.ifcncodeofprinciples.poynter.org/know-more/the-commitments-of-the-code-of-principles&amp;sa=D&amp;source=editors&amp;ust=1652628409077282&amp;usg=AOvVaw3XfB7oT41p3hVIQjHLro0O"
              >
                зобов'язань щодо
              </a>
            </span>
            <span className="c9">&nbsp;</span>
            <span className="c6">:</span>
          </p>
          <p className="c5">
            <span className="c6">&nbsp;</span>
          </p>
          <p className="c5 c11">
            <span className="c14">●</span>
            <span className="c22 c14">
              &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </span>
            <span className="c6">безпартійності і справедливості;</span>
          </p>
          <p className="c5 c11">
            <span className="c14">●</span>
            <span className="c22 c14">
              &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </span>
            <span className="c6">стандартів та прозорості джерел;</span>
          </p>
          <p className="c5 c11">
            <span className="c14">●</span>
            <span className="c22 c14">
              &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </span>
            <span className="c6">прозорості фінансування та організації;</span>
          </p>
          <p className="c5 c11">
            <span className="c14">●</span>
            <span className="c22 c14">
              &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </span>
            <span className="c6">
              стандартизованості та прозорості методології;
            </span>
          </p>
          <p className="c5 c11">
            <span className="c14">●</span>
            <span className="c22 c14">
              &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </span>
            <span className="c6">відкритої та чесної політики виправлень.</span>
          </p>
          <p className="c5">
            <span className="c6">&nbsp;</span>
          </p>
          <p className="c5">
            <span className="c14">
              Ви можете знайти додаткову інформацію про нашу політику та
              принципи на{" "}
            </span>
            <span className="c9">
              <a
                className="c4"
                href="https://www.google.com/url?q=https://voxcheck.voxukraine.org/&amp;sa=D&amp;source=editors&amp;ust=1652628409078261&amp;usg=AOvVaw3rLBoNo-z4ca63UQtpAP8S"
              >
                офіційному веб-сайті
              </a>
            </span>
            <span className="c9">&nbsp;VoxCheck</span>
            <span className="c6">.</span>
          </p>
          <p className="c5">
            <span className="c6">&nbsp;</span>
          </p>
          <h3 className="c27" id="h.pbocq961dn0">
            <span className="c20 c28">
              Основні джерела перевіреної інформації про Україну
            </span>
          </h3>
          <p className="c5">
            <span className="c20 c26">&nbsp;</span>
          </p>
          <p className="c5">
            <span className="c1">&nbsp;</span>
          </p>
          <a id="t.18f51b844711974066ab570f3d67610ffe6d8477"></a>
          <a id="t.0"></a>
          <table className="c46">
            <tbody>
              <tr className="c42">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c38 c20">№</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c38 c20">Джерело</span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c38 c20">Опис</span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c20 c38">Посилання на сайт UK</span>
                  </p>
                </td>
              </tr>
              <tr className="c16">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">1</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">Державна служба статистики України</span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Державна служба статистики України (Держстат) є спеціально
                      уповноваженим центральним органом виконавчої влади у сфері
                      статистики, діяльність якого спрямовується та
                      координується Кабінетом Міністрів України та забезпечує
                      формування та реалізує державну політику у сфері
                      статистики.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=http://www.ukrstat.gov.ua/&amp;sa=D&amp;source=editors&amp;ust=1652628409081621&amp;usg=AOvVaw1OwU7EnHKrfqwgGRShSoNo"
                      >
                        http://www.ukrstat.gov.ua/
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c17">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">2</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">Офіс Президента України</span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      В обов’язки ОПУ входить надання адміністративно-правової,
                      консультативної, консультативної, медійної, аналітичної та
                      іншої допомоги Президенту при здійсненні повноважень.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=https://www.president.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652628409082814&amp;usg=AOvVaw2F6EsUTEdoEtdJ-8lXOEli"
                      >
                        https://www.president.gov.ua/uk
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c23">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">3</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">Служба Безпеки України</span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Служба безпеки України є головним органом безпеки України.
                      Її основними пріоритетами є контррозвідка, захист
                      національної державності, боротьба з тероризмом, захист
                      інформаційної безпеки, захист державної таємниці.
                    </span>
                  </p>
                  <p className="c0">
                    <span className="c1">&nbsp;</span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=https://ssu.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652628409084080&amp;usg=AOvVaw3y9QjPMYQAjMAfHwMfZ_pD"
                      >
                        https://ssu.gov.ua/uk
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c30">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">4</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Рада національної безпеки і оборони України
                    </span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Рада національної безпеки і оборони України є координуючим
                      органом з питань національної безпеки і оборони при
                      Президентові України.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=https://www.rnbo.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652628409085305&amp;usg=AOvVaw2TWDelEIjz_Se_wp7NN-Qo"
                      >
                        https://www.rnbo.gov.ua/uk/
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c23">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">5</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">Центр протидії дезінформації</span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Центр протидії дезінформації є робочим органом Ради
                      національної безпеки і оборони України. Центр здійснює
                      заходи щодо протидії поточним та прогнозованим загрозам
                      національній безпеці та національним інтересам України в
                      інформаційній сфері.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">-</span>
                  </p>
                </td>
              </tr>
              <tr className="c13">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">6</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">Уряд України</span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Уряд України або Кабінет Міністрів України є вищим органом
                      державної виконавчої влади в Україні. До складу органу
                      входять Прем'єр-міністр України, віце-прем'єр-міністри та
                      інші міністри з різних установ. Прем'єр-міністр очолює
                      кабінет.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=https://www.kmu.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652628409087344&amp;usg=AOvVaw2atspzkdmsaToS6s6FZ8hJ"
                      >
                        https://www.kmu.gov.ua/uk
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c35">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">7</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c5">
                    <span className="c1">Верховна Рада України</span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Верховна Рада є парламентом України. Є єдиним органом
                      законодавчої влади в Україні. До складу Верховної Ради
                      входять 450 депутатів, які обираються українським народом.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=https://www.rada.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652628409088489&amp;usg=AOvVaw1Mv8VoCFXcnfTpLjWwx40G"
                      >
                        https://www.rada.gov.ua/uk
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c16">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">8</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c5">
                    <span className="c1">Державна казначейська служба України</span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Державна казначейська служба України є центральним органом
                      виконавчої влади України, що реалізує державну політику у
                      сфері казначейського обслуговування бюджетних коштів.
                      Діяльність служби спрямовується та координується Кабінетом
                      Міністрів України через Міністра фінансів України.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=https://www.treasury.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652628409089712&amp;usg=AOvVaw2EwzDz-CUkxEp8BTzXyqhR"
                      >
                        https://www.treasury.gov.ua/uk
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c36">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c5">
                    <span className="c1">9</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">Державна податкова служба України</span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Державна податкова служба України є центральним органом
                      виконавчої влади у сфері податків в Україні. Діяльність
                      служби спрямовується та координується Кабінетом Міністрів
                      України через Міністра фінансів.
                    </span>
                  </p>
                  <p className="c0">
                    <span className="c1">
                      Служба реалізує державну податкову політику та національну
                      політику у сфері протидії правопорушенням під час
                      застосування податкового законодавства
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=https://tax.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652628409090830&amp;usg=AOvVaw2qq-uqAuwy0bOoNdq0Ei5w"
                      >
                        https://tax.gov.ua/uk/
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c32">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c5">
                    <span className="c1">10</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">Митна служба України</span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Державна митна служба України є центральним органом
                      виконавчої влади України, що реалізує національну митну
                      політику та державну політику у сфері протидії
                      правопорушенням під час застосування законодавства про
                      національну митну справу. Діяльність служби спрямовується
                      та координується Кабінетом Міністрів України через
                      Міністра фінансів.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=https://customs.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652628409091908&amp;usg=AOvVaw3fNwUig8X3FXFDqIk3rria"
                      >
                        https://customs.gov.ua/uk
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c41">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">11</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">Державна прикордонна служба України</span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c31">
                      Державна прикордонна служба України є правоохоронним
                      органом, на який покладаються завдання щодо забезпечення
                      недоторканності державних кордонів та захисту суверенних
                      прав України в межах її виключної (морської) економічної
                      зони.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=https://dpsu.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652628409092901&amp;usg=AOvVaw0ghJUIJC4PcOZyWjg6dOI8"
                      >
                        https://dpsu.gov.ua/en/
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c15">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">12</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">Національний банк України</span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Національний банк України є державним органом,
                      відповідальним за проведення єдиної державної політики у
                      сфері грошового обігу країни, у тому числі зміцнення
                      національної валютної одиниці. Його місія – забезпечення
                      цінової та фінансової стабільності з метою сприяння
                      сталому економічному розвитку України.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=https://bank.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652628409093982&amp;usg=AOvVaw2zyhGlXBCrxYEKPXp3DAQy"
                      >
                        https://bank.gov.ua/uk/
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c23">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">13</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Міністерство цифрової трансформації України
                    </span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Міністерство цифрової трансформації України є державним
                      органом. Його головна мета – сприяти цифровізації в
                      Україні, особливо розвитку інфраструктури, створення
                      сприятливого середовища для ІТ-сектору та популяризації
                      цифрової грамотності.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">-</span>
                  </p>
                </td>
              </tr>
              <tr className="c45">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">14</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">Міністерство фінансів України</span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Міністерство фінансів України відповідає за формування та
                      реалізацію таких ключових напрямів державної політики:
                      бюджетна політика, податкова та митна політика, боргова
                      політика. міжнародне фінансове співробітництво. Місія
                      міністерства – забезпечити фінансову базу для належного
                      виконання державних функцій за підтримки виваженої
                      бюджетної політики, а також створити сприятливі умови для
                      стабільного економічного розвитку.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=https://mof.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652628409095820&amp;usg=AOvVaw1Tm3OCpwlWq1CXYtzR-7OX"
                      >
                        https://mof.gov.ua/uk
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c36">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">15</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">Міністерство оборони України</span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Міністерство оборони України є головним (провідним)
                      органом у системі центральних органів виконавчої влади із
                      забезпечення реалізації державної політики у сфері
                      оборони. Бере участь у реалізації державної політики щодо
                      оборони та військового будівництва, координації діяльності
                      державних органів та органів місцевого самоврядування з
                      підготовки держави до оборони.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=https://www.mil.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652628409096772&amp;usg=AOvVaw2ntqT0VRryxv-IghJ9xaYv"
                      >
                        https://www.mil.gov.ua/uk/
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c30">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">16</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">Розвідка оборони</span>
                  </p>
                  <p className="c0">
                    <span className="c1">Міністерства оборони України</span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c19">
                      Розвідка оборони України здійснює розвідку в сферах
                      оборони, розвитку військового потенціалу, військової та
                      військово-технічної та кібербезпеки.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=https://gur.gov.ua/en.html&amp;sa=D&amp;source=editors&amp;ust=1652628409097812&amp;usg=AOvVaw0IyrDkJNKpLy_sPGSBH4Cw"
                      >
                        https://gur.gov.ua/uk.html
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c15">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">17</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Міністерство з питань реінтеграції тимчасово окупованих
                      територій України
                    </span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Міністерство з реінтеграції тимчасово окупованих територій
                      є державним міністерством в Україні, яке вирішує завдання
                      оперативного реагування на проблеми та загрози, пов’язані
                      з проведенням антитерористичної операції в окремих районах
                      Донецької та Луганської областей, а також з тимчасова
                      окупація території України.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=https://minre.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652628409098786&amp;usg=AOvVaw0J2mqsyA7G0FL51cu5fKsv"
                      >
                        https://minre.gov.ua/uk
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c17">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">18</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">Децентралізація в Україні</span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Реформа децентралізації є офіційним веб-сайтом для реформ.
                      Децентралізація означає делегування значних повноважень і
                      бюджетів від державних органів місцевим органам влади
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=https://decentralization.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652628409099714&amp;usg=AOvVaw26XecVHwOEcAfBeHNvdVyC"
                      >
                        https://decentralization.gov.ua/uk/
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c13">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">19</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Міністерство соціальної політики України
                    </span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Міністерство соціальної політики України є державним
                      відомством України, відповідальним за встановлення
                      трудових відносин, сім'ї та дітей, імміграції та торгівлі
                      людьми, прав жінок, прав дитини та гуманітарної допомоги.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=https://www.msp.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652628409100667&amp;usg=AOvVaw2R3QZRWiyoAOenTXVZgMc1"
                      >
                        https://www.msp.gov.ua/en/
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c36">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">20</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Міністерство розвитку громад і територій України
                    </span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Державне регулювання в архітектурі, будівництві та
                      містобудуванні здійснює Міністерство розвитку громад і
                      територій України (Мінрегіон). Пріоритетними завданнями
                      міністерства є розробка та вдосконалення регулювання в
                      архітектурі, будівництві та містобудуванні з урахуванням
                      вимог законодавства ЄС у відповідних сферах, спрощення
                      дозвільних процедур та впровадження нових технологій.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=https://www.minregion.gov.ua/en/ministry-for-development-of-communities-and-territories-of-ukraine&amp;sa=D&amp;source=editors&amp;ust=1652628409101669&amp;usg=AOvVaw0mOyI51nan_RjOJedUAH1S"
                      >
                        https://www.minregion.gov.ua/uk/
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c45">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">21</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Міністерство екології та охорони навколишнього природного
                      середовища України
                    </span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Міністерство екології та природних ресурсів України є
                      центральним органом виконавчої влади, діяльність якого
                      керується та координується Кабінетом Міністрів України.
                      Міністерство екології та природних ресурсів здійснює
                      діяльність у сфері охорони навколишнього середовища,
                      екологічної безпеки, поводження з відходами, шкідливими
                      хімікатами, пестицидами та агрохімікатами та здійснює
                      державну екологічну експертизу.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=https://mepr.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652628409102655&amp;usg=AOvVaw0M_NXbJ-5eJWUW6iAJFl0H"
                      >
                        https://mepr.gov.ua/uk/
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c15">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">22</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Міністерство енергетики та вугільної промисловості України
                    </span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Міненерговугілля забезпечує формування та реалізує
                      державну політику в електроенергетиці,
                      атомно-промисловому, вугільно-промисловому,
                      торфодобувному, нафтогазопереробному комплексах, а також
                      забезпечує формування державна політика у сфері нагляду
                      (контролю) в енергетиці та теплоенергетиці.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">-</span>
                  </p>
                </td>
              </tr>
              <tr className="c15">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">23</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">МОЗ України</span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Міністерство охорони здоров'я України є основним органом
                      охорони здоров'я в системі центральної влади. Його
                      створено на базі колишніх міністерств охорони здоров’я.
                      Організаційна структура МОЗ України складається з дев’яти
                      управлінь, чотирьох управлінь, трьох відділів, чотирьох
                      секторів та патронатної служби.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=https://en.moz.gov.ua/&amp;sa=D&amp;source=editors&amp;ust=1652628409104423&amp;usg=AOvVaw2aIs0kOWSNCyXcfauAF0uQ"
                      >
                        https://en.moz.gov.ua/
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c32">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">24</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      ДП «Центр громадського здоров’я» МОЗ України
                    </span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Державне підприємство «Центр громадського здоров’я» МОЗ
                      України — заклад охорони здоров’я, що відповідає за
                      збереження та зміцнення здоров’я населення,
                      соціально-гігієнічний моніторинг захворювань,
                      епідеміологічний нагляд та біобезпеку, групову та
                      популяційну профілактику захворювань, контроль епідемій та
                      стратегічного управління у сфері охорони здоров'я.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=https://phc.org.ua/&amp;sa=D&amp;source=editors&amp;ust=1652628409105533&amp;usg=AOvVaw1xcVmVeYj_v7Uf5uOSjr9U"
                      >
                        https://phc.org.ua/
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c16">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">25</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">Національна служба здоров'я України</span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Національна служба здоров'я України (НСЗУ) є центральним
                      органом виконавчої влади, що реалізує державну політику у
                      сфері державних фінансових гарантій медичного
                      обслуговування населення. Діяльність НСЗУ спрямовується та
                      координується Кабінетом Міністрів України через Міністра
                      охорони здоров’я.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=https://nszu.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652628409106521&amp;usg=AOvVaw1FfUi2vEfHKtBto0S-oS2k"
                      >
                        https://nszu.gov.ua/uk
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c24">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">26</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">Міністерство економіки України</span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Міністерство економіки є провідним органом у системі
                      державних органів та установ України, відповідальним за
                      реалізацію єдиної державної політики національного та
                      регіонального економічного та соціального розвитку та
                      співробітництва з Європейським Союзом.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=https://www.me.gov.ua/?lang%3Den-GB&amp;sa=D&amp;source=editors&amp;ust=1652628409107732&amp;usg=AOvVaw3PdZqNA0b_-ma2f1bLlIN9"
                      >
                        https://www.me.gov.ua/?lang=en-GB
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c23">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">27</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">Міністерство освіти і науки України</span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Міністерство освіти і науки України є центральним
                      державним органом виконавчої влади в системі державної
                      влади України, відповідальним за розробку, реалізацію та
                      моніторинг загальнодержавної політики у сфері освіти і
                      науки.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=https://mon.gov.ua/eng&amp;sa=D&amp;source=editors&amp;ust=1652628409108790&amp;usg=AOvVaw0ieTzXRPGLrIt4ozKoh9YG"
                      >
                        https://mon.gov.ua/eng
                      </a>
                    </span>
                    <span className="c1">&nbsp;</span>
                  </p>
                </td>
              </tr>
              <tr className="c39">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">28</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">Міністерство юстиції України</span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Міністерство юстиції є центральним органом державної
                      виконавчої влади та основним органом серед центральних
                      органів виконавчої влади, що здійснює державно-правову
                      політику. Міністерство в установленому порядку та в межах
                      повноважень вирішує питання, що випливають із
                      загальновизнаних норм міжнародного права та міжнародних
                      договорів, ратифікованих Верховною Радою України.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=https://minjust.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652628409109730&amp;usg=AOvVaw1aCr8puUFEFoTxdYFzcxEw"
                      >
                        https://minjust.gov.ua/uk/
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c17">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">29</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Міністерство культури та інформаційної політики України
                    </span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Міністерство культури та інформаційної політики є головним
                      державним органом у системі центральної влади України,
                      відповідальним за розвиток культури та збереження історії
                      країни.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=https://mkip.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652628409110711&amp;usg=AOvVaw0earv4pxhPlMOK_-pb8TOf"
                      >
                        https://mkip.gov.ua/uk/
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c32">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">30</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">Центр стратегічних комунікацій</span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Центр стратегічних комунікацій створено при Міністерстві
                      культури та інформаційної політики України як один із
                      механізмів протидії дезінформації спільними зусиллями
                      держави та громадянського суспільства. Центр орієнтований
                      на комунікацію, спрямовану на протидію зовнішнім загрозам,
                      зокрема інформаційним атакам Російської Федерації.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=https://spravdi.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652628409111745&amp;usg=AOvVaw3bqy5pc6dR0zZ7h7zbqy8H"
                      >
                        https://spravdi.gov.ua/uk/
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c21">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">31</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Міністерство аграрної політики та продовольства України
                    </span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span>
                      Міністерство аграрної політики та продовольства України
                      формує та реалізує державну аграрну політику, державну
                      політику у сферах сільського господарства та продовольчої
                      безпеки держави, охорони прав на сорти рослин,
                      тваринництва, рослинництва, розвитку села та інших сфер
                      агропромислового комплексу. -промисловий комплекс{" "}
                    </span>
                    <span className="c47">.</span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=https://minagro.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652628409112746&amp;usg=AOvVaw0o2CmIwwuLF8k-KCax7VA0"
                      >
                        https://minagro.gov.ua/uk
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c33">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">32</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Міністерство внутрішніх справ України
                    </span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c43">
                      Міністерство здійснює державну політику щодо захисту прав
                      і свобод громадян, розслідує протиправні дії проти
                      інтересів суспільства та держави, веде боротьбу зі
                      злочинністю, забезпечує цивільний порядок, забезпечує
                      громадянську безпеку та безпеку дорожнього руху, гарантує
                      безпеку та захист важливих осіб. .
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=https://mvs.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652628409113758&amp;usg=AOvVaw1ocEYSSMZsxrFR54EPVmyS"
                      >
                        https://mvs.gov.ua/uk
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c40">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">33</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">Міністерство інфраструктури України</span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c34">
                      Мінінфраструктури є центральним органом виконавчої влади у
                      сферах транспорту, доріг, поштового зв'язку та
                      інфраструктури.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=https://mtu.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652628409114761&amp;usg=AOvVaw0Use_jUagsgXC_saSEKidk"
                      >
                        https://mtu.gov.ua/uk/
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c17">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">34</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Міністерство закордонних справ України
                    </span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Міністерство закордонних справ України є головним органом
                      у системі центральних органів виконавчої влади з
                      формування та реалізації державної політики у сфері
                      зовнішніх зносин України.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=https://mfa.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652628409115805&amp;usg=AOvVaw08ItsNnHgv1e5TECvX37YY"
                      >
                        https://mfa.gov.ua/uk
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c15">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">35</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">Національне антикорупційне бюро</span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Національне антикорупційне бюро України є центральним
                      органом виконавчої влади зі спеціальним статусом,
                      відповідальним за запобігання, виявлення, припинення,
                      розслідування та розкриття корупційних та інших
                      кримінальних правопорушень, віднесених до його
                      компетенції, а також недопущення вчинення нових.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=https://nabu.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652628409116972&amp;usg=AOvVaw2t4othKGUPHd8nvY8GDfkq"
                      >
                        https://nabu.gov.ua/uk
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c17">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">36</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Національне агентство з питань запобігання корупції
                    </span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Національне агентство з питань запобігання корупції є
                      центральним органом виконавчої влади зі спеціальним
                      статусом. Він відповідає за розробку антикорупційної
                      політики та запобігання корупції.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=https://nazk.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652628409118345&amp;usg=AOvVaw2rj0xl4FJ14z7gKYenOtrV"
                      >
                        https://nazk.gov.ua/uk/
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c16">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">37</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Спеціалізована антикорупційна прокуратура
                    </span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Спеціалізована антикорупційна прокуратура є самостійним
                      структурним підрозділом Генеральної прокуратури України,
                      на яку в першу чергу покладається забезпечення та нагляд
                      за розслідуванням кримінальних справ, розпочатих
                      Національним антикорупційним бюро України.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">-</span>
                  </p>
                </td>
              </tr>
              <tr className="c17">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">38</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">Укрзалізниця</span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Укрзалізниця здійснює централізоване управління перевізним
                      процесом у внутрішньому та міждержавному сполученні,
                      регулює виробничо-господарську діяльність залізниці.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=https://www.uz.gov.ua/en/&amp;sa=D&amp;source=editors&amp;ust=1652628409120436&amp;usg=AOvVaw2GKdpFdASn-uHpA52UB6nZ"
                      >
                        https://www.uz.gov.ua/uk/
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c36">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">39</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">Пенсійний фонд України</span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Пенсійний фонд України є центральним органом виконавчої
                      влади, який здійснює управління солідарною системою
                      загальнообов’язкового державного пенсійного забезпечення,
                      збирає, накопичує та обліковує страхові внески, призначає
                      пенсії та готує документи на їх виплату, забезпечує
                      своєчасне та повне фінансування та виплату пенсій,
                      допомоги на поховання та інші соціальні виплати.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">-</span>
                  </p>
                </td>
              </tr>
              <tr className="c16">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">40</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">Нафтогаз</span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Нафтогаз – найбільша державна компанія в Україні. Вона
                      займається повним циклом розвідки та розробки родовищ,
                      видобутку та розвідувального буріння, зберігання нафти і
                      газу, переробки та розподілу нафтопродуктів, природного
                      газу та скрапленого газу споживачам.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=https://www.naftogaz.com/en/&amp;sa=D&amp;source=editors&amp;ust=1652628409122306&amp;usg=AOvVaw09M2nXalkUHRyiC39Cthqi"
                      >
                        https://www.naftogaz.com/uk/
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c18">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">41</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">Укрпошта</span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      ДП «Укрпошта» — єдиний національний оператор поштового
                      зв’язку в Україні. Це головна поштова служба країни.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=https://www.ukrposhta.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652628409123477&amp;usg=AOvVaw1yMkD71ufq7Wq3qf7BtJEy"
                      >
                        https://www.ukrposhta.ua/uk
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c30">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">42</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">Офіс Генеральної прокуратури</span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Центральним органом у системі прокуратури є Генеральна
                      прокуратура. Організовує та координує діяльність усіх
                      органів системи прокуратури.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c3">
                      <a
                        className="c4"
                        href="https://www.google.com/url?q=https://www.gp.gov.ua/en&amp;sa=D&amp;source=editors&amp;ust=1652628409124661&amp;usg=AOvVaw3MGrabWrfwAqC5FQ1y6hv2"
                      >
                        https://www.gp.gov.ua/en
                      </a>
                    </span>
                  </p>
                </td>
              </tr>
              <tr className="c35">
                <td className="c7" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">43</span>
                  </p>
                </td>
                <td className="c10" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">Національна гвардія України</span>
                  </p>
                </td>
                <td className="c12" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">
                      Національна гвардія України. є українською національною
                      жандармерією та внутрішніми військовими силами. Входить до
                      складу Міністерства внутрішніх справ, відповідального за
                      громадську безпеку.
                    </span>
                  </p>
                </td>
                <td className="c8" colSpan="1" rowSpan="1">
                  <p className="c0">
                    <span className="c1">-</span>
                  </p>
                </td>
              </tr>
            </tbody>
          </table>
          <p className="c5">
            <span className="c1">&nbsp;</span>
          </p>
          <p className="c5 c44">
            <span className="c1">&nbsp;</span>
          </p>
          <p className="c0 c37">
            <span className="c6"></span>
          </p>
        </body>
      </div>
    </div>
  );
}
